### ISSUE TITLE
Regression in 1.6 onwards: duplicated check constraints in Create Table DDL

### ISSUE THREAD

**Issue by cansjt** [sqlalchemy/alembic#1004]
**Describe the bug**

Finally being able to upgrade from the latest 1.5.x to 1.7.x, I stumbled on the following problem: when built using SQLAlchemy expressions, check constraints may be duplicated in the DDL statement produced by alembic.

**Expected behavior**

**To Reproduce**
Please try to provide a [Minimal, Complete, and Verifiable](http://stackoverflow.com/help/mcve) example, with the migration script and/or the SQLAlchemy tables or models involved.
See also [Reporting Bugs](https://www.sqlalchemy.org/participate.html#bugs) on the website.

```py
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID

# revision identifiers, used by Alembic.
revision = 'b126031fd753'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # Columns forward declarations for those used in constraints
    column = sa.Column('column', sa.Integer, nullable=True)

    op.create_table(
        't',
        sa.Column('t_id', UUID, nullable=False),
        column,
        sa.PrimaryKeyConstraint('t_id'),
        sa.CheckConstraint(sa.and_(column > 0, column < 5),
                           name='ck_dim_job_ad_remote_type_range',
                           ),
        schema='issue',
    )


def downgrade():
    op.drop_table('t', schema='issue')
```

Will produce the following DLL:
```sql
CREATE TABLE issue.t (
    t_id UUID NOT NULL, 
    "column" INTEGER, 
    PRIMARY KEY (t_id), 
    CONSTRAINT ck_dim_job_ad_remote_type_range CHECK ("column" > 0 AND "column" < 5), 
    CONSTRAINT ck_dim_job_ad_remote_type_range CHECK ("column" > 0 AND "column" < 5)
);
```

**Error**

n/a

**Versions.**
 - OS: Ubuntu / Debian
 - Python: 3.9.10
 - Alembic: >1.6.0 (tested with 1.6.0, 1.6.5, 1.7.5)
 - SQLAlchemy: 1.4.31 (also tested with coming 1.4.33)
 - Database: postgresql
 - DBAPI: psycopg2

**Additional context**

Rewritting the constraint with a `text()` expression (_e.g._ `sa.text('"column" > 0 AND "column" < 5')` in the above example) works around the issue.

This does not seem to come from SQLAlchemy (or SQLAlchmey somehow works around this). Indeed the following code:
```python
from sqlalchemy.dialects.postgresql import dialect
from sqlalchemy.sql.ddl import CreateTable
from sqlalchemy import __version__

METADATA = MetaData()
T = Table(
    't',
    METADATA,
    Column('t_id', UUID, nullable=False),
    # Field to have a constraint applied to
    Column('column', Integer, nullable=True),
    PrimaryKeyConstraint('t_id'),
    comment='Bla bla bla',
    schema='issue',
)
"""Dimensions collection table to pull data from datapond (debezium)

"""
T.append_constraint(CheckConstraint(and_(T.c.column < 5, T.c.column > 0)))


print(f'-- SQLAlchemy {__version__}')
stmt = CreateTable(T)
str(dialect.ddl_compiler(dialect(), stmt))
```
As well as using the exact same construct as in the migration (column variable, used to build the constraint) yields the expected DDL statement:
```
-- 1.4.33

CREATE TABLE issue.t (
    t_id UUID NOT NULL, 
    "column" INTEGER, 
    PRIMARY KEY (t_id), 
    CHECK ("column" < 5 AND "column" > 0)
)
```

**Have a nice day!**
Thanks, have a nice day as well!

**Comment by cansjt** [comment]
The issue seems to be on [line 213, in `alembic/operations/schemaobj.py`](https://github.com/sqlalchemy/alembic/blob/2719c0ef1917af0b74b9d642a75c9b6dd5cf537a/alembic/operations/schemaobj.py#L213), adding the `column` Column does add the constraint to the table.

It is then copied and added again in the list comprehension on [l. 215](https://github.com/sqlalchemy/alembic/blob/2719c0ef1917af0b74b9d642a75c9b6dd5cf537a/alembic/operations/schemaobj.py#L215).

The following patch fixes the issue:
```diff
diff --git a/alembic/operations/schemaobj.py b/alembic/operations/schemaobj.py
index c8fab93..afba786 100644
--- a/alembic/operations/schemaobj.py
+++ b/alembic/operations/schemaobj.py
@@ -214,7 +214,7 @@ class SchemaObjects:
 
         constraints = [
             sqla_compat._copy(elem, target_table=t)
-            if getattr(elem, "parent", None) is not None
+            if getattr(elem, "parent", None) is not t and getattr(elem, "parent", None) is not None
             else elem
             for elem in columns
             if isinstance(elem, (Constraint, Index))
```

**Comment by zzzeek** [comment]
yeah looks like you have a PR coming.  can you write a test for it?

**Comment by zzzeek** [comment]
I think in tests/test_op.py should wok

**Comment by sqla-tester** [comment]
**Nicolas CANIART** has proposed a fix for this issue in the **main** branch:

**Fix duplicated constraints when using expressions** https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/3702
