### ISSUE TITLE
Have migration files on chronological order by default

### ISSUE THREAD

**Issue by eliasdorneles** [sqlalchemy/alembic#1011]
Hi folks! :wave: 

I've been using alembic for more than a year, and many times I've been frustrated (without fully realizing) because the migration files aren't sorted. Today I've realized that there is already a configuration for that, it's just not the default.

I bet I'm not the only person having this issue. :sweat_smile: 

Would you accept a pull request updating the default value for the `file_template` configuration to be like `%%(year)d_%%(month).2d_%%(day).2d_%%(hour).2d%%(minute).2d-%%(rev)s_%%(slug)s` ?

**Example:**

Running `alembic revision -m "Here is a new revision"` would yield a revision file named:

    2022_04_05_2155-c70b61b57ced_here_is_a_new_revision.py

Which is a quite nice naming scheme, friendly for `<tab>` completing and also quick eye-scanning the directory listings.

**Comment by CaselIT** [comment]
Hi,

I'm fine with it (I also tend to use it with a similar configuration), but I fear that it may lead people to thing that that's order of the migration, and that's not necessarily the case when developing with a branching style workflow.

What do you thing @zzzeek ?

**Comment by zzzeek** [comment]
I'm at the moment -1 on changing a default here.   we should likely document this better so that people won't miss it.

**Comment by eliasdorneles** [comment]
Well, I'd really prefer a better default, but I understand the reluctance in changing it.

In that case, I propose a commented-out example in the file template. Will open a PR for that.

**Comment by eliasdorneles** [comment]
I noticed that the code was merged, so I'll just close the issue.
Thank you!
