### ISSUE TITLE
@Operations.implementation_for typing issues

### ISSUE THREAD

**Issue by saulbein** [sqlalchemy/alembic#1015]
**Describe the bug**
Typing for custom operation implementation complains when using other operations for the implementation. For example from the cookbook:
```py
@Operations.implementation_for(CreateViewOp)
def create_view(operations, operation):
    operations.execute("CREATE VIEW %s AS %s" % (
        operation.target.name,
        operation.target.sqltext
    ))
```
mypy outputs this error:
`error: "Operations" has no attribute "execute"`

**Expected behavior**
No mypy errors when following the cookbook.

**To Reproduce**
```py
from alembic.operations import Operations, MigrateOperation

@Operations.register_operation("custom_op")
class CustomOp(MigrateOperation):
    def __init__(self) -> None:
        pass

@Operations.implementation_for(CustomOp)
def custom_op(operations: Operations, operation: CustomOp) -> None:
    operations.execute("SELECT 1") # "Operations" has no attribute "execute" 
```

**Versions.**
 - OS: Linux (Manjaro 21.2.5)
 - Python: 3.8.12
 - Alembic: 1.7.7
 - SQLAlchemy: 1.3.24
 - Database: Any
 - DBAPI: Any

**Additional context**
I'm not sure if this is possible to fix, since custom implementations may rely on other custom implementations, so it is impossible to know what methods will be available to `Operations` in runtime, but it would be nice if it at least wouldn't complain about the built-in ones.

**Have a nice day!**

**Comment by zzzeek** [comment]
@CaselIT we would need to expand on https://github.com/sqlalchemy/alembic/blob/main/tools/write_pyi.py to also add the Operations class

**Comment by CaselIT** [comment]
This was actually fixed at some point
