### ISSUE TITLE
Breaking behavior of `history -r ARG` when using relative command

### ISSUE THREAD

**Issue by eliasdorneles** [sqlalchemy/alembic#1020]
**Describe the bug**

When I run `alembic history -r -1:head` (note the space after `-r`), then I get an error `alembic history: error: argument -r/--rev-range: expected one argument`

**Expected behavior**

I'd expect it to show me the list of two latest migrations, just the same as `alembic history -r-1:head` (note, this time no spaces between `-r`  and the argument).

Just as documented in the output of `alembic history --help` :

![image](https://user-images.githubusercontent.com/37565/164001375-04071a21-ae00-4142-baec-3d56ed6ec6e7.png)

**To Reproduce**

Just run `alembic history -r -1:head` on a working project with a few migration files.

**Error**

```
alembic history: error: argument -r/--rev-range: expected one argument
```

**Versions.**
 - OS: Ubuntu
 - Python: 3.8.10
 - Alembic: 1.7.6
 - SQLAlchemy: 1.3.24

**Additional context**

 It breaks similarly if I do `alembic history --rev-range -1:head`, but it works if I do  `alembic history --rev-range=-1:head`, which is also not as documented.

**Have a nice day!**

**Comment by zzzeek** [comment]
this is a [known issue in argparse](https://github.com/python/cpython/issues/53580), apparently.   we can document the "=" workaround that appears to be the only way to make it work but there's no bug that can be fixed in alembic here short of not using argparse.

**Comment by zzzeek** [comment]
documented

**Comment by eliasdorneles** [comment]
Thank you! :sparkles:
