### ISSUE TITLE
Drop python 3.6

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/alembic#1025]
I think we need to remove support for python 3.6, since the current main uses `from __future__ import annotation` that raises `SyntaxError: future feature annotations is not defined` on py 3.6

@zzzeek this probably requires 1.8?

**Comment by zzzeek** [comment]
yes let's do a bump, since have a lot of installation types of things in the queue

**Comment by sqla-tester** [comment]
**CaselIT** has proposed a fix for this issue in the **main** branch:

**Alembic 1.7 now supports Python 3.6 and above** https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/3819
