### ISSUE TITLE
Add epoch as an option for the file_template

### ISSUE THREAD

**Issue by lowercase00** [sqlalchemy/alembic#1027]
This is just a small detail, but would be great to have epoch as an alternative for the file_template, I'll be opening a PR with this change.

**Comment by sqla-tester** [comment]
**Caio Carvalho** has proposed a fix for this issue in the **main** branch:

**Add epoch as an option for file_template** https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/3823
