### ISSUE TITLE
Autogenerate does not sees collation field changes

### ISSUE THREAD

**Issue by jekel** [sqlalchemy/alembic#1041]
I have found the same problem as described in #475 , 
when you change for example String field with adding collation parameter to it - alembic does not see this change on autogenerate

**Versions.**
 - OS:  MS Windows 10
 - Python: 3.9.10
 - Database: PostgreSQL 12
 - alembic 1.7.7
 - SQLAlchemy 1.4.35

**Comment by zzzeek** [comment]
hi -

please reopen #475 with clear reproducing examples.  modify my model at https://github.com/sqlalchemy/alembic/issues/475#issuecomment-441887543 to show a model that fails.

**Comment by faizanalhassan** [comment]
Hi @zzzeek , any updates on this issue?

**Comment by Cheaterman** [comment]
Interesting that two persons are inquiring about this two year old issue within a month, but yeah, that would be neat :-D
