### ISSUE TITLE
Cookbook recipe for "Don’t emit CREATE TABLE statements for Views" does not have instructions for declarative tables

### ISSUE THREAD

**Issue by jack-michaud** [sqlalchemy/alembic#1050]
**Describe the bug**
The instructions for [Don’t emit CREATE TABLE statements for Views](https://alembic.sqlalchemy.org/en/latest/cookbook.html#don-t-emit-create-table-statements-for-views) does not describe a method for providing an `info` object on a declarative table.
**Expected behavior**
I'd expect the example to include instructions for including an `info` object on a declarative table. e.g. https://github.com/olirice/alembic_utils/issues/92#issuecomment-1141453005

**Comment by CaselIT** [comment]
Hi,

We could indeed include it. Could you open a PR with the change?
