### ISSUE TITLE
Iceberg Support

### ISSUE THREAD

**Issue by dpedowitz** [sqlalchemy/alembic#1056]
**Describe the use case**

Iceberg is becoming a popular choice for big data and supports schema evolution.  Alembic support for Iceberg would benefit the community greatly by providing a programatic schema evolution library that many developers are already familiar with.

**Databases / Backends / Drivers targeted**

Iceberg (https://iceberg.apache.org/) spark (https://iceberg.apache.org/docs/latest/spark-ddl/)

**Example Use**

https://iceberg.apache.org/docs/latest/evolution/

```
CREATE TABLE prod.db.sample (
    id bigint,
    data string,
    category string)
USING iceberg
PARTITIONED BY (category)
```

```
ALTER TABLE prod.db.sample RENAME TO prod.db.new_name
```

```
ALTER TABLE prod.db.sample
ADD COLUMNS (
    new_column string comment 'new_column docs'
  )
```

**Thank you for consider this!**

**Comment by gordthompson** [comment]
Does Iceberg have a third-party dialect for SQLAlchemy? That would be a pre-requisite.

**Comment by zzzeek** [comment]
we can't add Iceberg support to Alembic as there is no dialect for it and such a dialect would be third party.  Many of the dialects listed at https://docs.sqlalchemy.org/en/14/dialects/index.html#external-dialects include Alembic features, so a future Iceberg dialect would also add Alembic support.
