### ISSUE TITLE
[mypy] error: Argument 1 to "execute" has incompatible type "Delete"; expected "Union[str, TextClause, Update]"

### ISSUE THREAD

**Issue by arjenzorgdoc** [sqlalchemy/alembic#1058]
**Describe the bug**
mypy doesn't allow Delete() as parameter to op.execute().

**Expected behavior**
no mypy error?

**To Reproduce**

```py
from alembic import op
from sqlalchemy import table            
op.execute(table("test").delete())
```

**Error**

```
test.py:3: error: Argument 1 to "execute" has incompatible type "Delete"; expected "Union[str, TextClause, Update]"
```

**Versions.**
 - OS: linux
 - Python: 3.8
 - Alembic: 1.8.0
 - SQLAlchemy: 1.3.18
 - Database: n/a
 - DBAPI: n/a

**Have a nice day!**
Thanks!

**Comment by arjenzorgdoc** [comment]
Maybe in `ddl/impl.py`:

```patch
     def execute(
         self,
-        sql: Union["Update", "TextClause", str],
+        sql: Union["UpdateBase", "TextClause", str],
         execution_options: None = None,
     ) -> None:
         self._exec(sql, execution_options)
```

**Comment by zzzeek** [comment]
agree, "Update" seems kind of arbitrary.  I would think Executable is the safer choice


cc @CaselIT

**Comment by CaselIT** [comment]
That type probably was the one auto-generated from the tests. We can do `executable|str`

**Comment by CaselIT** [comment]
This is actually the same as https://github.com/sqlalchemy/alembic/issues/1277

**Comment by sqla-tester** [comment]
**Mihail Milushev** has proposed a fix for this issue in the **main** branch:

**Improve typing of `op.execute`** https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/4835
