### ISSUE TITLE
Migration generated always set enum nullable to true

### ISSUE THREAD

**Issue by yixiongngvsys** [sqlalchemy/alembic#1090]
**Describe the bug**
I have a field with enum type and I want to set nullable to False, however, the migration generated is always set nullable to True

**Expected behavior**
If the field contains nullable = False, migration generated should set nullable = False

**To Reproduce**

```py
import enum
from sqlmodel import SQLModel, Field, UniqueConstraint, Column, Enum

class Contract_Status(str, enum.Enum):
    CREATED = "Created"
    COMPLETED = "Completed"
    DEPOSITED = "Deposited"
    CANCELLED = "Cancelled"

class Contract(SQLModel, table = True):
    __table_args__ = (UniqueConstraint("ctrt_id"),)
    ctrt_id: str = Field(primary_key = True, nullable = False)
    status: Contract_Status = Field(sa_column = Column(Enum(Contract_Status, values_callable = lambda enum: [e.value for e in enum])), nullable = False)

```

**Error**

```
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contract',
    sa.Column('status', sa.Enum('Created', 'Completed', 'Deposited', 'Cancelled', name='contract_status'), nullable=True),
    sa.Column('ctrt_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('ctrt_id'),
    sa.UniqueConstraint('ctrt_id')
    )
    # ### end Alembic commands ###

```

**Versions.**
 - OS: MacOS Monterey 12.6 (Intel Processor)
 - Python: 3.10.5
 - Alembic: 1.8.1
 - SQLAlchemy: 1.4.40
 - Database: MySQL 8.0.29
 - SQLModel: 0.0.8

**Comment by CaselIT** [comment]
Hi,

Can you reproduce the same issue using a sqlalchemy definition?

**Comment by yixiongngvsys** [comment]
> Hi,
> 
> Can you reproduce the same issue using a sqlalchemy definition?

Hi, I am not sure how to reproduce using sqlalchemy definition since all my classes are using SQLModel. Do you mind show me some examples?

**Comment by CaselIT** [comment]
This is the quick start https://docs.sqlalchemy.org/en/14/orm/quickstart.html

In any case this seems an issue with sqlmodel, since sqlalchemy will not flip nullable if it's set.
