### ISSUE TITLE
Cannot upgrade branch with dependency

### ISSUE THREAD

**Issue by asodeur** [sqlalchemy/alembic#1107]
**Describe the bug**
When a branch has a dependency on another branch it seems to be impossible to upgrade any further.
```
Branch A: ----- A1
               /
Branch B: -- B1
```
Any attempt to upgrade (even to A1/B1) gives an error: `FAILED: Requested revision A1 overlaps with other requested revisions B1`. The issue is not caused by the target revision but by the current state when the current node set is calculated here: https://github.com/sqlalchemy/alembic/blob/1684d0ee89c0fc6b0b90bc5db614468b31119e9d/alembic/script/revision.py#L1481-L1485
Not sure about the true root cause but `check=True` might not be necessary for the current node set? (`check=True` does not like the target state (A1, B1) but would allow upgrade to A1 or B1 individually regardless of order which is a little strict IMHO as well.)

**Versions.**
 - OS: Windows
 - Python: 3.9
 - Alembic: 1.8.1
 - SQLAlchemy: 1.4.15
 - Database: Sql Server
 - DBAPI: pyodbc

**Comment by CaselIT** [comment]
Hi,

I think additional information is required here. Can you provide an example of migrations that's causing the issue?

**Comment by asodeur** [comment]
Hi,
is there some standard example or template project I could adapt as a reproducer? Setting-up a reproducer from scratch with two branches will be quite some work. Maybe, another strategy would be building the `RevisionMap` from the outputs of `alembic history` as in  `test_revison.py`?

**Comment by CaselIT** [comment]
I don't think there is a standard template. 
For a start I think you could provide the revision information (listed below) of the migrations that cause the problem, to understand the use case (so the base for the branch plus any other migration that's involved)
```
revision 
down_revision
branch_labels 
depends_on 
```

**Comment by zzzeek** [comment]
building a test_revision.py case is probably workable, if there's a bug, that's where we'd need to fix it

**Comment by asodeur** [comment]
Your right, the behavior I am seeing is not an issue on its own but a consequence of the `alembic_version` table being corrupted (most likely not at `alembic`s fault). The 'special' thing about the case was we used multiple bases for the A/B branches but somehow A1 and B1 ended-up in `alembic_version` even though B1 is only an effective head. After removing the effective head (B1) from the table everything works as expected.

Would it make sense to add a sanity check that flags effective heads in `alembic_version` ? I am inclined to believe we corrupted the table by our own fault but debugging this would have been easier with a pointer in this direction ...

**Comment by zzzeek** [comment]
> Would it make sense to add a sanity check that flags effective heads in `alembic_version` ? I am inclined to believe we corrupted the table by our own fault but debugging this would have been easier with a pointer in this direction ...

yes, because if something is corrupting version tables that seems concerning, were you manipulating the table directly?

**Comment by asodeur** [comment]
No not directly. But I got a hunch the `depends_on` might have been added only after someone already ran the upgrade. Changing the migration scripts after the fact probably gives the same if not more opportunities to mess-up than manipulating the table directly ;-).
