### ISSUE TITLE
revision function's type annotation is partial.

### ISSUE THREAD

**Issue by mmohaveri** [sqlalchemy/alembic#1110]
**Describe the bug**

Revision function's type annotation causes "Type is partially unknown" error. The root of the issue is that `process_revision_directives`'s argument has been typed with `Callable` which is a partial type (as it lacks definition of the signature of the function).

**Expected behavior**
I expect the type of the `process_revision_directives` to be fully defined so type checkers like Pyright won't give me an error.

**To Reproduce**
Just write any code that imports `revision` and run pyright on it.

**Comment by zzzeek** [comment]
hey there -

here's a script, I can't get it to reproduce a problem, does this cause a problem on your end?

```py
from alembic.script import revision

map_ = revision.RevisionMap(
    lambda: [
        revision.Revision("a", ()),
        revision.Revision("b", ("a",)),
        revision.Revision("c", ("b",)),
    ]
)


```

**Comment by zzzeek** [comment]
oh. you mean "from alembic.command import revision".

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**add typing parameters** https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/4179
