### ISSUE TITLE
overload stubs missing for get_x_argument

### ISSUE THREAD

**Issue by vfazio** [sqlalchemy/alembic#1146]
**Describe the bug**

The `context.pyi` does not have stubs for the function overloads specified in `environment.py`
```python
    @overload
    def get_x_argument(  # type:ignore[misc]
        self, as_dictionary: Literal[False] = ...
    ) -> List[str]:
        ...

    @overload
    def get_x_argument(  # type:ignore[misc]
        self, as_dictionary: Literal[True] = ...
    ) -> Dict[str, str]:
        ...

    def get_x_argument(
        self, as_dictionary: bool = False
    ) -> Union[List[str], Dict[str, str]]:
```

This will cause typing errors if trying to use:
```python
cmd_line_path = context.get_x_argument(as_dictionary=True).get("dbpath", None)
```
```
migrations/env.py:71:21: error: Item "List[str]" of "Union[List[str], Dict[str, str]]" has no attribute "get"  [union-attr]
```

Since the default typing for the function allows it to return `List[str]` even though specifying `as_dictionary` should narrow the return type.

**Expected behavior**

There should be no typing error once `@overload` stubs are added

**To Reproduce**
Please try to provide a [Minimal, Complete, and Verifiable](http://stackoverflow.com/help/mcve) example, with the migration script and/or the SQLAlchemy tables or models involved.
See also [Reporting Bugs](https://www.sqlalchemy.org/participate.html#bugs) on the website.

```py
# Insert code here
```

**Error**

```
# Copy error here. Please include the full stack trace.
```

**Versions.**
 - OS: 
 - Python:
 - Alembic:
 - SQLAlchemy:
 - Database:
 - DBAPI:

**Additional context**

**Have a nice day!**

**Comment by CaselIT** [comment]
Thanks for reporting
