### ISSUE TITLE
Stub generator for proxy classes does not generate overload stubs

### ISSUE THREAD

**Issue by vfazio** [sqlalchemy/alembic#1147]
**Describe the bug**

The stub generator for proxy classes (`tools/write_pyi.py`) does not generate overload stubs

**Expected behavior**

To accurately reflect the typing of the proxied classes, the overloads should be stubbed out.

**Comment by CaselIT** [comment]
Hi,

this seems a duplicate of https://github.com/sqlalchemy/alembic/issues/1146. We can continue to the other one
