### ISSUE TITLE
Autogenerate ignores order of columns in an index

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/alembic#1166]
For the autogenrated the following indexes where considered equal, while in general they aren't
```py
Index('my_index', 'a', 'b')
Index('my_idnex', 'b', 'a')
```

**Comment by sqla-tester** [comment]
**CaselIT** has proposed a fix for this issue in the **main** branch:

**Improved support for expression indexes** https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/4426
