### ISSUE TITLE
create_index documentation and typing should allow a None name

### ISSUE THREAD

**Issue by simark** [sqlalchemy/alembic#1168]
According to:

https://github.com/sqlalchemy/alembic/blob/4fb3681f8167d8501ff8a348fd6e9caa6491122f/tests/test_op_naming_convention.py#L46

... it is valid to pass None as the name to the create_index operation.  However, the documentation and typing do not reflect it:

https://github.com/sqlalchemy/alembic/blob/4fb3681f8167d8501ff8a348fd6e9caa6491122f/alembic/op.pyi#L579

**Comment by CaselIT** [comment]
Hi,

Thanks for reporting.

**Comment by sqla-tester** [comment]
**CaselIT** has proposed a fix for this issue in the **main** branch:

**Improve typing to accomodate sqlalchemy v2** https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/4440
