### ISSUE TITLE
type error in env.py from documentation

### ISSUE THREAD

**Issue by Dreamsorcerer** [sqlalchemy/alembic#1174]
When using the examples in the documentation for env.py, there is a type error:

```
alembic/env.py:53:13: error: Argument 1 to "engine_from_config" has
incompatible type "Optional[Dict[str, str]]"; expected "Dict[str, Any]" 
[arg-type]
                config.get_section(config.config_ini_section),
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Seems that there should be a check for `None` in these examples, or `engine_from_config()` should accept a `None` value.

**Comment by sqla-tester** [comment]
**Sam Bull** has proposed a fix for this issue in the **main** branch:

**Include missing part of env.py** https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/4443
