### ISSUE TITLE
remove quoting in compare server default

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/alembic#1178]
will be updated by #1177, but the logic we want to remove is:

https://github.com/sqlalchemy/alembic/blob/a79ba7d74d12e0be63e1afb05e037d0a052b5086/alembic/autogenerate/compare.py#L1023-L1025

that logic should be within dialects only on an as-needed basis.

we can't remove it on a point release since the converted string is passed to user defined server default comparison

**Comment by zzzeek** [comment]
welp we missed it.  will try for 1.11

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **main** branch:

**Removed server default quoting from compare** https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/4608
