### ISSUE TITLE
Pyright warnings in strict mode: type is partially unknown for op.create_index

### ISSUE THREAD

**Issue by AlexanderPodorov** [sqlalchemy/alembic#1191]
Example of op.create_index:
`op.create_index(op.f('ix_token_expired_at'), 'token', ['expired_at'], unique=False)`
warning: Type of "create_index" is partially unknown
reason (most likely): `columns` parameter has type `Sequence[str | TextClause | Function[Unknown]]`. `Function` generic is missing type parameter.

**Expected behavior**
No warnings produced

**Versions.**
 - OS: MacOS
 - Python: 3.11.2
 - Alembic: 1.9.4
 - SQLAlchemy: 2.0.4
 - Database: Postgres 15
 - DBAPI: asyncpg

**Additional context**
See: https://github.com/sqlalchemy/sqlalchemy/issues/9391

Thanks!

**Comment by CaselIT** [comment]
Hi,

Thanks for re-reporting. Sorry for moving the previous issue

**Comment by AlexanderPodorov** [comment]
Hi, no worries, let me know if you need anything.

**Comment by sqla-tester** [comment]
**CaselIT** has proposed a fix for this issue in the **main** branch:

**Correctly account for generic in Function** https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/4492

**Comment by zzzeek** [comment]
funny that mypy doesnt complain

**Comment by CaselIT** [comment]
Mypy is a bit leaking in some regards.

Is seels it also doesn't know that enume are iterable :/ (not related to this change)
