### ISSUE TITLE
Pyright in "strict" mode complains about "begin_transaction"

### ISSUE THREAD

**Issue by AlexanderPodorov** [sqlalchemy/alembic#1201]
When `env.py` is generated, this line is usually added:
```python
from alembic.context import begin_transaction
```
VSCode (pylance/pyright) compains about it saying:
`Type of "begin_transaction" is partially unknown`
Most likely because of:
```python
def begin_transaction() -> Union[_ProxyTransaction, ContextManager]:
```
where the type of `ContextManager` generic is not specified

**Expected behavior**
No warnings

**Versions.**
 - OS: MacOS
 - Python: 3.11.2
 - Alembic: 1.10.1
 - SQLAlchemy: 2.0.5.post1
 - Database: Postgres 15
 - DBAPI: asyncpg

**Have a nice day!**

**Comment by zzzeek** [comment]
thanks for reporting

cc @CaselIT

**Comment by CaselIT** [comment]
Thanks for reporting.

**Comment by CaselIT** [comment]
Please note that both alembic and sqlalchemy are currently "best effort" type checking with pyright/pylance. A lot of similar issues will came up running them, especially in strict mode

**Comment by sqla-tester** [comment]
**CaselIT** has proposed a fix for this issue in the **main** branch:

**Correctly account for generic in Function** https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/4492

**Comment by AlexanderPodorov** [comment]
Thanks for the note, that's fine. sqlalchemy and alembic are doing the great job of implementing proper type hinting!
I personally have not seen a lot of typing issues yet. Refining existing type hints is also great.
I would mention this particular issue is not related to pyright/pylance, mypy in strict mode will likely show a warning either (however I did not test that). I believe the respective setting for that is `--disallow-any-generics`. Thanks!

**Comment by CaselIT** [comment]
BTW I did not want to discourage future issues on this, just stating the current status of alembic and sqlalchemy
