### ISSUE TITLE
A way to run non-transactional DDL commands / PG requires autocommit to modify a type ?!

### ISSUE THREAD

**Issue by sqlalchemy-bot** [sqlalchemy/alembic#123]
**Migrated issue, originally created by Wichert Akkerman ([@wichert](https://github.com/wichert))**

Unfortunately not all DDL commands for PostgreSQL can be used in a transaction. I ran into this when trying to add a new value to an enum:

```
db=# BEGIN;
BEGIN
db=# ALTER TYPE article_type ADD VALUE 'unknown';
ERROR:  ALTER TYPE ... ADD cannot run inside a transaction block
```

I'm not sure what the best way to handle this is in alembic currently. Perhaps do ``op.execute('COMMIT')`` manually? Perhaps alembic needs an in-between-commit operation for this.

**Comment by zzzeek** [comment]
if I hope to implement migration operations for ENUM including autogenerate support, if PG won't even let us add elements to an enum without cancelling the transaction, that's going to be *really* painful

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Add autocommit_block** https://gerrit.sqlalchemy.org/1463
