### ISSUE TITLE
Add op.run_async to allow running async function from upgrade/downgrade when using an async engine

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/alembic#1231]
The function that's called should probably receive an async connection as the fist argument

Mentioned in #1229

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **main** branch:

**Added ``op.run_async``.** https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/4594
