### ISSUE TITLE
Don't use `type(None)` as fallback for Computed or Identity

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/alembic#1237]
In old version of sqlalchemy, that don't have Computed or Identity a fallback in alembic is used.
The current fallback is to set these values to `type(None)`

This causes issues since checks like `isinstance(something, Computed)` will pass when something is `None`, leading to attribute errors.

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **main** branch:

**Fix compat issue with older SQLAlchemy versions.** https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/4601

**Comment by zzzeek** [comment]
looks like we added "Computed" in 1.3.11
