### ISSUE TITLE
Multiple versions directories

### ISSUE THREAD

**Issue by sqlalchemy-bot** [sqlalchemy/alembic#124]
**Migrated issue, originally created by Wichert Akkerman ([@wichert](https://github.com/wichert))**

I have a collection of packages, each of which import one or more models that may be used in an application. Each package can require its own migrations, but will may depend on migrations from other packages it depends on as well. I am looking at what it would take to use alembic in this type of environment. I see two basic approaches: manually importing versions, or allowing versions in multiple places.

### Manual importing of versions ###

One option is to turn the versions directory into a package and import the downgrade and upgrade functions defined there in a version definition of another package. This does not require any changes in alembic

```
from other.package.versions.v3_0 import downgrade as downgrade_other
from other.package.versions.v3_0 import upgrade as upgrade_other

def upgrade():
    upgrade_other()
    # Upgrade logic for this package

def downgrade():
    downgrade_other()
    # Downgrade logic for this package
```

This works, but quickly becomes problematic as soon as the dependencies are not completely trivial.

### Versions in multiple places ###

Alembic has an undocumented option allowing you use a dotted path as version location. It should be easy to extend this to allow multiple version directories.

```
[alembic]
script_location =
    other.package:upgrade
    other.package2:upgrade
    my_package:upgrade
```

You can then treat each package as a branch to make sure all migration dependencies are handled correctly.

If you think this approach is workable I can probably whip up a pull request for it.

**Comment by praveensnsct** [comment]
> > **Michael Bayer ([@zzzeek](https://github.com/zzzeek)) wrote:**
> > i use multiple sets of versions by just putting multiple sections in my .ini file and referring to them using the "--name" option:
> > ```
> > -n NAME, --name NAME  Name of section in .ini file to use for Alembic config
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > so that is:
> > ```
> > [alembic_app1]
> > script_location = foo
> > 
> > [alembic_app2]
> > script_location = bar
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > but these are separate series of migration scripts. I can't tell in your use case how the versions across these different packages intend to be organized into a line, or if they all run as separate series of migrations.
> 
> This is kinda old, but i would like to add my two cents in case someone comes here looking for help. The config additions worked well for me, but I also had to add two more vars for the migrations to work:
> 
> ```
> [alembic_app1]
> script_location = foo
> version_locations = %(here)s/alembic/foo/versions
> prepend_sys_path = .
> ```

You are my life saver
