### ISSUE TITLE
Enable compareType by default

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/alembic#1248]
Change the compareType default from False to True

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **main** branch:

**Enable compare type by default** https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/4822

**Comment by zzzeek** [comment]
what's the background on this? I know the general idea is that at some point we redid type comparison to be a lot better.   but are people looking for this?  Why open ourselves up to a bunch of new issues that might be very difficult to solve?

**Comment by CaselIT** [comment]
iirc we talked a bit about this on an dev meeting.

shall we introduce a "warn" flag that's the new default, that's basically like true but only long that there are type changes, without then writing them to the migration?

**Comment by zzzeek** [comment]
nah, let's make the change.  we already broke the type comparison hook silently.  let's just document all this pretty prominently

**Comment by CaselIT** [comment]
ok, I'll expand the documentation a bit.
