### ISSUE TITLE
Autogenerate migration has minor typing issues with mypy

### ISSUE THREAD

**Issue by igorbga** [sqlalchemy/alembic#1253]
Using SqlAlchemy 2.X and Alembic 1.11.1.

_mypy_ is complaining about _down_revision_, _branch_labels_, and _depends_on_ needing explicit type annotation.

I guess that for _down_revision_ this is only an issue for the first migration because after that it will always be initialized and detected as _str_.

The fix seems trivial, but I'm not an Alembic expert at all so I might be missing something:

```python
down_revision: Optional[str] = None
branch_labels: Optional[str] = None
depends_on: Optional[str] = None
```

Maybe this is intended and neccesary in order to keep backwards compatibility with Python 2.x ?

**Comment by CaselIT** [comment]
Hi,

thanks for reporting.
This can be fixed in the alembic templates, but existing install will need to edit the `script.py.mako` file

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **main** branch:

**Added typing to the default script mako templates.** https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/4635
