### ISSUE TITLE
Badly formatted output when running post-write hooks

### ISSUE THREAD

**Issue by duc00** [sqlalchemy/alembic#1261]
**Describe the bug**
There is a small output bug when running `alembic revision ...` with a post-write hook. The name of the hook is not correctly displayed:

```bash
$ alembic revision -m 'my new revision'        
  Generating myrepo/migrations/versions/202306151538_my_new_revision.py_ ...  done
  Running post write hook {name!r} ... # Display bug HERE
reformatted myrepo/migrations/versions/202306151538_my_new_revision.py

All done! ✨ 🍰 ✨
1 file reformatted.
  done
```

Happy to fix, if approved!

**Expected behavior**
This output
```bash
$ alembic revision -m 'my new revision'        
  Generating myrepo/migrations/versions/202306151538_my_new_revision.py_ ...  done
  Running post write hook black ... # Display bug HERE
reformatted myrepo/migrations/versions/202306151538_my_new_revision.py

All done! ✨ 🍰 ✨
1 file reformatted.
  done
```
when `black` hook is configured.

**To Reproduce**
```bash
$ mkdir testdir
$ cd testdir
$ python3 -m venv venv
$ source venv/bin/activate
$ pip install alembic
```

Uncomment default `post_write_hooks` parameters in `alembic.ini`
```ini
[post_write_hooks]
black.type = console_scripts
black.entrypoint = black
black.options = -l 79 REVISION_SCRIPT_FILENAME
```

Then run revision command
```bash
alembic revision -m 'my new revision'
```

**Error**

```bash
# Command output
  Generating workspace/testdir/migrations/versions/324b3e655f54_my_new_revision.py ...  done
  Running post write hook {name!r} ...
...
```

**Versions.**
 - OS: macOS
 - Python: 3.11
 - Alembic: 1.11.1
 - SQLAlchemy: 2.0.16
 - Database: PostgreSQL 15.3
 - DBAPI: N/A

**Additional context**
Bug seems to be here: https://github.com/sqlalchemy/alembic/blob/79738c9e971d4bbe6f4845a54fd0f972d15e1035/alembic/script/write_hooks.py#L88

**Have a nice day!**

**Comment by CaselIT** [comment]
Hi,

duh. thanks for noticing. strange that no linted said anything about it.
Care to create a PR for it?

**Comment by duc00** [comment]
Sure!

**Comment by sqla-tester** [comment]
**Mathieu Défosse** has proposed a fix for this issue in the **main** branch:

**Fixed CLI output when running post_write hooks** https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/4731
