### ISSUE TITLE
Alembic 10.1.4+ re-creates index with DESC defined via `postgresql_ops` without changes

### ISSUE THREAD

**Issue by mtvx** [sqlalchemy/alembic#1285]
**Describe the bug**

Code declares an index as:

```py
    __table_args__ = (
        Index(
            "ix_client_config_change_user_uid_created_at",
            "user_uid",
            "created_at",
            postgresql_ops={"created_at": "DESC"},
        ),
    )
```

Migration generated with `alembic < 1.10.4` is as:

```py

op.create_index('ix_client_config_change_user_uid_created_at', 'client_config_change',
                ['user_uid', 'created_at'],
                unique=False, postgresql_ops={'created_at': 'DESC'})
```

It shows in DB as:

```
    "ix_client_config_change_user_uid_created_at" btree (user_uid, created_at DESC)
```

`alembic check` on `1.10.4` fails to:

```
2023-07-31 11:27:11.945 ERROR [alembic.util.messaging] New upgrade operations detected: [('remove_index', Index('ix_client_config_change_user_uid_created_at', Column('user_uid', UUID(), table=<client_config_change>), <sqlalchemy.sql.elements.UnaryExpression object at 0x7fbdcb7aca00>)), ('add_index', Index('ix_client_config_change_user_uid_created_at', Column('user_uid', UUID(as_uuid=True), table=<client_config_change>), Column('created_at', DateTime(), table=<client_config_change>, nullable=False, default=ColumnDefault(<sqlalchemy.sql.functions.now at 0x7fbdd1f81780; now>))))]
  FAILED: New upgrade operations detected: [('remove_index', Index('ix_client_config_change_user_uid_created_at', Column('user_uid', UUID(), table=<client_config_change>), <sqlalchemy.sql.elements.UnaryExpression object at
  0x7fbdcb7aca00>)), ('add_index', Index('ix_client_config_change_user_uid_created_at', Column('user_uid', UUID(as_uuid=True), table=<client_config_change>), Column('created_at', DateTime(), table=<client_config_change>, nullable=False,
  default=ColumnDefault(<sqlalchemy.sql.functions.now at 0x7fbdd1f81780; now>))))]
```

`alembic revision --autogenerate` wants to re-generate it as identical:

```py
    op.drop_index('ix_client_config_change_user_uid_created_at', table_name='client_config_change')
    op.create_index('ix_client_config_change_user_uid_created_at', 'client_config_change', ['user_uid', 'created_at'], unique=False, postgresql_ops={'created_at': 'DESC'})
```

Reproduces on 1.11.x branch, too.

A workaround is to declare the index using `desc()` rather than `postgresql_ops`:

```py
    __table_args__ = (
        Index(
            "ix_client_config_change_user_uid_created_at",
            "user_uid",
            desc("created_at"),
        ),
    )
```

With this, no migration is generated (as should).

**Expected behavior**

There shouldn't be migration.

**To Reproduce**

I believe the above description is sufficient. `postgresql_ops` is probably the culprit?

Most likely caused by https://github.com/sqlalchemy/alembic/issues/1213?

Happy to give a reproducible script if one's needed.

**Error**

**Versions.**
 - OS: Linux
 - Python: 3.10.6
 - Alembic: 1.8.1
 - SQLAlchemy: 1.4.42
 - Database: Postgres
 - DBAPI: ?

**Comment by CaselIT** [comment]
Hi,

Thanks for reporting.
I believe there are no test for declaring desc using postgresql_ops. Maybe there should be some. I'll take a look at what's the original purpose of the ops dict.

For now use the alternative form

**Comment by mtvx** [comment]
@CaselIT Thanks for looking into it. Fair enough, so the original behavior was a bit mistaken.

In a way, it's a regression, though? What used to just work now re-generates the index. I bet someone else is going to bump into the same (hopefully they'll find this ticket).

Maybe mark it as a _breaking_ change in the changelog?

**Comment by CaselIT** [comment]
Well it's a new behaviour of alembic. I guess it depends on how you consider it, could be considered a breaking change or not, since there was noting before to break

The original plan was to release it as a 1.11, but it got released as 1.10.4
I guess the changelog can be improved a bit though. Feel free to send a PR to improve it

**Comment by CaselIT** [comment]
> I guess the changelog can be improved a bit though

clarified in 07aae1d88fecb267fdc623d02005dadbbd39948a

**Comment by mtvx** [comment]
Thank you, awesome 🥳
