### ISSUE TITLE
PR #619 completely removed support for `compare_against_backend`, but it's still documented

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/alembic#1293]
The PR #619 has completely removed support for `compare_against_backend`, but it's still documented and supposedly tested (the test is clearly broken.)

@zzzeek This seems to be a rarely used feature, since no-one reported it, but since it's still documented and all it may be better to just re-introduce it. If you feel like it make more sense removing it, then this issue could be used to remove the docs for it

_Originally posted by @CaselIT in https://github.com/sqlalchemy/alembic/issues/619#issuecomment-1675384015_

**Comment by zzzeek** [comment]
we never fixed this; removing from the docs now

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**remove compare_against_backend from tests and docs** https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/4925
