### ISSUE TITLE
`alembic merge` ignores `revision_environment` and cannot find the hooks defined in `env.py`

### ISSUE THREAD

**Issue by FeeeeK** [sqlalchemy/alembic#1299]
**Describe the bug**
As title says, `alembic merge` ignores `revision_environment` and cannot find the hooks defined in `env.py`.

**Expected behavior**
Custom hooks work the way they do when generating revisions

**To Reproduce**

```ini
# alembic.ini
revision_environment = true
hooks = ruff
ruff.type = ruff
ruff.options = --select I --select F401 --fix
```
```py
# env.py
from alembic.script import write_hooks

@write_hooks.register("ruff")
def run_ruff(filename, options):
    ruff = os.path.join(sysconfig.get_path("scripts"), "ruff")
    os.system(f"{ruff} {options['options']} {filename}")  # noqa: S605
```

**Error**

```
Running post write hook 'ruff' ...
  FAILED
FAILED: No formatter with name 'ruff' registered.
```

**Versions.**
 - Python: 3.11.1
 - Alembic: 1.11.3

**Additional context**
For the ruff example, this may become useless after #1276, but it is still needed for the rest of the custom hooks .

**Have a nice day!**
Thanks, you too!

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**implement revision_environment for merge** https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/4817

**Comment by zzzeek** [comment]
thanks for reporting
