### ISSUE TITLE
ForeignKeyConstraint argument `match` is not rendered in autogeneration

### ISSUE THREAD

**Issue by asibkamalsada** [sqlalchemy/alembic#1302]
When specifying `ForeignKeyConstraint(..., match="FULL")` I noticed that the autogeneration does not pick up the keyword argument `match`.

I already checked, the constraint is interpreted correctly and only during rendering in:
https://github.com/sqlalchemy/alembic/blob/dbdec2661b8a01132ea3f7a027f85fed2eaf5e54/alembic/autogenerate/render.py#L983C25-L983C25
the argument is just silently dropped, which totally confuses me.

Am I not seeing the reason for that? I need many `ForeignKeyConstraints` to have full matching, this is troublesome doing by hand.

**Comment by asibkamalsada** [comment]
@zzzeek I have opened a pull request and noticed that not only the `CreateForeignKeyOp` was rendered incorrectly but also the `ForeignKeyConstraint` and fixed both as they are very closely related.

**Comment by sqla-tester** [comment]
**Asib Kamalsada** has proposed a fix for this issue in the **main** branch:

**Add `match` keyword argument to rendering of foreign key constraints** https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/4833
