### ISSUE TITLE
Support future sqlalchemy change regarding sequence and identity

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/alembic#1304]
Add support for the changes that are added by https://github.com/sqlalchemy/sqlalchemy/issues/10247

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **main** branch:

**adapt identity logic to support dialect kwags** https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/4821
