### ISSUE TITLE
Facing an issue with alter enum column 

### ISSUE THREAD

**Issue by idomic** [sqlalchemy/alembic#1305]
**Describe the bug**
I initially set the postgres table as enum, but it was the native postgres enum type.
Now I'm trying to create a revision where I alter_column to the sa.Enum type, but I keep getting this error:
`AttributeError: Neither 'Column' object nor 'Comparator' object has an attribute 'lower'`

I also found [this thread](https://github.com/sqlalchemy/alembic/issues/278) and tried using some of the snippets in there but it didn't work for me.

What I tried to set in the migration script is this:
```
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Update ENUM columns to SQLAlchemy enums and not postgres enums
    name = "projects_type"
    old_type = ("aws-apprunner", "notebook-convert")
    new_type = tuple(ProjectType.get_values())
    sa_enum = sa.Enum(*new_type, name=name)
    psql_enum = sad_psql.ENUM(*old_type, name=name, create_type=False)
    op.alter_column("projects", sa.Column("type", sa_enum), old_type=psql_enum,
                    nullable=False)


    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Dealing with ENUM downgrades
    name = "project_type"
    new_type = ("aws-apprunner", "notebook-convert")
    old_type = sa.Enum(*tuple(ProjectType.get_values()), name="projects_type")
    psql_enum = sad_psql.ENUM(*new_type, name=name, create_type=False)
    op.alter_column("projects", sa.Column("type", psql_enum),
                    existing_type=old_type, nullable=False)

    # ### end Alembic commands ###
```

**Expected behavior**
I'd expect it to alter the column and from now on the Sqlalchemy column type will be used for this ENUM.

**Have a nice day!**

**Comment by CaselIT** [comment]
Hi,

As documented https://alembic.sqlalchemy.org/en/latest/ops.html#alembic.operations.Operations.alter_column alter_column accepts a column name, not a column object

**Comment by CaselIT** [comment]
Type should be the correct whay doing it.
If you already have the postgresql enum values as text set in the columns I think pg can change the type correctly, or by using the "using" part of the alter column https://alembic.sqlalchemy.org/en/latest/ops.html#alembic.operations.Operations.alter_column.params.postgresql_using
