### ISSUE TITLE
create special rendering for Variant

### ISSUE THREAD

**Issue by sqlalchemy-bot** [sqlalchemy/alembic#131]
**Migrated issue, originally created by Michael Bayer ([@zzzeek](https://github.com/zzzeek))**

a `Variant()` type would ideally be rendered like this:

```
op.add_column(Column("mycol", Variant(Enum, {"mysql": mysql.ENUM(...), "postgresql": postgresql.ENUM(...)})
```

the special thing here is that `Variant()` will typically have lots of dialect-specific types in it, which means we need to get dialect prefixes into the render.   So this kind of takes it outside the realm of straight `repr()` and I think alembic should have a special renderer for it.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Render Variant types** https://gerrit.sqlalchemy.org/1472

**Comment by sidujjain** [comment]
@zzzeek It seems that `type_` and `dialect_name` are getting generated in flipped order.     

Code generated during migration:
`sa.Column('id', sa.BigInteger().with_variant('sqlite', sa.INTEGER()), nullable=False)`

whereas sqlalchemy defines `with_variant` as:
 `def with_variant(self, type_, dialect_name)`

**Comment by zzzeek** [comment]
that sounds very believable because i get their order confused all the time.   what sounds more strange is that I remember testing this pretty hard but I guess not.

**Comment by zzzeek** [comment]
that's incredible, right in the test, the reversal can be seen

```
        type_ = (
            String(5)
            .with_variant(VARCHAR(10), "mysql")
            .with_variant(CHAR(15), "oracle")
        )

        # the new Black formatting will help a lot with this
        eq_ignore_whitespace(
            autogenerate.render._repr_type(type_, self.autogen_context),
            "sa.String(length=5)."
            "with_variant('mysql', sa.VARCHAR(length=10))."
            "with_variant('oracle', sa.CHAR(length=15))",
        )

```

it would be so great if I had people to help review code  :(

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Repair Variant argument order** https://gerrit.sqlalchemy.org/1520

**Comment by sidujjain** [comment]
Thanks for quick fix! 

Are you the sole maintainer at the moment?

**Comment by zzzeek** [comment]
at the moment that seems to be the case.
