### ISSUE TITLE
alembic --auogenerate should put columns from base class before columns from derived class

### ISSUE THREAD

**Issue by BlackZork** [sqlalchemy/alembic#1318]
**Describe the bug**
```python
@dataclass
class DbObject:
    id: Mapped[int] = mapped_column(primary_key=True)

@mapper_registry.mapped_as_dataclass
class IrsUser(DbObject):
    __tablename__ = "users"
    email: Mapped[str]
```

Result of `alembic revision --autogenerate`:

```python
    op.create_table('users',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
```

**Expected behavior**
In most cases it should be in reverse order. Columns from base class should be added first, then columns from derived classes.

**Versions**:
python 3.9
sqlalchemy 2.0.19
alembic 1.8,1

**Have a nice day!**

**Comment by CaselIT** [comment]
Hi,

This behaviour comes from sqlalchemy, and it's unlikely to be changed, at least not in a minor version.

You can use sort_order to control how the columns are laid out in a table https://docs.sqlalchemy.org/en/20/orm/mapping_api.html#sqlalchemy.orm.mapped_column.params.sort_order

**Comment by BlackZork** [comment]
Many thanks, I did not know about sort order. This works:

```python
@dataclass
class DbObject:
    id: Mapped[int] = mapped_column(primary_key=True, sort_order=-99)
```
