### ISSUE TITLE
`process_revision_directives` documentation disagrees with type annotation

### ISSUE THREAD

**Issue by jwodder** [sqlalchemy/alembic#1325]
[The documentation for `EnvironmentContext.configure.process_revision_directives`](https://alembic.sqlalchemy.org/en/latest/api/runtime.html#alembic.runtime.environment.EnvironmentContext.configure.params.process_revision_directives) states that the callable's third argument is a list of `MigrationScript`s, yet [the type annotations in the code](https://github.com/sqlalchemy/alembic/blob/5a95c35910185c5b1d53324d5e95b290bdac2446/alembic/runtime/environment.py#L44) state that the third argument is a list of `MigrateOperation`s, a superclass of `MigrationScript`.

This causes problems in particular when trying to add type annotations to the code from [the "Don't Generate Empty Migrations with Autogenerate" recipe](https://alembic.sqlalchemy.org/en/latest/cookbook.html#cookbook-no-empty-migrations), as use of the `upgrade_ops` property assumes that the list elements are `MigrationScript`s.

**To Reproduce**

Running mypy 1.6.0 (default config) on the following code:

```python
from __future__ import with_statement
import logging
from alembic import context
from alembic.migration import MigrationContext
from alembic.operations.ops import MigrationScript
import sqlalchemy as sa

config = context.config
logger = logging.getLogger("alembic.env")

engine: sa.Engine
metadata: sa.MetaData

def process_revision_directives(
    context: MigrationContext,  # noqa: U100
    revision: tuple[str, str],  # noqa: U100
    directives: list[MigrationScript],
) -> None:
    if getattr(config.cmd_opts, "autogenerate", False):
        script = directives[0]
        if script.upgrade_ops.is_empty():
            directives[:] = []
            logger.info("No changes in schema detected.")

with engine.connect() as connection:
    context.configure(
        connection=connection,
        target_metadata=metadata,
        process_revision_directives=process_revision_directives,
    )
    with context.begin_transaction():
        context.run_migrations()
```

fails with the error:

```text
sample02.py:29: error: Argument "process_revision_directives" to "configure" has incompatible type "Callable[[MigrationContext, tuple[str, str], list[MigrationScript]], None]"; expected "Callable[[MigrationContext, tuple[str, str], list[MigrateOperation]], None] | None"  [arg-type]
```

If `MigrationScript` is changed to `MigrateOperation`, the error changes to:

```text
sample01.py:21: error: "MigrateOperation" has no attribute "upgrade_ops"  [attr-defined]
```

**Versions.**
 - OS: macOS 14.0
 - Python: 3.11.6
 - Alembic: 1.12.0
 - SQLAlchemy: 2.0.22

**Comment by zzzeek** [comment]
hi -

for simple documentation issues we can accept PRs to correct problems.  thanks!

**Comment by jwodder** [comment]
@zzzeek So is the mistake simply that the third argument should be documented as a list of `MigrateOperations`s?  Then how is it safe for the "Don’t Generate Empty Migrations with Autogenerate" recipe to access an attribute that only exists on a subclass?

**Comment by zzzeek** [comment]
OK. the attribute is in practice a MigrationScript, I will attempt to change the typing to show MigrationScript all the way through and rewrite the doc example to be typed.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**match process_revision_directives typing to API** https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/4927

**Comment by zzzeek** [comment]
for the next release 1.12.1
