### ISSUE TITLE
Support of source object(.so) files in alembic versions.

### ISSUE THREAD

**Issue by adityaSiso** [sqlalchemy/alembic#1333]
**Describe the use case**
As a developer I want my alembic version files to be cythonized and protected. There should not be any data leakage. Currently, alembic is only able to find `.py, .pyc, and, .pyo` version files from the versions dir. 

**Databases / Backends / Drivers targeted**
MySQL and MongoDB.

**Have a nice day!**

**Comment by CaselIT** [comment]
Hi,

Not sure I understand the point of compiling the files. Migration files are hardly performance critical

**Comment by zzzeek** [comment]
They want them to be obfuscated for intellectual property purposes.   Alembic does not have integration with things like py2exe so you would need to develop this on your own .

**Comment by CaselIT** [comment]
You could create empty files that import from a module
```py
# plain python module used by alembic
from my_compiled_revision_123 import *
```

**Comment by CaselIT** [comment]
I'm -1 on this, since compiled files have different extensions in every os.

**Comment by zzzeek** [comment]
this is out of scope for alembic
