### ISSUE TITLE
Replace dateutil with zoneinfo buildin module

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/alembic#1339]
python 3.9+ the zoneinfo module. https://docs.python.org/3.11/library/zoneinfo.html#module-zoneinfo
for older version the backport can be used https://pypi.org/project/backports.zoneinfo/

@zzzeek this probably requires 1.13

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **main** branch:

**Use zoneinfo instead of dateutil.** https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/4917
