### ISSUE TITLE
`compare_type` does not detect length/param changes (when they get removed)

### ISSUE THREAD

**Issue by rafales** [sqlalchemy/alembic#1342]
1. Changing type of a column from `String(20)` to `String(50)` will autogenerate changes.
2. Changing type of a column from `String(20)` to `String()` will detect no changes.

As it is totally ok with some backends to pass no length (eg. postgres), these changes to the type should be detected.

Same goes for other types, I had trouble with `Numeric`, where a field was changed from `Numeric(scale=2)` to `Numeric()` and no changes were detected either.

**To Reproduce**

```py
import sqlalchemy as sa
from sqlalchemy import orm
from sqlalchemy.dialects import postgresql as pg


class Model(orm.DeclarativeBase):
    pass


class User(Model):
    __tablename__ = "users"

    id: orm.Mapped[int] = orm.mapped_column(primary_key=True)
    name: orm.Mapped[str] = orm.mapped_column(sa.String(80))
```

Setup alembic, set `compare_type=True`. Then change type to `sa.String()` or simply leave `name: orm.Mapped[str]`. An empty migration will be generated.

**Versions.**
 - OS: MacOS 13.6
 - Python: 3.1.14
 - Alembic: 1.12.1
 - SQLAlchemy: 2.0.22
 - Database: postgres 15.4
 - DBAPI: psycopg2 2.9.9
 -

**Comment by zzzeek** [comment]
hi -

this is normal and is there to avoid false positives.  See the notes at https://alembic.sqlalchemy.org/en/latest/autogenerate.html#comparing-and-rendering-types
