### ISSUE TITLE
target_metadata typing don't support metadata sequences

### ISSUE THREAD

**Issue by iurisilvio** [sqlalchemy/alembic#1348]
**Describe the bug**

From the [docs](https://alembic.sqlalchemy.org/en/latest/autogenerate.html#autogenerating-multiple-metadata-collections
):

> The target_metadata collection may also be defined as a sequence if an application has multiple MetaData collections involved:

But `target_metadata` typing is only `MetaData`.

https://github.com/sqlalchemy/alembic/blob/0e0131be34bb3a80c0cbc5cfe655c98dd838bfba/alembic/context.pyi#L100
https://github.com/sqlalchemy/alembic/blob/0e0131be34bb3a80c0cbc5cfe655c98dd838bfba/alembic/runtime/environment.py#L419

**Expected behavior**

The `target_metadata` type must include `Sequence[MetaData]`.

**To Reproduce**

Run mypy on this file.

```python
from sqlalchemy import MetaData
from alembic.migration import EnvironmentContext, Config, ScriptDirectory

context = EnvironmentContext(Config(), ScriptDirectory("."))
context.configure(target_metadata=[MetaData(), MetaData()])
```

**Error**

```
5: error: Argument "target_metadata" to "configure" of "EnvironmentContext" has incompatible type "list[MetaData]"; expected "MetaData | None"  [arg-type]
```

**Versions.**
 - OS: Ubuntu
 - Python: 3.11.4
 - Alembic: 1.12.1
 - SQLAlchemy: 2.0
 - Database:
 - DBAPI:

**Have a nice day!**

**Comment by sqla-tester** [comment]
**Iuri de Silvio** has proposed a fix for this issue in the **main** branch:

**Fixes: #1348 Typings for target_metadata sequence of metadatas** https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/4965
