### ISSUE TITLE
Remove support for python 3.7

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/alembic#1359]
Support for python 3.7 ended earlier this year, and it's being removed also for sqlalchemy 2.1

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **main** branch:

**Alembic 1.13 now supports Python 3.8 and above** https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/4975
