### ISSUE TITLE
`get_x_argument(as_dictionary=True)` fails if x values doesn't have `=`

### ISSUE THREAD

**Issue by iurisilvio** [sqlalchemy/alembic#1369]
**Describe the bug**

It is not safe to use `get_x_argument(as_dictionary=True)` because it fails with `-x foo`.

**Expected behavior**

I'd expect an empty string `""` (or `True`? or `None`?) as value instead of breaking my script.

**To Reproduce**

```py
from unittest.mock import Mock

from alembic.config import Config
from alembic.runtime.environment import EnvironmentContext
from alembic.script import ScriptDirectory

context = EnvironmentContext(Config(cmd_opts=Mock(x="foo")), ScriptDirectory("."))
context.get_x_argument(as_dictionary=True)
```

**Error**
```
$ python example.py
Traceback (most recent call last):
  File "example.py", line 8, in <module>
    context.get_x_argument(as_dictionary=True)
  File "alembic/runtime/environment.py", line 331, in get_x_argument
    value = dict(arg.split("=", 1) for arg in value)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: dictionary update sequence element #0 has length 1; 2 is required
```

**Versions.**
 - OS: 
 - Python:
 - Alembic:
 - SQLAlchemy:
 - Database:
 - DBAPI:

**Additional context**

**Have a nice day!**

**Comment by zzzeek** [comment]
> 
> Yes, I think an empty string is the least surprising value here

hmm not None?  what do we do if someone asks for x value and there was no -x ?

**Comment by CaselIT** [comment]
> > Yes, I think an empty string is the least surprising value here
> 
> hmm not None? what do we do if someone asks for x value and there was no -x ?

Well if `foo=bar` gives me `'bar'` it think the logic thing for `foo=` and `foo` is to return `''`. Otherwise we have two different behaviours in that case

**Comment by zzzeek** [comment]
> > > Yes, I think an empty string is the least surprising value here
> > 
> > 
> > hmm not None? what do we do if someone asks for x value and there was no -x ?
> 
> Well if `foo=bar` gives me `'bar'` it think the logic thing for `foo=` and `foo` is to return `''`. Otherwise we have two different behaviours in that case

oh ok.   that's fine then

**Comment by iurisilvio** [comment]
This is how I think too, `foo=` generate an empty string, `foo` should return the same value.

Talking about my use case, I just need something like multiple tags and I don't really care about the value.

I don't even need the dict. I could use `"foo" in context.get_x_argument()`, but then I can't use `as_dictionary` flag anywhere else because `foo` breaks it.

In any case, we still can check for the key with `"foo" in context.get_x_argument(as_dictionary=True)`.
