### ISSUE TITLE
Changing a unique index generate a non-unique downgrade

### ISSUE THREAD

**Issue by iurisilvio** [sqlalchemy/alembic#1371]
**Describe the bug**

The reverse operation for a **unique** index change (like changing columns) is a non-unique index.

```diff
-Index("ix_unique", "foo", unique=True)
+Index("ix_unique", "foo", "bar", unique=True)
```

The downgrade generates a non-unique index.

**Expected behavior**

The downgrade should preserve the `unique` flag.

**To Reproduce**
Please try to provide a [Minimal, Complete, and Verifiable](http://stackoverflow.com/help/mcve) example, with the migration script and/or the SQLAlchemy tables or models involved.
See also [Reporting Bugs](https://www.sqlalchemy.org/participate.html#bugs) on the website.

```py
from alembic.operations import ops

from sqlalchemy import Column, Index, Integer, MetaData, Table

metadata = MetaData()
table = Table(
    "t",
    metadata,
    Column("id", Integer(), primary_key=True),
    Column("x", Integer()),
)
ix = Index("ix1", table.c.id, unique=True)

op = ops.CreateIndexOp.from_index(ix)
assert op.reverse().to_index().unique
```

**Error**

AssertionError on last line.

**Versions.**
 - OS: Ubuntu
 - Python: 3.11
 - Alembic: main
 - SQLAlchemy: 2.0

**Additional context**

**Have a nice day!**

**Comment by zzzeek** [comment]
thanks.  1.13.0 is going out now, this can be part of 1.13.1
