### ISSUE TITLE
alembic is passing an empty tuple to conn.execute() which is nonsensical

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/alembic#1394]
this should be fixed because in https://github.com/sqlalchemy/sqlalchemy/issues/9647 we are going to disallow or warn for this

**Comment by CaselIT** [comment]
this is here
https://github.com/sqlalchemy/alembic/blob/abc8002ec67ddcb0a0be56b8167a4837f3884217/alembic/ddl/impl.py#L172

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**dont pass empty sequences to connection.execute()** https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/5122
