### ISSUE TITLE
create_foreign_key has wrong type annotations

### ISSUE THREAD

**Issue by kasium** [sqlalchemy/alembic#1429]
**Describe the bug**
`BatchOperations.create_foreign_key` states that the `constraint_name` should be a string, but it should be `Optional[str]`

**Versions.**
 - OS: Linux
 - Python: 3.12.0
 - Alembic: 1.12.1
 - SQLAlchemy: 1.4.51

**Additional context**
I'm happy to open a PR, but first wanted to create an issue

**Have a nice day!**

**Comment by CaselIT** [comment]
Hi,

Indeed it seems to be a bug, since the normal create_fk has it optional:
https://github.com/sqlalchemy/alembic/blob/a22d21a43c2eb7a12944377168727ed76a51aaa9/alembic/operations/ops.py#L595-L696

A PR would be appreciated!

**Comment by kasium** [comment]
@CaselIT thansk for the confirmation. I'll open a PR

**Comment by CaselIT** [comment]
Not yet, but it shouldn't be too long
