### ISSUE TITLE
script_location PATH config is not OS agnostic

### ISSUE THREAD

**Issue by developer992** [sqlalchemy/alembic#1431]
**Describe the bug**
This setting is different if you are running on Windows OS or Linux OS

```
script_location = app/db/migrations
```

**Expected behavior**
I am developing on Windows machine and i set the value of the setting to "app\db\migrations"

But then I build docker image, deploy and want to run it the server and I have to fix the config file to "app/db/migrations"

I find myself changing this quite frequently, is there a way to define this with mutli OS support in mind?

Thanks

**To Reproduce**
Please try to provide a [Minimal, Complete, and Verifiable](http://stackoverflow.com/help/mcve) example, with the migration script and/or the SQLAlchemy tables or models involved.
See also [Reporting Bugs](https://www.sqlalchemy.org/participate.html#bugs) on the website.

```py
# Insert code here
```

**Error**

```
# Copy error here. Please include the full stack trace.
```

**Versions.**
 - OS: 
 - Python:
 - Alembic:
 - SQLAlchemy:
 - Database:
 - DBAPI:

**Additional context**

**Have a nice day!**

**Comment by CaselIT** [comment]
Hi,

Does using `/` on windows not work?

**Comment by developer992** [comment]
no it fails with
```
FAILED: Path doesn't exist: '/app/xara\\db\\migrations'.  Please use the 'init' command to create a new scripts
  folder.
˙˙˙`

**Comment by developer992** [comment]
I have the setting in relative path but this is what running "alembic upgrade head" outputs

**Comment by CaselIT** [comment]
I can't reproduce.

I've just tried the following:
```
> systeminfo | rg 'OS Name'
OS Name:                   Microsoft Windows 11 Pro
> rg script_location .\alembic.ini
5:script_location = foo/bar/baz/migrations
> alembic history
<base> -> baaccf72950c (head), one
> ls .

    Directory: path\to\here

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----          27/02/2024    20:48                foo
-a---          27/02/2024    20:49           3647 alembic.ini
-a---          27/02/2024    20:49          24576 db.sqlite
```

**Comment by developer992** [comment]
ok i must be losing my mind then ... ok thanks

**Comment by CaselIT** [comment]
I don't think it's something that has to do with powershell, since the path is never handled by the shell since it's in the alembic file that's read by python.

Can you create a reproducing case for the error you are seeing?
