### ISSUE TITLE
Typo in Front Matter/Installation: alembic init .

### ISSUE THREAD

**Issue by kornelumann** [sqlalchemy/alembic#1463]
**Describe the bug**

https://alembic.sqlalchemy.org/en/latest/front.html#installation says
```
/path/to/your/project/.venv/bin/alembic init .
```

**Expected behavior**

It should be 
```
/path/to/your/project/.venv/bin/alembic init alembic
```

**To Reproduce**

Follow the installation instructions as on the page.

**Error**

```
  FAILED: Directory . already exists and is not empty
```

**Versions.**
 - Alembic: 1.13.1

**Additional context**

https://alembic.sqlalchemy.org/en/latest/tutorial.html has it correctly

```
$ alembic init alembic
```

_Yeah and there's a dot after **Versions** in this template._

**Have a nice day!**

**Comment by CaselIT** [comment]
Hi,

Indeed, thanks for reporting
