### ISSUE TITLE
IF EXISTS/IF NOT EXISTS directives

### ISSUE THREAD

**Issue by sqlalchemy-bot** [sqlalchemy/alembic#151]
**Migrated issue, originally created by Rémy Roy ([@remyroy](https://github.com/remyroy))**

IF EXISTS and IF NOT EXISTS are already part of many DBMSs DDL vocabulary. They have many use cases which are highly useful in some situations.

For instance, creating a table if it does not already exists or dropping a column if it exists.

It would be nice to have those directives with op in alembic. I guess they could be implemented using the native support for DBMSs that support them or with some introspection for those that do not.

Thanks

**Comment by CaselIT** [comment]
since sqlalchemy implemented https://github.com/sqlalchemy/sqlalchemy/issues/7354 this should now be pretty straight forward

**Comment by sqla-tester** [comment]
**Адриан Максим Александрович** has proposed a fix for this issue in the **main** branch:

**Added parameters if_exists and if_not_exists for index operations.** https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/4782
