### ISSUE TITLE
Support if_exists / if_not_exists on drop_table and create_table operations

### ISSUE THREAD

**Issue by agriffin-grow** [sqlalchemy/alembic#1520]
**Describe the use case**
This is similar to #524, which appears to at least be implemented for indexes.

SqlAlchemy already supports these operations on `DropTable` and `CreateTable` so this would essentially be a pass-through in a similar manner.

**Databases / Backends / Drivers targeted**

Postgresql

**Example Use**
Much like drop_index, I'd expect

```python
op.drop_table('foobar', if_exists=True)
```
to produce
```sql
DROP TABLE IF EXISTS foobar
```

**Additional context**
This is just some insurance for edge cases where a migration partially applies due to external circumstances. i.e. a migration containing two drop_table operations could fail after the first succeeds, but then would require some surgery to work again

**Have a nice day!**

**Comment by CaselIT** [comment]
Hi,

I was convinced it was already supported, but it seems not.

A PR with an initial implementation would be appreciated!

**Comment by agriffin-grow** [comment]
@CaselIT https://github.com/sqlalchemy/alembic/pull/1521

Hope that's everything

**Comment by agriffin-grow** [comment]
@CaselIT - do you know when we could expect this to get merged and released?

**Comment by CaselIT** [comment]
sorry, been on holiday this past week. Will try taking a look in the weekend

**Comment by CaselIT** [comment]
#1434 was a duplicate of this issue
