### ISSUE TITLE
Wrong generation partial index for Boolean condition

### ISSUE THREAD

**Issue by mmmcorpsvit** [sqlalchemy/alembic#1523]
**Expected behavior**
I will see in alembic script
```
    op.create_index('ix_unique_vin_active', 'lot', ['vin'], unique=True, postgresql_where=sa.text('active = TRUE'))
```

but get 
```
    op.create_index("ix_unique_vin_active", "lot", ["vin"], unique=True, postgresql_where=False)
```

**To Reproduce**
Please try to provide a [Minimal, Complete, and Verifiable](http://stackoverflow.com/help/mcve) example, with the migration script and/or the SQLAlchemy tables or models involved.
See also [Reporting Bugs](https://www.sqlalchemy.org/participate.html#bugs) on the website.

```py
    __table_args__ = (
        Index('ix_unique_vin_active', 'vin', unique=True, postgresql_where=active == True), 
        # Index("ix_unique_active_vin", "vin", unique=True, postgresql_where=(active == True)), # or like this way
    )
```

**Versions.**
 - OS: Windows
 - Python: 3.11
 - Alembic: 1.13.2
 - SQLAlchemy: 2.0.32
 - Database: PostgreSQL
 - DBAPI:

**Comment by CaselIT** [comment]
Hi,

What is active in your example? The fact that ot renders true/false suggest it's not a sqlalchemy column element

**Comment by mmmcorpsvit** [comment]
active is a bool field in my model

**Comment by CaselIT** [comment]
can you provide an example of your model?

**Comment by zzzeek** [comment]
please open a [discussion](https://github.com/sqlalchemy/alembic/discussions) if you have further need for help thanks
