### ISSUE TITLE
create_unique_constraint if not exists 

### ISSUE THREAD

**Issue by aakrem** [sqlalchemy/alembic#1530]
I would like to suggest adding a flag to the create_unique_constraint to check if the constraint exists or not.

https://alembic.sqlalchemy.org/en/latest/ops.html#alembic.operations.Operations.create_unique_constraint

maybe something similar to 
https://alembic.sqlalchemy.org/en/latest/ops.html#alembic.operations.Operations.create_index

**Comment by zzzeek** [comment]
that's not possible as there is no "IF NOT EXISTS" clause for an ALTER TABLE command

**Comment by aakrem** [comment]
right right okay then thank you!
