### ISSUE TITLE
Log directory location is insecure

### ISSUE THREAD

**Issue by devinbost** [sqlalchemy/alembic#1552]
Bug was encountered here: https://github.com/langflow-ai/langflow/issues/4235

I've been looking through the Alembic documentation, and I cannot find a way to change the log directory, such as via the `alembic.ini` file. Am I just not seeing it?

**Comment by zzzeek** [comment]
hi -

alembic does not specify a "logging directory".    the alembic environment includes a pre-configured logging environment that dumps logging to stdout, which you can see [here](https://github.com/sqlalchemy/alembic/blob/bd50ba325b10a1a9cdb452fe40c96f959825797c/alembic/templates/generic/alembic.ini.mako#L84).    An application may reconfigure this to point to a file such as the `alembic.log` your k8s issue refers to.   or it may not use `alembic.ini` at all and instead use an alternate logging configuration, by modifying the env.py code seen [here](https://github.com/sqlalchemy/alembic/blob/bd50ba325b10a1a9cdb452fe40c96f959825797c/alembic/templates/generic/env.py#L12).
