### ISSUE TITLE
Make version table customizable by dialects

### ISSUE THREAD

**Issue by maver1ck** [sqlalchemy/alembic#1560]
**Describe the use case**
Starrocks is Open-Source, High-Performance Analytical Database.
https://www.starrocks.io

**Databases / Backends / Drivers targeted**

Starrocks

**Example Use**
Management of Tables in Starrocks.

**Additional context**
I will create PR with detailed technical solution.

**Have a nice day!**

**Comment by zzzeek** [comment]
Alembic only includes support for SQLAlchemy's built-in dialects: oracle, postgresql, sqlite, mysql, mssql.    To add alembic implementations to third party dialects, you should contribute your PR to that dialect's github repository.

**Comment by zzzeek** [comment]
the alembic_version table has only one column.  it is by definition the first column in the table.

**Comment by zzzeek** [comment]
both statements are identical

```py
>>> from sqlalchemy import table, column
>>> alembic_version = table("alembic_version", column("version_num"))
>>> print(alembic_version.select())
SELECT alembic_version.version_num 
FROM alembic_version
>>> print(alembic_version.select().with_only_columns(alembic_version.c.version_num))
SELECT alembic_version.version_num 
FROM alembic_version

```

**Comment by zzzeek** [comment]
this is why, let's open a discussion and step through what's happening

**Comment by CaselIT** [comment]
I think the issue is that they want to use a table that has two columns with an autoincrement id as the first column. Not sure if it's a constraint of starrocks the fact that it requires one such column as the fist one.

**Comment by sqla-tester** [comment]
**Maciek Bryński** has proposed a fix for this issue in the **main** branch:

**Add ability to configure alembic_version table in DialectImpl** https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/5556

**Comment by zzzeek** [comment]
ok you're released thanks for the patience

**Comment by maver1ck** [comment]
Thanks @zzzeek.

**Comment by jaogoy** [comment]
@maver1ck  Hi friend, have it solved the problem?
Currently, I've tested alembic with StarRocks, I still encounter the problem with alembic_version. (of course, there are also a lot of other problems.)

**Comment by maver1ck** [comment]
Hi @jaogoy,
I'm using this implementation of Dialect along with Starrocks with success.
https://github.com/StarRocks/starrocks/blob/main/contrib/starrocks-python-client/starrocks/alembic.py#L10

**Comment by jaogoy** [comment]
@maver1ck Can you tell me how to use it? I'm not familar with Alembic, I don't know how to register the starrocks module into Alembic, even after I searched in GPT.

**Comment by maver1ck** [comment]
Hi,
You just need to import this class and use alembic as usual.

**Comment by jaogoy** [comment]
@maver1ck Thank you very much. It works when I have imported the StarrocksImpl class.

And, I have another question: **Does it support alerting a table**? It seems **NOT**.
When I make some change in my `models.py` to add/remove some columns, it can make a schema diff by running `alembic revision --autogenerate` command, but I can't do upgrade by running `alembic upgrade head`. It throws an Error:
```
INFO  [alembic.runtime.migration] Context impl StarrocksImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade b4a8153528db -> a6dccfeb6346, diff1
Traceback (most recent call last):
  File "/python/alembic-venv/lib/python3.10/site-packages/sqlalchemy/sql/visitors.py", line 137, in _compiler_dispatch
    meth = getter(visitor)
AttributeError: 'StarRocksDDLCompiler' object has no attribute 'visit_clause'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
......
sqlalchemy.exc.UnsupportedCompilationError: Compiler <starrocks.dialect.StarRocksDDLCompiler object at 0x10e27b790> can't render element of type <class 'alembic.ddl.mysql.MySQLModifyColumn'> (Background on this error at: https://sqlalche.me/e/20/l7de)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
......
  File "/python/alembic-venv/lib/python3.10/site-packages/sqlalchemy/ext/compiler.py", line 525, in _wrap_existing_dispatch
    raise exc.UnsupportedCompilationError(
sqlalchemy.exc.UnsupportedCompilationError: Compiler <starrocks.dialect.StarRocksDDLCompiler object at 0x10e27b790> can't render element of type <class 'alembic.ddl.mysql.MySQLModifyColumn'>: <class 'alembic.ddl.mysql.MySQLModifyColumn'> construct has no default compilation handler. (Background on this error at: https://sqlalche.me/e/20/l7de)
```

It seems that **StarRocksDDLCompiler** is simple, and it doesn't support altering columns?

**Comment by maver1ck** [comment]
This may be a drawback of Alembic Python driver.
I'm not sure if this is working as I'm using Alembic with plain SQL.

**Comment by jaogoy** [comment]
> This may be a drawback of Alembic Python driver. I'm not sure if this is working as I'm using Alembic with plain SQL.

@maver1ck How to use "plan SQL"? It seems Alembic doesn't support plan SQL.
