### ISSUE TITLE
detect changes in type parameters

### ISSUE THREAD

**Issue by sqlalchemy-bot** [sqlalchemy/alembic#180]
**Migrated issue, originally created by Anonymous**

Hey there Mike, hope you're doing well :)

Firstly, thanks so much for creating SQL Alchemy and Alembic!

I'm trying out the latest version of Alembic (0.6.3) with my current Flask project backed by a PostgreSQL database and have noticed one rather important limitation.  Alembic doesn't seem to detect any changes to existing columns.

So let's take a simple scenario to demonstrate this problem...

Suppose I start with a Person model as follows:

```
class Person(db.Model):
    id = db.Column('id', db.Integer, primary_key=True)
    name = db.Column(db.String(50))
    email = db.Column(db.String(100), unique=True)
```

This generates the upgrade migration shown below as expected:

```
def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    ### end Alembic commands ###
```

Which I apply to my database.

Now, suppose I needed to make the email address column larger.  I update the model as follows...

```
-    name = db.Column(db.String(50))
+    name = db.Column(db.String(100))
```

But now when generating a new migration, Alembic doesn't pick up the alteration to the column.

```
def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
```

As a comparison, I tested out the newly implemented migrations in Django's 1.7 alpha 2 and it picked up all changes to my columns, even more complex changes like changing data type and so forth.

Am I perhaps missing something or is Alembic simply not able to detect such changes yet?  Do you think this is something you might support in future?

Thanks heaps for your help!

Fotis

**Comment by zzzeek** [comment]
this is resolved by #605
