### ISSUE TITLE
add mssql_drop_XYZ flags to autogenerate op.drop_column() based on observation of mssql + known type-specific check constraints, defaults, FKs

### ISSUE THREAD

**Issue by sqlalchemy-bot** [sqlalchemy/alembic#184]
**Migrated issue, originally created by Marek Baczyński ([@imbaczek](https://github.com/imbaczek))**

DB: SQL Server 2008R2

SQLAlchemy==0.9.3

alembic==0.6.4dev (today's master and 0.6.3 too)

```
def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('table', sa.Column('col1', sa.Enum('one', 'two', name='ck_col1'), nullable=True))
    op.add_column('table', sa.Column('col2', sa.Boolean(name='ck_col2'), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('table', 'col2')
    op.drop_column('table', 'col1')
    ### end Alembic commands ###
```

```
$ alembic downgrade 328
INFO  [alembic.migration] Context impl MSSQLImpl.
INFO  [alembic.migration] Will assume transactional DDL.
INFO  [alembic.migration] Running downgrade 26f5521a70be -> 328b04eddf97, added table table
[...]
  File "pymssql.pyx", line 435, in pymssql.Cursor.execute (pymssql.c:6347)
sqlalchemy.exc.OperationalError: (OperationalError) (5074, "The object 'ck_col2' is dependent on column 'col2'.DB-Lib error message 5074, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\nDB-Lib error message 4922, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\n") 'ALTER TABLE [table] DROP COLUMN col2' {}

```
(constraint names above are tweaked to increase readability, related to #183)

----------------------------------------
Attachments: [184.patch](../wiki/imported_issue_attachments/184/184.patch)

**Comment by zzzeek** [comment]
the related issue is #186 which was fixed.

While it would be nice for this flag to automatically render, this is a fairly special case for now and other than having it render unconditionally in all cases, which would be wasteful, I don't have a solution right now for how this flag could always come out correctly.   If we look into doing a generalized ENUM solution, that would be separate from this.
