### ISSUE TITLE
Upload wheel

### ISSUE THREAD

**Issue by sqlalchemy-bot** [sqlalchemy/alembic#191]
**Migrated issue, originally created by Jeroen Ruigrok van der Werven ([@asmodai](https://github.com/asmodai))**

Hi Mike,

saw that you had already added wheel to your setup.cfg, but could you also upload the wheels to PyPi?

Simple matter of running: `python setup.py bdist_wheel upload`

Thanks!

**Comment by youtux** [comment]
Hello, I see that both sqlalchemy and mako provide wheels now, would it be possible to upload the wheels also for alembic?
It cuts down some build time when installing it on environments that don't use a shared system cache (e.g. docker containers).

**Comment by zzzeek** [comment]
if Mako has a wheel it's because someone had me run "bdist wheel" manually.   I would have to update my release scripts for wheels to be consistent or perhaps @CaselIT can add a github action to this repo to do such (that's how SQLAlchemy wheels work).

**Comment by CaselIT** [comment]
Since alembic and mako are universal wheels (I think) it should be very easy to setup :)

**Comment by layday** [comment]
The last version to have had a wheel published on PyPI was 1.5.2 on 20 Jan - was re-dropping wheels intentional?

**Comment by zzzeek** [comment]
I've just not integrated it into my build process as of yet, so I have to remember to do it.

SQLAlchemy  has wheels integrated via github actions and alembic and mako could use this as well.

**Comment by zzzeek** [comment]
well at least there is "pip wheel" and "twine upload" now so I can do the whole bunch of them at once without unpacking anything.

**Comment by CaselIT** [comment]
I can add a workflow to create it on release. it would be more or less the same as this proposal for the sphinx extension https://github.com/sqlalchemyorg/zzzeeksphinx/pull/2

**Comment by layday** [comment]
Do you sign the sdists, or why do you prefer to build and upload the sdists locally and the wheels on GHA, if you don't mind me asking?

**Comment by zzzeek** [comment]
the wheels are on GHA because github supplies a whole swarm of OSes including windows and OSX to build C code on every possible platform for SQLAlchemy.     for pure Python wheels I would basically have to add a few lines to my local "create_release.sh" script, have not gotten around to it.

**Comment by CaselIT** [comment]
we seem to have added it at some point, since recent releases have them https://pypi.org/project/alembic/#files
