### ISSUE TITLE
Alembic doesn't cleaup up after itself

### ISSUE THREAD

**Issue by sqlalchemy-bot** [sqlalchemy/alembic#25]
**Migrated issue, originally created by Daniel Miller ([@millerdev](https://github.com/millerdev))**

Some alembic commands (for example, upgrade and downgrade) create an engine and a connection, but these resources are not cleaned up on exit. I have some tests that create a new database, run alembic commands, and finally drop the database. However, the database cannot be dropped until the alembic resources are cleaned up. These resources are created in env.py. Should the env.py templates include some resource cleanup?

    
    #!python
    
    engine = engine_from_config(
        config.get_section(config.config_ini_section),
        prefix='sqlalchemy.')
    
    connection = engine.connect()
    try:
        context.configure(
                    connection=connection, 
                    target_metadata=target_metadata
                    )
    
        with context.begin_transaction():
            context.run_migrations()
    finally:
        connection.close()
        engine.dispose()

**Comment by hartzell** [comment]
I'm finding myself in a similar situation, where I need to call engine.dispose() in my application code so that my tests are able to drop the database and succeed.  

I just want my application to be able to check the schema version, and put this together (cribbed from [here](//stackoverflow.com/questions/24431366/getting-alembic-database-version-programmatically)).

```python
def get_actual_schema_revision(uri):
    current_rev = None
    try:
        engine = create_engine(uri)
        conn = engine.connect()
        context = MigrationContext.configure(conn)
        current_rev = context.get_current_revision()
    finally:
        conn.close()
        engine.dispose()

    return current_rev
```

The changeset you cite above is no longer available.  I can see the diff between those two commits by cloning the repo and running:

```
git diff 279f8359031a363e0c43a49dd87ac133eba4f6e9^..279f8359031a363e0c43a49dd87ac133eba4f6e9
```

but I guess I'm in the 'curious user' class you mention.  It seems uglier for me to iterate over all the connections.

If we're not supposed to call `engine.dispose`, then what is the proper way to clean something like this up?

**Comment by zzzeek** [comment]
> I'm finding myself in a similar situation, where I need to call engine.dispose() in my application code so that my tests are able to drop the database and succeed.

this should never be necessary.  ensure you commit or rollback all transactions in progress before ending your test suite.

> 
> I just want my application to be able to check the schema version, and put this together (cribbed from [here](//stackoverflow.com/questions/24431366/getting-alembic-database-version-programmatically)).
> 
> ```python
> def get_actual_schema_revision(uri):
>     current_rev = None
>     try:
>         engine = create_engine(uri)
>         conn = engine.connect()
>         context = MigrationContext.configure(conn)
>         current_rev = context.get_current_revision()
>     finally:
>         conn.close()
>         engine.dispose()

conn.close() is enough as that will roll back any transactional state on the connection that's holding locks.


> The changeset you cite above is no longer available. I can see the diff between those two commits by cloning the repo and running:

this is an ancient issue.  the codebase has changed completely since it was open and has been migrated from  mercurial to git years ago.

> If we're not supposed to call `engine.dispose`, then what is the proper way to clean something like this up?

connection.close().  if that's not working then please open a new issue with a complete [MCVE](http://stackoverflow.com/help/mcve) and please include complete information about database, DBAPI / driver version in use.  thanks!

**Comment by hartzell** [comment]
> if that's not working then please open a new issue with a complete [MCVE](http://stackoverflow.com/help/mcve) and please include complete information about database, DBAPI / driver version in use.

Done, see #702.
