### ISSUE TITLE
server_default on postgres json column breaks automigration

### ISSUE THREAD

**Issue by sqlalchemy-bot** [sqlalchemy/alembic#272]
**Migrated issue, originally created by drmaples ([@drmaples](https://github.com/drmaples))**

I am trying to run a migration via `--autogenerate` on a JSON column with a server_default. Alembic generates invalid sql which causes the migration to fail.

stack trace:
```
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    manager.run()
  .
  .
  .
  File "/code/api/.env_py2/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/code/api/.env_py2/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 951, in _execute_context
    context)
  File "/code/api/.env_py2/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 443, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (ProgrammingError) syntax error at or near "{"
LINE 1: SELECT '{"data":[]}'::json = {"data":[]}
```

sqlalchemy column definition:
```
suggested = db.Column(postgresql.JSON(), nullable=False, server_default=text('{"data":[]}'))
```

what the column looks like in the db:
```
suggested json NOT NULL DEFAULT '{"data":[]}'::json,
```

db and library versions:
```
PostgreSQL 9.2.4 on x86_64-apple-darwin12.4.0, compiled by i686-apple-darwin11-llvm-gcc-4.2 (GCC) 4.2.1 (Based on Apple Inc. build 5658) (LLVM build 2336.11.00), 64-bit

Flask==0.10.1
Flask-Migrate==1.2.0
Flask-SQLAlchemy==1.0
SQLAlchemy==0.9.8
psycopg2==2.5.1
alembic==0.7.4
```

**Comment by zzzeek** [comment]
Seems like things are working now as far as what I can glean from the use case here (it's not clear if this column was added to the metadata, or removed from the DB, or what).

So I went with having the table in the DB already, then running autogenerate with default compare, then the "downgrade" has the DROP TABLE.  It has correct application of quoting which doesnt seem to be in the examples here so we would assume that got fixed along the way some years back when we improved server default comparison.

Start with a table:

```python
Table(
    "test",
    target_metadata,
    Column("data", JSON, server_default=text('\'{"data":[]}\''))
)


e = create_engine("postgresql://scott:tiger@localhost/test", echo=True)

target_metadata.create_all(e)
```

then run autogenerate with a blank metadata, generates:

```python
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("test")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "test",
        sa.Column(
            "data",
            postgresql.JSON(astext_type=sa.Text()),
            server_default=sa.text("'{\"data\":[]}'::json"),
            autoincrement=False,
            nullable=True,
        ),
    )
    # ### end Alembic commands ###
```

looks pretty legit. then run an upgrade to drop the table, then a downgrade to recreate it.  SQL output succeeds, looks good:

```sql
CREATE TABLE test (
	data JSON DEFAULT '{"data":[]}'::json
)

```

**Comment by 4dahalibut** [comment]
Hey @zzzeek , it seems that this issue does still exist if there is already a server default on the table

**Comment by zzzeek** [comment]
this issue is eight years old, and it sounds like you are describing something completely different since this has to do with the "create_table" directive where by definition nothing "already" exists.      I'd recommend please open an issue with clear, full reproduction steps as well as include a stack trace please.
