### ISSUE TITLE
DBAPI-agnostic dialect use for offline mode

### ISSUE THREAD

**Issue by sqlalchemy-bot** [sqlalchemy/alembic#304]
**Migrated issue, originally created by Michael Bayer ([@zzzeek](https://github.com/zzzeek))**

The psycopg2 dialect doubles up percent signs.  in offline mode, there's no DBAPI thus we should use the default dialect minus DBAPI.  However SQLAlchemy does not expose this.  We may want upstream SQLA to support a url of the form "postgresql+generic://" to make this possible, but the solution should be agnostic of backend (still might require adding the name "generic" to each module).

**Comment by zzzeek** [comment]
we don't render bound parameters in SQL mode so this issue doesn't make any sense, closing.
