### ISSUE TITLE
PEP8-format generated revisions

### ISSUE THREAD

**Issue by sqlalchemy-bot** [sqlalchemy/alembic#307]
**Migrated issue, originally created by Adrian ([@thiefmaster](https://github.com/thiefmaster))**

Even though they usually need to be modified a bit, it would be nice if the generated statements were PEP8-valid by default (besides maybe line-length..)

**Comment by sqla-tester** [comment]
**Mike Waites** has proposed a fix for this issue in the **master** branch:

**Format autogenerated revisions** https://gerrit.sqlalchemy.org/1060

**Comment by mikeywaites** [comment]
Hey 👋 

hoping there's still some people interested in this.  I've been (very slowly) getting through some of these tickets and would love some feedback/testing on the proposed solution linked above.

The plan is to provide formatting via some simple hooks (with a couple of popular options baked in) to allow users to specify a third party library that alembic can defer formatting to.  We think this is the best option as it means all the various nuances of pep8 can be catered for by libraries that will do a much better job than we will

I'm hoping to get this merged next week so any help before then would be greatly appreciated.

**Comment by m-aciek** [comment]
@mikeywaites I will try to test this in the near future.

Is there chance for it to be merged?
