### ISSUE TITLE
Support PostgreSQL "named schemas"

### ISSUE THREAD

**Issue by sqlalchemy-bot** [sqlalchemy/alembic#409]
**Migrated issue, originally created by Petri Savolainen**

See https://www.postgresql.org/docs/current/static/ddl-schemas.html

For multi-tenant applications, named schemas are commonly used.

**Comment by zzzeek** [comment]
so the information here isn't correct.  schema_translate_map is not really supported with Alembic, it works here and there but not for things like autogenerate.   for PG named schemas right now the only approach is to manipulate the search path.    The issue here is a dupe of #555.
