### ISSUE TITLE
auto generate not working for postgres JSONB

### ISSUE THREAD

**Issue by sqlalchemy-bot** [sqlalchemy/alembic#411]
**Migrated issue, originally created by Paul van der Linden**

When I auto generate a migration for a model with a jsonb field i get the following error:
```
    sa.Column('data', postgresql.JSONB(astext_type=Text()), nullable=True),
NameError: name 'Text' is not defined
```
This is with version alembic `0.8.10` and sqlalchemy `1.1.5`, it used to work, and would not add the `astext_type=Text()` (in version alembic `0.8.9` and sqlalchmey `1.0.15`).

**Comment by mikeywaites** [comment]
Hey @joanna350 sorry you're still having trouble. 

So that I can properly replicate the issue could you provide me with a simple test case, version of poatgresql you're running, versions of alembic and sqlalchemy.

**Comment by joanna350** [comment]
I really appreciate this response..and look forward to hearing back in the other thread, or other links that may help. thanks.
