### ISSUE TITLE
Support Comments on Table / Columns

### ISSUE THREAD

**Issue by sqlalchemy-bot** [sqlalchemy/alembic#422]
**Migrated issue, originally created by Brice Maron ([@emerzh](https://github.com/emerzh))**

Hi, 
it seems that sqlalchemy supports comments on objects 
(https://bitbucket.org/zzzeek/sqlalchemy/issues/1546/feature-request-commenting-db-objects)
which is awesome! 

it could be really cool if it can be integrated to alembic as well

**Comment by TargetLiu** [comment]
I need this feature very much, hope to publish soon, thx.

**Comment by zzzeek** [comment]
@targetliu the review is ongoing at https://gerrit.sqlalchemy.org/#/c/sqlalchemy/alembic/+/932/.  what you can do to help is try out this patch (see "download" dropdown in upper right) and see what works and what doesn't.  Then you can leave comments on the gerrit or even if you wanted to push fixes to this review I can give you access to do that.    it takes a village !

**Comment by mikeywaites** [comment]
@TargetLiu @sweh 

I'm really keen to get this wrapped up this week.  I've been dragging this along for an age now.  Could really appreciate some help testing if you have some time.

**Comment by mikeywaites** [comment]
@TargetLiu @sweh 

Scrap that.  I've missed a pretty big chunk of the autogenerate flow so i'll work on that today.  The famous "works in unit tests" problem :)

Apologies for this taking so long, Now i'm starting to get my head around the code base the next tickets will hopefully come faster.

**Comment by sqla-tester** [comment]
**Mike Waites** has proposed a fix for this issue in the **master** branch:

**Implemented support for Table and Column Comments** https://gerrit.sqlalchemy.org/932
