### ISSUE TITLE
'alembic history' ignores env.py

### ISSUE THREAD

**Issue by sqlalchemy-bot** [sqlalchemy/alembic#447]
**Migrated issue, originally created by rkrzr ([@rkrzr](https://github.com/rkrzr))**

We rely on `env.py` to set the correct PYTHONPATH, so that we can import our modules in an alembic migration. This works for all commands (e.g. `alembic current`,  `alembic upgrade`, `alembic downgrade`), except for `alembic history`.

For `alembic history` it fails with: `ModuleNotFoundError: No module named 'bla'`

It seems that `alembic history` does not read in `env.py`.

The workaround for this is to run `PYTHONPATH=. alembic history`, which works correctly.

**Comment by nugrahari** [comment]
use autogenerate params

alembic revision --autogenerate -m "initial migrations"
