### ISSUE TITLE
drop_constraint(... type_='check') working too well with naming conventions

### ISSUE THREAD

**Issue by sqlalchemy-bot** [sqlalchemy/alembic#453]
**Migrated issue, originally created by Matt Jernigan ([@juanitogan](https://github.com/juanitogan))**

v0.8.4

This:

```
op.drop_constraint('ck_forms_code_friendly', 'forms', type_='check')
```

tries to drop a constraint called `ck_forms_ck_forms_code_friendly` which is not consistent with the other drop constraint types that don't apply the naming convention here.

To drop `ck_forms_code_friendly` you must do it this way instead:

```
op.drop_constraint('code_friendly', 'forms', type_='check')
```

**Comment by zzzeek** [comment]
i've added more docs for this case in 873027160f88af277b73223e9
