### ISSUE TITLE
add environment control for *all* ScriptDirectory commands

### ISSUE THREAD

**Issue by sqlalchemy-bot** [sqlalchemy/alembic#460]
**Migrated issue, originally created by Mischa ([@mischas](https://github.com/mischas))**

continuing from #447:

all commands that use ScriptDirectory.from_config() should be altered to use a context manager that examines "revision_environment" and then optionally makes use of EnvironmentContext.

the idea is that people are now coding imports into their revision files that need to be pulled in from env.py in order for the files to be importable.  ScriptDirectory is not usable without this directive.

**Comment by zzzeek** [comment]
I've just read through all the messages here and it seems to come down to people using their Python application without their paths set up ahead of time, and then manual manipulation of sys.path and/or PYTHONPATH within the .py files.  That's not how modern Python applications are meant to be used.    There are now widely accepted patterns in use, and if someone truly wants to have PYTHONPATH set up, that's what environmental shell scripts are for.    Seeing as Alembic has an enormous backlog of more important issues I don't see this being implemented right now without a clearer rationale.
