### ISSUE TITLE
Downgrade for just one branch from multi heads

### ISSUE THREAD

**Issue by sqlalchemy-bot** [sqlalchemy/alembic#464]
**Migrated issue, originally created by dem0n3d ([@dem0n3d](https://github.com/dem0n3d))**

I frequently need possibility to downgrade just one of my heads to branchpoint, but alembic tries to downgrade all of them. Can you implement this feature, please?

**Comment by simonbowly** [comment]
Interested to discuss & implement this if it is still going to be useful for others.  I'm using alembic to manage multiple branches and ran into similar issues trying to wind back a single branch to a branchpoint reliably.

I have a rough concept for an `alembic checkout` implementation which covers (at least) the cases mentioned in these issues:

- `alembic checkout rev2` in #464 would run downgrades to remove only `rev2a` and `rev3a` on `branchb`
- `alembic checkout B` would downgrade only revision C as mentioned in #660 (similarly for `alembic checkout C`)

Roughly the idea is to:

1. Determine the current subtree of revisions that the database uses (trace all ancestors & dependencies from the current revision set).
2. Determine the target subtree (my thinking is to use `alembic checkout <rev1> <rev2> ...` as suggested in this issue which specifies a complete target tree state).
3. Determine revision scripts to be downgraded and upgraded, run downgrades in reverse topological sort order then upgrades in topological sorted order to reach the target state.

Happy to put a PR together for this but are there are other cases that should be covered or should a different API be used?

**Comment by zzzeek** [comment]
why is it called "alembic checkout"?    if one wants to "downgrade" I would think they'd be using the "downgrade" command ?

**Comment by zzzeek** [comment]
or is this command of a more general scope?    "checkout" from tools like git sounds like a passive command but running upgrades and downgrades is not a passive operation.

**Comment by simonbowly** [comment]
Ah, I went with the OP's suggestion of "checkout" but hadn't thought about this, makes sense.

I was thinking of a very general operation that runs upgrades and downgrades as necessary to migrate the database to a fixed state.  So the OPs of these issues are after in general:

Initial state:
```
base -> rev1 --> rev2 (brancha)
             +-> rev2a (branchb)
             +-> rev2b (branchb)
```

Final state after some alembic operation (doesn't seem to currently be possible as `alembic downgrade -1` might choose a different branch to wind back):
```
base -> rev1 --> rev2 (brancha)
             +-> rev2a (branchb)
```

I'm suggesting `alembic checkout rev2 rev2a` should be interpreted as "`rev2` and `rev2a` is the target set of revisions" to be kept, so it should run a downgrade of the `rev2b` script.

**Comment by zzzeek** [comment]
can you review my comment at https://github.com/sqlalchemy/alembic/issues/464#issuecomment-441887420 and see if the proposed syntax (which is a syntax we already have, branch@revision, will work, that is:

    alembic downgrade rev2b@rev1


see https://alembic.sqlalchemy.org/en/latest/branches.html#working-with-branch-labels for a description of this syntax.

**Comment by simonbowly** [comment]
Yes I can see that this syntax makes more sense to downgrade a specific branch.  Your suggested patch handles the labelled branch case as long as the labelled revision is a current head.  I'll attempt a PR for a more general approach.

I found a few odd quirks (I think) of `downgrade` with multiple branches while trying this out.  Will point them out in a separate issue.

**Comment by sqla-tester** [comment]
**Simon Bowly** has proposed a fix for this issue in the **master** branch:

**New downgrade algorithm to fix branch behaviour** https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/2530
