### ISSUE TITLE
Redundant Foreign Key migrations (again)

### ISSUE THREAD

**Issue by rjaduthie** [sqlalchemy/alembic#519]
Although there are other closed issues addressing this, they seem to deal with postgres and I have not found a solution to the problem I've seen.  The problem is reproducable and I've created a minimal example: https://github.com/sqlalchemy/alembic/files/2625781/FK_test.tar.gz

On repeated `alembic revision --autogenerate` then `alembic upgrade head` commands, alembic always seems to want to drop and create the foreign keys.

**Logging** to stdout:
```bash
    INFO  [alembic.autogenerate.compare] Detected removed foreign key (t1_id)(id) on table table_two
    INFO  [alembic.autogenerate.compare] Detected added foreign key (t1_id)(id) on table test_fktdb.table_two
```
Resulting **migration script**:
```python
 def upgrade():
        # ### commands auto generated by Alembic - please adjust! ###
        op.drop_constraint('fk_table1', 'table_two', type_='foreignkey')
        op.create_foreign_key('fk_table1', 'table_two', 'table_one', ['t1_id'], ['id'], source_schema='test_fktdb', referent_schema='test_fktdb')
        # ### end Alembic commands ###


    def downgrade():
        # ### commands auto generated by Alembic - please adjust! ###
        op.drop_constraint('fk_table1', 'table_two', schema='test_fktdb', type_='foreignkey')
        op.create_foreign_key('fk_table1', 'table_two', 'table_one', ['t1_id'], ['id'])
        # ### end Alembic commands ###
```

**ORM** code:
```python

# [...imports and bobs...]

class TableOne(Base):
    """Class representing a table with an id."""
    __tablename__ = "table_one"

    id = Column(UNSIGNED_INTEGER, nullable=False, autoincrement=True, primary_key=True)

    __table_args__ = (
        dict(mysql_engine='InnoDB'),
    )


class TableTwo(Base):
    """A table representing records with a foreign key link to table one."""
    __tablename__ = "table_two"

    id = Column(UNSIGNED_INTEGER, nullable=False, autoincrement=True, primary_key=True)
    t1_id = Column(UNSIGNED_INTEGER, nullable=False)

    __table_args__ = (
        ForeignKeyConstraint(["t1_id"], ["test_fktdb.table_one.id"], name="fk_table1"),
        dict(mysql_engine='InnoDB'),
    )
```

**Software versions**: alembic 1.0.5, SQLAlchemy 1.2.14, MySQL 5.7, Python 3.6.7

I've documented this on StackOverflow here:
https://stackoverflow.com/questions/53523529/alembic-revision-autogenerate-produces-redundant-foreign-key-migrations

**Comment by zzzeek** [comment]
your attachment seems to have just an env.py file inside of it, there's no files for the "from test_fktdb.orm import Base as FKTDB_Base" part, can you just attach the zip to the issue here? github supports attachments

**Comment by rjaduthie** [comment]
Sorry, I think filedropper is doing something to the tar.  Here it is unadulterated:

[FK_test.tar.gz](https://github.com/sqlalchemy/alembic/files/2625781/FK_test.tar.gz)

**Comment by zzzeek** [comment]
nice effort on the test case here.  since it's docker i can actually just run it, thanks

**Comment by zzzeek** [comment]
though I think I already see the problem just want to confirm

**Comment by rjaduthie** [comment]
Sounds promising.

**Comment by zzzeek** [comment]
> Thanks for this.
> 
> Firstly, I had already tried `include_schemas=True` without any change in behaviour. From the docs, this option seemed to be focussed on situations with multiple schemas, which I don't have.

this only would work if the database you connect to is not the schema name, see my example:

```
   SCHEMA_NAME = "NOT_test_fktdb"
  
  # e.g.:

   e = create_engine("mysql://hostname/%s" % SCHEMA_NAME)


``

> 
> > you are connecting with "test_fktdb" in your database URL as the default schema. which means, alembic is going to find your tables in that schema
> 
> So, what part of the system is dictating this? SQLAlchemy? The PyMySQL driver? If this issue was cleared up, there'd be no need to remove metadata from the ORM.

SQLAlchemy's convention is that table metadata is agnostic of the default schema in the database if the schema_name is not given.   To work correctly, table reflection must assume the same convention, meaning, when it reflects database tables, if those tables are in the default schema, the "schema" parameter is not filled in.     Without this assumption, all kinds of use cases become un-symmetrical.   It is possible that SQLAlchemy reflection could be enhanced to allow "schema explicit" to be an option, however we've tried to stick to one single convention that, when followed, can work in all cases, rather than trying to support two conventions as this issue is confusing enough.

> 
> Regarding the solutions
> I've ruled out the second option, as there won't be another DB on the server and it doesn't seem like a good idea to introduce one for these purposes solely. I did try connecting without a schema specified (i.e. the sqlalchemy.url = "mysql+pymysql://bob:password@172.17.0.2") but SQLAlchemy doesn't like that.

right, the "no database" use case is something that we also don't support right now, which is because most backends don't even support such a concept, it is idiosyncratic to MySQL.   That is, I can't connect to a SQLite or Postgresql database without there being an implicit "no-schema" database that I can CREATE TABLE inside of without schema qualification.

> 
> In trying to get the first sugggestion working with the example, I've changed a couple of things:
> 
> ```python
> # instead of [...]:
> # declarative_base(metadata=sqlalchemy.MetaData(schema=test_fktdb.SCHEMA_NAME))
> Base = sqlalchemy.ext.declarative.declarative_base()
> 
> # instead of [...]:
> # ForeignKeyConstraint(["t1_id"], ["test_fktdb.table_one.id"], name="fk_table1"),
> ForeignKeyConstraint(["t1_id"], ["table_one.id"], name="fk_table1"),
> ```
> 
> ... and that works as you predicted! Thanks. However, I wonder if there will be any issue now that the tables don't have a scheam defined in their metadata, for example with normal SQL Alchemy operation. 

They are now defined as schema agnostic.  the database name you put in your engine URL in create_engine() is where those tables will be created.

> I had a thought that the metadata could be massaged in env.py to make it work. Although `target_metadata.schema=None` is easy, trawling through tables, etc., and changing their names becomes unwieldy.

yes, people expect that they can change their database URL to some totally other thing, and their Table objects work the same way over there as in the other URL.  That is, they are portable.  When you add a schema name, the table is *still* portable, in that the schema name is relative to the default schema.   This has to do with what the "schema" concept was modeled after, which is Postgresql schemas, that is, you can have a database, and then within it, multiple schemas.

When "schema" is used with a database that does not actually support PG-style "schemas", like MySQL or Oracle, it instead acts as kind of a cross-database accessor, but this usage is much less common.

> 
> Anyway thanks for your help. I'll see if the easy solution is suitable for my application.

any "user question" issue pretty much is going to mean the documentation is lacking so the section in https://docs.sqlalchemy.org/en/latest/core/metadata.html#specifying-the-schema-name which is very terse and old should be enhanced to include some of my information above as well as to draw from some of the material at https://docs.sqlalchemy.org/en/latest/dialects/postgresql.html#remote-schema-table-introspection-and-postgresql-search-path.

**Comment by zzzeek** [comment]
oh, but over on the SQLAlchemy side.

**Comment by cbradl01** [comment]
In case it's helpful to anyone else, I just posed my solution to a similar problem on SO: https://stackoverflow.com/a/74311722/18572704

**Comment by TomerLankri** [comment]
@cbradl01  I tried using that solution but no luck.
I posted my configuration here any chance someone can take a look ?
https://stackoverflow.com/questions/78029653/alembic-autogenerate-creates-redundant-foreign-key-migrations-for-mysql-database

**Comment by handzlikt** [comment]
@zzzeek I have a slightly different configuration but similar problem. I've tried suggestions rom this thread but couldn't get it working as expected. Could you maybe help me with that?
I've prepared minimal reproducable example in Docker 

[multitenant_mre.tar.gz](https://github.com/user-attachments/files/23774833/multitenant_mre.tar.gz)

My approach:
- models use SqlAlchemy 2.0 syntax
- I have a `shared` schema (with it's own alembic config) and tenant schemas (with another alembic config for them all)
- I use `tenant_<name>` schemas for actual tenants, and `tenant` schema as a reference schema for autogenerating migrations (it's my source o truth).
- The Base for tenant models has schema set to 'tenant' which in my actual app is translated with `connectable.execution_options(schema_translate_map = {"tenant": tenant.schema_name})`

Once you run `docker compose up` a basic setup will be executed.
Then when you run
`docker compose run --rm migrations alembic -n tenant-schema -x schema_name=tenant revision --autogenerate -m "Test"`
I would expect no changes to be generated, but it actually generates:
```
def upgrade() -> None:    
  op.drop_constraint(op.f('user_tenant_id_fkey'), 'user', type_='foreignkey')
  op.create_foreign_key(None, 'user', 'tenant', ['tenant_id'], ['id'], source_schema='tenant', referent_schema='shared')
```

**Comment by CaselIT** [comment]
it's likely that sqlalchemy is not seeing the schemas as you expect them. if you turn on engine logging what schema is sqlalchemy using for the reflection queries?

**Comment by handzlikt** [comment]
I've turned on the engine loging and the queries look correct to me (they include correct schema name). This issue appars only for migrations where there is a foreign key with cross schema reference (pointing to the 'shared' schema).
