### ISSUE TITLE
add column with comment for postgresql

### ISSUE THREAD

**Issue by larrylau** [sqlalchemy/alembic#521]
I used sqlalchemy to create table, It will call **SetColumnComment** .
How does alembic AddColumn do it?
>

    if self.dialect.supports_comments and not self.dialect.inline_comments:
            if table.comment is not None:
                self.connection.execute(SetTableComment(table))

            for column in table.columns:
                if column.comment is not None:
                    self.connection.execute(SetColumnComment(column))

**Comment by zzzeek** [comment]
this is issue #422 .  thanks!
