### ISSUE TITLE
how to disabled param binding ?

### ISSUE THREAD

**Issue by Dog-Lee** [sqlalchemy/alembic#522]
i have the version py like this:

```python
from alembic import op
op.execute('''
        INSERT INTO my_table VALUES ('{\"Global Private Network\":true,\"}');
'''))

```

and i got the error :
```
sqlalchemy.exc.StatementError: (sqlalchemy.exc.InvalidRequestError) A value is required for bind parameter 'true'
```

obviously :true is not a param, so how to pass alembic params binding ? 

i try using
```python
op.get_bind().execute('''
             INSERT INTO my_table VALUES ('{\"Global Private Network\":true,\",\"Over 99.99% Availaiblity\":true}');
''')
```

op.get_bind() can pass param binding, but i get another error。
```
sqlalchemy.exc.ProgrammingError: (_mysql_exceptions.ProgrammingError) not enough arguments for format string
```

**Comment by zzzeek** [comment]
op.execute() coerces the string into a sqllachemy text() construct, where you have to escape colons with a backslash:   "\:true".   this is not documented, will add.

**Comment by zzzeek** [comment]
your second error message is because of the percent sign, you're in raw SQL mode there so that has to be doubled, "%%".   you hit the worst case for both worlds in one statement :)
