### ISSUE TITLE
remove "force" parameter from identifierpreparer.quote, quote_schema in alembic/ddl/base.py

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/alembic#528]
The "force" parameter has had [no effect since 0.9](https://docs.sqlalchemy.org/en/latest/core/internals.html?highlight=quote#sqlalchemy.sql.compiler.IdentifierPreparer.quote)  and I was going to remove it entirely in 1.3, though at the moment I'm going to just have it emit a deprecation warning.   this will still cause alembic's tests to fail on the warning.

**Comment by zzzeek** [comment]
e.g. 

https://github.com/sqlalchemy/alembic/blob/master/alembic/ddl/base.py#L179

https://github.com/sqlalchemy/alembic/blob/master/alembic/ddl/base.py#L181

https://github.com/sqlalchemy/alembic/blob/master/alembic/ddl/base.py#L187

**Comment by ParthS007** [comment]
Hi @zzzeek 
Can I work on this Issue?

**Comment by mikeywaites** [comment]
@ParthS007 I did make a start but work totally anhilated me last week. I was hoping to sit down tonight and work on it some more. 

More than happy if you wanna pick it up though, I didn't get far.

**Comment by ParthS007** [comment]
okay, I will work on this. :+1: 
I have to remove `force=None` parameter from [here]( https://github.com/sqlalchemy/alembic/blob/master/alembic/ddl/base.py#L179).
Am I getting this right? If not can you please help me getting started with this issue?
Thanks for the quick reply.

**Comment by mikeywaites** [comment]
Yes, having looked at this again I can confirm that's correct.  the force param will now result in alembic test suite to fail so we just want that removed.  I can see one place this is happening that @zzzeek  has already pointed out.

Give the test suite a run once it's removed and you should be good to go.  Not sure why I thought there was more to it than this but hey, thanks for picking this up anyway, the help is really appreciated @ParthS007

**Comment by ParthS007** [comment]
@mikeywaites I have made the Pull Request. Please review and let me know your views on it. :smiley:

**Comment by mikeywaites** [comment]
@ParthS007 Sorry i've been slow on this.  Will take a look later on today and get this reviewed.

**Comment by sqla-tester** [comment]
**Parth Shandilya** has proposed a fix for this issue in the **master** branch:

**Removed force parameter from base.py** https://gerrit.sqlalchemy.org/1125
