### ISSUE TITLE
Alembic bug, NameError: name 'Text' is not defined importing JSON -- Continued issue

### ISSUE THREAD

**Issue by joanna350** [sqlalchemy/alembic#531]
Reproducing https://realpython.com/flask-by-example-part-2-postgres-sqlalchemy-and-alembic/..
Seems to be a common error but..all the solutions that were suggested in all the links I had access to, did not resolve the problem for me so far..
Some github site recommended importing (5th line) Text straight from the relevant directory, but no avail. Please advise.

    from app import db   
    import sqlalchemy as sa
    from sqlalchemy.dialects.postgresql import JSON
    from sqlalchemy import Integer, String, TIMESTAMP
    from sqlalchemy.types import Text

    class Result(db.Model):
        __tablename__ = 'results'

        id = db.Column(Integer, primary_key = True)
        url = db.Column(sa.String())
        result_all = db.Column(JSON)
        result_no_stop_words = db.Column(JSON)

        def __init__(self, url, result_all, result_no_stop_words):
            self.url = url
            self.result_all = result_all
            self.result_no_stop_words = result_no_stop_words

        def __repr__(self):
            return('<id {}>'.format(self.id))

**Comment by mikeywaites** [comment]
Hey @joanna350 

I just replied to your comment on #411 

Could you provide me with examples of what you have specifically rather than the link to the post. Examples of your models, the revision you've generated, version of postgresql etc will all help me to understand the issue properly.

**Comment by joanna350** [comment]
postgreSQL v.11
model is in the code.. (when I import db, it is just a line db = SQLAlchemy(app) )
Or do you mean to say the actual data I am to input?
I thought this was a framework that I first instantiate, after which I load JSON. (which is flexible)
not sure what you mean by revision?

**Comment by zzzeek** [comment]
@mikeywaites just checked, if they are using a non-postgresql database URI in alembic.ini (which would be a mistake to use in conjunction with the postgresql.JSON datatypes), the rendering for postgresql.JSON() will fail to include the "sa." module prefix because it does not consult the PG dialect for rendering information.

**Comment by joanna350** [comment]
As Im mainly following the tutorial first, not sure what you mean by non-postgresql database URI in alembic.ini and how to fix it. Could you elaborate please

**Comment by joanna350** [comment]
Unless you can specify where I did not follow..I am not certain this is really my mistake. Because I edited certain commands that didn't work on my OS environment as the comments in that post did. (Mac Pro 2011, Mojave is what I use and this tutorial is 2 years outdated) If you see what is wrong, could you not just tell me? And really there isn't that many steps to follow. If you see the comments, they do say to make more changes which are what Im wondering I did not do.

**Comment by mikeywaites** [comment]
The issue with the autogenerated migration has been explained above.

Regarding my pointing out that there was a difference between your code and the tutorial, i was simply trying to be helpful and not in any way accusatory.  

I did point out where I spotted the difference.  

> The main thing i spotted was that you do not instantiate your flask app object with one of the config objects you've created.

You're not instantiating the flask app object in app.py with your config object not are you doing so as show in the examples. Nor are you doing so as shown in your manage.py file.

EG `app.config.from_object(os.environ['APP_SETTINGS'])` 

To get this issue back on focus, if you can apply the change I've specified to your migration and confirm that it has resolved the issue (for now).

**Comment by joanna350** [comment]
This line causes error.. `app.config.from_object(os.environ['APP_SETTINGS'])` that is why I removed it.

**Comment by joanna350** [comment]
I am not entirely sure where the issue began, but apparently that importing of configuration setting was crucial. Thank you all for looking into the problem with me, wish the best of this module!
