### ISSUE TITLE
requies minimum number of characters to match version numbers in commands

### ISSUE THREAD

**Issue by claweyenuk** [sqlalchemy/alembic#534]
Can version matching get more strict?

https://github.com/sqlalchemy/alembic/blob/master/alembic/script/revision.py#L376

Ideally, something like `if len(resolved_id) < 3` set `revs = []`.

I went to downgrade an database, and accidentally typed `alembic downgrade 1` instead of `alembic downgrade -1` and happened to have a single revision start with a "1", so the downgrade continued.

DB migrations can result in data loss, I think it's ok to require a certain number of characters when identifying the migration.

**Comment by zzzeek** [comment]
this is acceptable if someone wants to work on it.

**Comment by claweyenuk** [comment]
Great!  Thanks!

I'll plan to do it in the next few weeks (though if anyone sees this message, feel free to pick this change up)

**Comment by zzzeek** [comment]
please ensure your PR has tests in tests/test_command.py

**Comment by claweyenuk** [comment]
Will do

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Only allow partial revision match for > 3 characters** https://gerrit.sqlalchemy.org/1466

**Comment by claweyenuk** [comment]
Thanks for making a fix. (Sorry I never got around to it). This is exactly what I was thinking of.
