### ISSUE TITLE
Wrong key used in example in documentation for Config object

### ISSUE THREAD

**Issue by federicotdn** [sqlalchemy/alembic#536]
In [the documentation on the `Config` class](https://alembic.sqlalchemy.org/en/latest/api/config.html#alembic.config.Config), an example is shown which contains the following code:
```python
from alembic.config import Config
alembic_cfg = Config()
alembic_cfg.set_main_option("script_location", "myapp:migrations")
alembic_cfg.set_main_option("url", "postgresql://foo/bar")
alembic_cfg.set_section_option("mysection", "foo", "bar")
```

Specifically, the line using `"url"` as key should be changed to `"sqlalchemy.url"`, since that is the key that is read later on. Using `"url"` only yields in `KeyError: 'url'` being thrown when the `alembic` command is used.

**Comment by zzzeek** [comment]
technically it depends on what you put in your env.py but sure, please send a PR for this.
