### ISSUE TITLE
Keyword arguments at __table_args__ are not taken into account

### ISSUE THREAD

**Issue by decaz** [sqlalchemy/alembic#538]
According to the solution taken from https://groups.google.com/forum/#!topic/sqlalchemy/qCQFD2LNyTQ I'm trying to add `info` to the `__table_args__` as the last argument as the dictionary (https://docs.sqlalchemy.org/en/latest/orm/extensions/declarative/table_config.html#table-configuration):
```python
__table_args__ = (
    db.Index('user_created_at_idx', created_at),
    {
        'info': {
            'postgresql_partition': 'PARTITION BY RANGE (created_at)',
        },
    },
)
```
But alembic does not specify that dictionary as the `**kw` when calling `op.create_table`.

**Comment by zzzeek** [comment]
the "info" dictionary is not rendered as part of autogenerate.   "PARTITION BY" is directly supported as a Table argument so perhaps you mean to say:

`__table_args__ = (Index(...), {"postgresql_partition_by": "RANGE (created_at)"})
`
see https://docs.sqlalchemy.org/en/latest/dialects/postgresql.html#postgresql-specific-index-options

**Comment by decaz** [comment]
Ah, sorry, didn't know about such an option. Thanks!
