### ISSUE TITLE
Please publish changelog in a format that Dependabot (and similar tools) can find

### ISSUE THREAD

**Issue by robertknight** [sqlalchemy/alembic#543]
We use [Dependabot](https://dependabot.com) to help us keep Python dependencies up to date in our projects. It creates PRs when a new version of a dependency becomes available. These PRs usually include details of the changes since the last update, fetched from either the project's changelog file, or GitHub release information, or some other machine readable source.

In the case of Alembic however the PRs don't contain this information because the CHANGES file is some prose that points to a page on the Alembic site. For example: https://github.com/hypothesis/lms/pull/488.

It would be helpful if the CHANGES file included details of the changes directly, or if they were published as metadata of the GitHub release, so that Dependabot and similar/related services can more easily find and present it.

**Comment by zzzeek** [comment]
Hi there -

Alembic's changelog uses restructured text which is in a machine readable format.  Every change contains all the information which you request as well as the github bug number.   The file is present in all releases here: https://github.com/sqlalchemy/alembic/blob/master/docs/build/changelog.rst .

this file is consumed by [changelog](https://github.com/sqlalchemyorg/changelog/)

please let me know this resolves your issue thanks!

**Comment by zzzeek** [comment]
releases are now published in markdown format at https://github.com/sqlalchemy/alembic/releases
