### ISSUE TITLE
generated create_table_comment doesn't use repr for the comment parameters

### ISSUE THREAD

**Issue by RazerM** [sqlalchemy/alembic#549]
I'm on alembic 1.0.8, I think #529 only dealt with the column comments

**Comment by zzzeek** [comment]
Sorry I look at alembic like once a month, which parameters on which functions please?  examples / PR with tests

**Comment by RazerM** [comment]
Sorry I should have provided more info in the first place:

```python
op.create_table_comment('table_name', 'this quote isn't escaped')
op.drop_table_comment('table_name', existing_comment='this quote isn't escaped')
```

It may be both `comment` and `existing_comment` on both of those functions. I only had examples like above.

**Comment by zzzeek** [comment]
a PR w test support would be most helpful

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Use repr for table comment in create_table_comment / drop_table_comment** https://gerrit.sqlalchemy.org/1464
