### ISSUE TITLE
consider rationale for ModifyTableOps emitting "pass" for no operations

### ISSUE THREAD

**Issue by RazerM** [sqlalchemy/alembic#550]
I was using alembic's rewrite feature to ignore comment changes (temporarily, not important for the issue):

```python
@writer.rewrites(ops.AlterColumnOp)
def rewrite_alter_column(context, revision, op):
    op.modify_comment = False
    if not op.has_changes():
        return []
    return op
```

the resulting migration file has many pass lines:

```python
def upgrade():
    pass
    pass
    pass
    ...
```

It would be nice if alembic wouldn't add unnecessary `pass` lines.

I found the cause:

https://github.com/sqlalchemy/alembic/blob/d46de05b8b3281a85e6b107ef3f3407e232eb9e9/alembic/autogenerate/render.py#L117

---

I found a workaround by rewriting `ModifyTableOps` after the first rewriter has finished:

```python
writer1 = Rewriter()
writer2 = Rewriter()

@writer1.rewrites(ops.AlterColumnOp)
def rewrite_alter_column(context, revision, op):
    op.modify_comment = False
    if not op.has_changes():
        return []
    return op

@writer2.rewrites(ops.ModifyTableOps)
def rewrite_modify_table_ops(context, revision, op):
    if op.is_empty():
        return []
    return op

writer = writer1.chain(writer2)
```

**Comment by zzzeek** [comment]
need to determine rationale why "pass" is present, no tests cover the code currently:

```
diff --git a/alembic/autogenerate/render.py b/alembic/autogenerate/render.py
index 21bbb50..698ef63 100644
--- a/alembic/autogenerate/render.py
+++ b/alembic/autogenerate/render.py
@@ -114,7 +114,7 @@ def _render_modify_table(autogen_context, op):
 
         return lines
     else:
-        return ["pass"]
+        return [""]
 
 
 @renderers.dispatch_for(ops.CreateTableCommentOp)

```

need to determine if there is any impact to removing this additional  "pass" as well as to provide test coverage.  Contirbutors can start here by writing tests for this code and submitting a PR that includes the change + tests

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Render a single "pass" only for UpgradeOps, DowngradeOps** https://gerrit.sqlalchemy.org/1465

**Comment by zzzeek** [comment]
we do need to render a "pass" if you were to rewrite all the ops to have no elements, it's just the "pass" needs to be only once at the top level if no lines rendered
