### ISSUE TITLE
support mysql DROP for CHECK constraints, which might be different from that of mariadb

### ISSUE THREAD

**Issue by hahahannes** [sqlalchemy/alembic#554]
With version 8.0.16 mysql fully supports constraints. But I noticed that drop_constraint is not working because it produces ALTER TABLE DROP CONSTRAINT and not ALTER TABLE DROP CHECK which mysql uses

**Comment by zzzeek** [comment]
hi -

MariaDB added real check contraints first, and we support those with "ALTER TABLE DROP CONSTRAINT " which is what MariaDB allows.   At the time, there was no "DROP CHECK".   
Can you refer me to the MySQL documentation illustrating the syntax they'd like to use, and can you confirm that they are *not* accepting MariaDB's syntax ?

**Comment by zzzeek** [comment]
we would need to run "DROP CHECK" syntax against mariadb also to see if they support it, however I have a feeling that at least some MariaDB versions that support CHECK constraints might not support "DROP CHECK" syntax.   Basically we need a syntax table.

**Comment by hahahannes** [comment]
thanks for the fast response. The link to the documentation [https://dev.mysql.com/doc/refman/8.0/en/create-table-check-constraints.html](https://dev.mysql.com/doc/refman/8.0/en/create-table-check-constraints.html).

Yes, I can confirm.
To reproduce with version 8.0.16:
``` sql
CREATE TABLE test (id VARCHAR(50), CONSTRAINT test_constraint CHECK (id IS NOT NULL));
ALTER TABLE test DROP CONSTRAINT test_constraint; -> syntax error
ALTER TABLE test DROP CHECK test_constraint; -> working
```

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Emit DROP CHECK for MySQL, DROP CONSTRAINT for MariaDB** https://gerrit.sqlalchemy.org/1245

**Comment by zzzeek** [comment]
yup thanks, i have an approach in review.    it just might be difficult for the --sql use case.
