### ISSUE TITLE
Wrong description for unit-tests

### ISSUE THREAD

**Issue by anetbnd** [sqlalchemy/alembic#557]
Hello

when reading the file https://github.com/sqlalchemy/alembic/blob/master/README.unittests.rst I had the feeling, that the test-framework tries to discover the database configuration, which should be run by itself. The following sentence implies this for me:

```
The test suite will attempt to run a subset of tests against various database backends, including Postgresql and MySQL. It uses the database URLs in the [db] section of setup.cfg to locate a URL for particular backend types.
```

However when I tried to run tests against my postgres configuration, which uses exactly the URL given in the setup.cfg for postgres, all postgres tests are always skipped. I spent hours on debugging this until I found out, that by default only the default-configuration (sqlite) is run, all other configurations are not taken automatically into account. 

To run postgres tests, I had to first install `nose` and to start the tests with `python run_tests.py --db postgresql` instead of `python setup.py test`. This should be clearly explained in the unit-test description file, to prevent contributors from wasting a lot of time, just to figure out, why certain tests are skipped.

**Comment by zzzeek** [comment]
my apologies, I had updated this long ago in SQLAlhcemy but forgot to do so for Alembic

**Comment by zzzeek** [comment]
note tests are run like this:

    tox -e py37

or using py.test directly.   run_tests.py is deprecated.
