### ISSUE TITLE
Cookbook recipe for database freshness check

### ISSUE THREAD

**Issue by m-aciek** [sqlalchemy/alembic#559]
This feature request is for a cookbook recipe to programatically check database freshness.

Snippet:
```python
from alembic import config
from alembic import script
from alembic.runtime import migration
import sqlalchemy

import exceptions


engine = sqlalchemy.create_engine(DATABASE_URL)
alembic_cfg = config.Config('alembic.ini')
directory = script.ScriptDirectory.from_config(alembic_cfg)
with engine.begin() as conn:
    context = migration.MigrationContext.configure(conn)
    if context.get_current_revision() != directory.get_current_head():
        raise exceptions.DatabaseIsNotUpToDate('Upgrade the database.')
```

(Gist: https://gist.github.com/m-aciek/118d450ee59a41176214b5f93a02cc6f.)

**Comment by zzzeek** [comment]
kind of the natural mashup of the examples given in https://alembic.sqlalchemy.org/en/latest/api/script.html#script-directory and https://alembic.sqlalchemy.org/en/latest/api/runtime.html#the-migration-context, I can accept a PR for this and it might be nice if the above two API docs referred to it as a `.. seealso::`.
