### ISSUE TITLE
inspect.getfullargspec() is deprecated in python 3.8

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/alembic#563]
causes test suites to fail

see
https://github.com/sqlalchemy/sqlalchemy/issues/4674

**Comment by zzzeek** [comment]
getargspec is used in alembic for:

- argspec of command functions in command.py

- argspec of MigrateOperation methods registered with @register_operation

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Use vendored getargspec()** https://gerrit.sqlalchemy.org/1288
