### ISSUE TITLE
How do I autogenerate table comments? 

### ISSUE THREAD

**Issue by zzztimbo** [sqlalchemy/alembic#565]
Given:

```python
from sqlalchemy import Column, DateTime, String, Integer, func  
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()

class Bug(Base):  
    __tablename__ = 'bug'
    id = Column(Integer, primary_key=True)
    bug_tracker_url = Column(String, unique=True, comment="the bug tracker url")
```

How do I add a table comment? It is clear to me how to add column comments. 
The end goal is to have a generated SQL: 
```sql
COMMENT ON TABLE bug IS 'The bug table!!';
```

**Comment by zzzeek** [comment]
comments autogenerate automatically as long as you are on a version of SQLAlchemy and Alembic which supports it as well as a database backend that supports comments which are currently MySQL, PostgreSQL, and Oracle (See https://docs.sqlalchemy.org/en/13/changelog/migration_12.html?highlight=comment%20support#support-for-sql-comments-on-table-column-includes-ddl-reflection).

Please specify:
1. database in use
2. SQLAlchemy version in use
3. alembic version in use

thanks!

**Comment by zzztimbo** [comment]
Postgres 9.4.20
SQLAlchemy 1.3.3
Alembic 1.0.10

I've already verified that I can manually add the table comment to the generated migration script. 

```
    op.create_table('bug',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bug_tracker_url', sa.String(), nullable=True, comment='the bug tracker url'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bug_tracker_url'),
    comment="The bug table!!"
    )
```

What do I need to add to my original code snippet in order for this comment to be auto-generated?

**Comment by zzzeek** [comment]
oh, this is table comment, you have to add that to the Table you're specifying, with declarative this is `__table_args__`:

```
class Bug(Base):  
    __tablename__ = 'bug'
    __table_args__ = {"comment": "a comment"}
    id = Column(Integer, primary_key=True)
    bug_tracker_url = Column(String, unique=True, comment="the bug tracker url")

```

**Comment by zzztimbo** [comment]
thank you @zzzeek this worked for me.
