### ISSUE TITLE
Solution to work autogenerate enums on postgresql

### ISSUE THREAD

**Issue by mrquokka** [sqlalchemy/alembic#567]
According [this](https://github.com/sqlalchemy/alembic/issues/278) many users have this problem.
But how can i resolve this now? Have not found example, can you write it, please?

**Comment by zzzeek** [comment]
hi -

autogenerate doesn't work for enums right now, so you simply write the migrations manually:

    op.execute("ALTER TYPE colors ADD VALUE 'orange' AFTER 'red';")

please see the [postgresql documentation](https://www.postgresql.org/docs/9.1/sql-altertype.html) for the syntaxes.
