### ISSUE TITLE
Autogenerate enums, classes inheritance

### ISSUE THREAD

**Issue by mrquokka** [sqlalchemy/alembic#568]
Thanks for previos answer. How can i get metadata changes, If i need to manually processing that?

**Comment by mrquokka** [comment]
tried to

```
from alembic.migration import MigrationContext
from ...... import engine
mc = MigrationContext.configure(engine.connect())
print(compare_metadata(mc, Base.metadata)
```)

But it will rise error

 ```
   context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/hdd/work/envs/main/lib/python3.6/site-packages/alembic/runtime/environment.py", line 839, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/hdd/work/envs/main/lib/python3.6/site-packages/alembic/runtime/migration.py", line 361, in run_migrations
    step.migration_fn(**kw)
  File "/hdd/work/projects/main/ekra-sql-orm-migrations/ekra_sql_orm_migrations/alembic/versions/7255ad6ccc0f_.py", line 50, in upgrade
    print(compare_metadata(mc, Base.metadata))
  File "/hdd/work/envs/main/lib/python3.6/site-packages/alembic/autogenerate/api.py", line 104, in compare_metadata
    migration_script = produce_migrations(context, metadata)
  File "/hdd/work/envs/main/lib/python3.6/site-packages/alembic/autogenerate/api.py", line 134, in produce_migrations
    compare._populate_migration_script(autogen_context, migration_script)
  File "/hdd/work/envs/main/lib/python3.6/site-packages/alembic/autogenerate/compare.py", line 25, in _populate_migration_script
    _produce_net_changes(autogen_context, upgrade_ops)
  File "/hdd/work/envs/main/lib/python3.6/site-packages/alembic/autogenerate/compare.py", line 51, in _produce_net_changes
    autogen_context, upgrade_ops, schemas
  File "/hdd/work/envs/main/lib/python3.6/site-packages/alembic/util/langhelpers.py", line 303, in go
    fn(*arg, **kw)
  File "/hdd/work/envs/main/lib/python3.6/site-packages/alembic/autogenerate/compare.py", line 83, in _autogen_for_tables
    autogen_context,
  File "/hdd/work/envs/main/lib/python3.6/site-packages/alembic/autogenerate/compare.py", line 164, in _compare_tables
    inspector.reflecttable(t, None)
  File "/hdd/work/envs/main/lib/python3.6/site-packages/sqlalchemy/engine/reflection.py", line 633, in reflecttable
    table_name, schema, **table.dialect_kwargs
  File "/hdd/work/envs/main/lib/python3.6/site-packages/sqlalchemy/engine/reflection.py", line 372, in get_columns
    self.bind, table_name, schema, info_cache=self.info_cache, **kw
  File "<string>", line 2, in get_columns
  File "/hdd/work/envs/main/lib/python3.6/site-packages/sqlalchemy/engine/reflection.py", line 55, in cache
    ret = fn(self, con, *args, **kw)
  File "/hdd/work/envs/main/lib/python3.6/site-packages/sqlalchemy/dialects/postgresql/base.py", line 2850, in get_columns
    comment,
  File "/hdd/work/envs/main/lib/python3.6/site-packages/sqlalchemy/dialects/postgresql/base.py", line 2967, in _get_column_info
    coltype = coltype(*args, **kwargs)
  File "/hdd/work/envs/main/lib/python3.6/site-packages/sqlalchemy/dialects/postgresql/base.py", line 1397, in __init__
    super(ENUM, self).__init__(*enums, **kw)
  File "<string>", line 2, in __init__
  File "/hdd/work/envs/main/lib/python3.6/site-packages/sqlalchemy/util/deprecations.py", line 130, in warned
    return fn(*args, **kwargs)
  File "/hdd/work/envs/main/lib/python3.6/site-packages/sqlalchemy/sql/sqltypes.py", line 1359, in __init__
    self._enum_init(enums, kw)
  File "/hdd/work/envs/main/lib/python3.6/site-packages/sqlalchemy/sql/sqltypes.py", line 1399, in _enum_init
    length = max(len(x) for x in self.enums)
  File "/hdd/work/envs/main/lib/python3.6/site-packages/sqlalchemy/sql/sqltypes.py", line 1399, in <genexpr>
    length = max(len(x) for x in self.enums)
TypeError: object of type 'NoneType' has no len()
```

**Comment by mrquokka** [comment]
answer is 

from alembic.migration import MigrationContext
from alembic.autogenerate.api import compare_metadata
from EXAMPLE_MODULE.base import engine, Base

mc = MigrationContext.configure(engine.connect())
print(compare_metadata(mc, Base.metadata))

But it cannot see metadata content and all of them as dropped

**Comment by zzzeek** [comment]
hi -

i don't keep track of usernames can you please refer to what is being discussed?     github is not a chat room exactly

**Comment by mrquokka** [comment]
Hi, https://github.com/sqlalchemy/alembic/issues/567. It was a courtesy.
Does not matter, i answer my question. Thread may beclosed, but maybe you can add it to the documentation, someone may need it

**Comment by zzzeek** [comment]
it's so hard for me to answer questions that are asked like this, that's a row from an autogenerate there's no "transaction" there, can you please try to provide a complete example of what you are doing?

**Comment by mrquokka** [comment]
> it's so hard for me to answer questions that are asked like this, that's a row from an autogenerate there's no "transaction" there, can you please try to provide a complete example of what you are doing?

I have 3 troubles:
1) I would like to create enums on postgresql, but autogeneratescript raise Error

```
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedObject) type "UnitMultiplier" does not exist
LINE 7:  _payment_multiplier "UnitMultiplier", 
```
2) alembic.commands.revision trigger Flash watch script and action may be cancelled
3) alembic.commands.revision does not have parameter change version on create migration

I try to create empty migration file, parse it and set version to new, add migration lines after change version

**Comment by zzzeek** [comment]
> > it's so hard for me to answer questions that are asked like this, that's a row from an autogenerate there's no "transaction" there, can you please try to provide a complete example of what you are doing?
> 
> I have 3 troubles:
> 
>     1. I would like to create enums on postgresql, but autogeneratescript raise Error
> sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedObject) type "UnitMultiplier" does not exist
> LINE 7:  _payment_multiplier "UnitMultiplier", 


do it like this, we're using https://docs.sqlalchemy.org/en/13/core/type_basics.html?highlight=create#sqlalchemy.types.Enum.create and https://alembic.sqlalchemy.org/en/latest/ops.html?highlight=get_bind#alembic.operations.Operations.get_bind:

```
e1 = sa.Enum('y', 'z', 'a', 'f', 'p', 'n', 'micro', 'm', 'c', 'd', 'none', 'da', 'h', 'k', 'M', 'G', 'T', 'P', 'E', 'Z', 'Y', name='UnitMultiplier')
e2 = sa.Enum('AED', 'AFN', 'ALL', 'AMD', 'ANG', 'AOA', 'ARS', 'AUD', 'AWG', 'AZN', 'BAM', 'BBD', 'BDT', 'BGN', 'BHD', 'BIF', 'BMD', 'BND', 'BOB', 'BOV', 'BRL', 'BSD', 'BTN', 'BWP', 'BYR', 'BZD', 'CAD', 'CDF', 'CHF', 'CLF', 'CLP', 'CNY', 'COP', 'COU', 'CRC', 'CUC', 'CUP', 'CVE', 'CZK', 'DJF', 'DKK', 'DOP', 'DZD', 'EEK', 'EGP', 'ERN', 'ETB', 'EUR', 'FJD', 'FKP', 'GBP', 'GEL', 'GHS', 'GIP', 'GMD', 'GNF', 'GTQ', 'GYD', 'HKD', 'HNL', 'HRK', 'HTG', 'HUF', 'IDR', 'ILS', 'INR', 'IQD', 'IRR', 'ISK', 'JMD', 'JOD', 'JPY', 'KES', 'KGS', 'KHR', 'KMF', 'KPW', 'KRW', 'KWD', 'KYD', 'KZT', 'LAK', 'LBP', 'LKR', 'LRD', 'LSL', 'LTL', 'LVL', 'LYD', 'MAD', 'MDL', 'MGA', 'MKD', 'MMK', 'MNT', 'MOP', 'MRO', 'MUR', 'MVR', 'MWK', 'MXN', 'MYR', 'MZN', 'NAD', 'NGN', 'NIO', 'NOK', 'NPR', 'NZD', 'OMR', 'PAB', 'PEN', 'PGK', 'PHP', 'PKR', 'PLN', 'PYG', 'QAR', 'RON', 'RSD', 'RUB', 'RWF', 'SAR', 'SBD', 'SCR', 'SDG', 'SEK', 'SGD', 'SHP', 'SLL', 'SOS', 'SRD', 'STD', 'SYP', 'SZL', 'THB', 'TJS', 'TMT', 'TND', 'TOP', 'TRY', 'TTD', 'TWD', 'TZS', 'UAH', 'UGX', 'USD', 'UYU', 'UZS', 'VEF', 'VND', 'VUV', 'WST', 'XAF', 'XCD', 'XOF', 'XPF', 'YER', 'ZAR', 'ZMK', 'ZWL', name='Currency')

e1.create(op.get_bind())
e2.create(op.get_bind())

op.create_table('accesspermit',
    sa.Column('mRID', ekra_sql_orm.scripts.base.UUID(), nullable=False),
    sa.Column('applicationNumber', sa.String(), nullable=True),
    sa.Column('effectiveDate', sa.Date(), nullable=True),
    sa.Column('expirationDate', sa.Date(), nullable=True),
    sa.Column('_payment_multiplier', e1, nullable=True),
    sa.Column('_payment_unit', e2, nullable=True),
    sa.Column('_payment_value', sa.Float(), nullable=True),
    sa.Column('permitID', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['mRID'], ['workdocument.mRID'], ),
    sa.PrimaryKeyConstraint('mRID'))

```

> ```
> 
>     1. alembic.commands.revision trigger Flash watch script and action may be cancelled

OK, and, whats the issue ?  Postgresql uses transactional DDL so if the script is cancelled the changes would be rolled back.

> 
>     2. alembic.commands.revision does not have parameter change version on create migration

are you looking for `--rev-id` ?   `alembic revision -m "newrev" --rev-id=my_revision_ident`

> 
> 
> I try to create empty migration file, parse it and set version to new, add migration lines after change version

for the enum part of this, that is correct, since autogenerate doesnt do the CREATE for the enum these need to be added manually.   see https://alembic.sqlalchemy.org/en/latest/autogenerate.html#what-does-autogenerate-detect-and-what-does-it-not-detect for a discussion of what autogenerate can and cannot do, although ENUM is something it *should* do at some point.

**Comment by mrquokka** [comment]
> do it like this, we're using https://docs.sqlalchemy.org/en/13/core/type_basics.html?highlight=create#sqlalchemy.types.Enum.create and https://alembic.sqlalchemy.org/en/latest/ops.html?highlight=get_bind#alembic.operations.Operations.get_bind:

yeap, i know. But autogenerate script does not try to do it authomaticly, i have ~ 300 enums and list of them may be changed. I try to create interface that can create new/ alter exists enums.


> OK, and, whats the issue ? Postgresql uses transactional DDL so if the script is cancelled the changes would be rolled back.

But i need to apply transaction now, not after another restart

> are you looking for `--rev-id` ? `alembic revision -m "newrev" --rev-id=my_revision_ident`
I looking boolean that can change current version to new revision without execute generated file

**Comment by zzzeek** [comment]
again I have no idea what that means.  a "relation" in Postgresql is what it calls a "table", above code is trying to create an ENUM which has nothing to do with tables.   I don't know where this decorator runs or what the stack trace is or anything else like that.

**Comment by mrquokka** [comment]
> again I have no idea what that means. a "relation" in Postgresql is what it calls a "table", above code is trying to create an ENUM which has nothing to do with tables. I don't know where this decorator runs or what the stack trace is or anything else like that.

https://docs.sqlalchemy.org/en/13/orm/extensions/declarative/basic_use.html
relation - is a table.
autogenerate script is alphabetically, and create now. If child class comes before parent it will raise exception, because cannot create link to parent(parent is not exists)

About previous script - copy old sqlalchemy.Column function, override them, before call check enum exists, if it is not exists, create it, and run native sqlalchemy.Column

**Comment by zzzeek** [comment]
I think you should use [autogenerate rewriters](https://alembic.sqlalchemy.org/en/latest/api/autogenerate.html?highlight=rewriter#autogen-rewriter) here, scan the Table objects that are in the autogenerate body and then pull out each Enum you care about and insert "enum.create(op.get_bind())" as a code object, then have it all render directly.   Having that enormous amount of code hardcoded into all your migration files will not be maintainable.

See https://alembic.sqlalchemy.org/en/latest/api/autogenerate.html#autogenerating-custom-operation-directives for a complete example of how to add new features to autogenerate.

**Comment by mrquokka** [comment]
> I think you should use [autogenerate rewriters](https://alembic.sqlalchemy.org/en/latest/api/autogenerate.html?highlight=rewriter#autogen-rewriter) here, scan the Table objects that are in the autogenerate body and then pull out each Enum you care about and insert "enum.create(op.get_bind())" as a code object, then have it all render directly. Having that enormous amount of code hardcoded into all your migration files will not be maintainable.
> 
> See https://alembic.sqlalchemy.org/en/latest/api/autogenerate.html#autogenerating-custom-operation-directives for a complete example of how to add new features to autogenerate.

That's maybe help, but why it is don't apply automaticly?

**Comment by zzzeek** [comment]
> 
> That's maybe help, but why it is don't apply automaticly?

are you asking why is #278 open ?  because nobody is willing to work on it.

**Comment by mrquokka** [comment]
> > That's maybe help, but why it is don't apply automaticly?
> 
> are you asking why is #278 open ? because nobody is willing to work on it.

My bad, sorry, i will close this thread
