### ISSUE TITLE
Choose how generated migrations are indented

### ISSUE THREAD

**Issue by Thf772** [sqlalchemy/alembic#577]
By default, autogeneration of Alembic migrations produces scripts indented with 4 spaces. Although it is recommended by PEP 8, sometimes a project's guidelines or a programmer's own habits will call for another indentation scheme.

> Many projects have their own coding style guidelines. In the event of any conflicts, such project-specific guides take precedence for that project. - [PEP 8 Introduction](https://www.python.org/dev/peps/pep-0008/#introduction)

I suggest adding the possibility for Alembic users to define the character(s) to be used for indentation, perhaps as an argument to the `context.configure` function called in the default `env.py`.

Examples:

```python
    # Indenting with 4 spaces (PEP 8, should be the default):
    context.configure(
        ...
        indent = "    ",
    )
```
```python
    # Indenting with tabs:
    context.configure(
        ...
        indent = "\t",
    )
```
```python
    # Indenting with 2 spaces:
    context.configure(
        ...
        indent = "  ",
    )
```

Indentation is a touchy subject among our community: let us be wise, by being tolerant.

**Comment by zzzeek** [comment]
hi there -

is there a code formatter that formats your code in the way you wish?  these will be [pluggable](https://github.com/sqlalchemy/alembic/issues/307).

I'm -1 on an explicit option to set the indentation character specifically, that is too tiny of an option in an area that would be better off being much more generalized.

**Comment by sqla-tester** [comment]
**Mike Waites** has proposed a fix for this issue in the **master** branch:

**Provide revision post-write hooks** https://gerrit.sqlalchemy.org/1060

**Comment by zzzeek** [comment]
the docs in  51b3072 include an example of how to rewrite spaces into tabs.
