### ISSUE TITLE
Redundant foreign keys during autogenerate

### ISSUE THREAD

**Issue by vinvinod** [sqlalchemy/alembic#585]
This is somewhat related to #519 except that the table names are in Title case.

Repeated execution of `alembic revision --autogenerate` then `alembic upgrade head` is continuously dropping all the existing foreign keys and regenerating them.

These are the versions:
SQLAlchemy - 1.3.5
Alembic - 1.0.11
MySQL - 5.7
PyMySQL - 0.9.3

```python
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import MetaData
from sqlalchemy.schema import Column, ForeignKey
from sqlalchemy.types import CHAR, VARCHAR

convention = {
  "ix": 'ix_%(column_0_label)s',
  "uq": "uq_%(table_name)s_%(column_0_name)s",
  "ck": "ck_%(table_name)s_%(constraint_name)s",
  "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
  "pk": "pk_%(table_name)s"
}
meta = MetaData(naming_convention=convention)
Base = declarative_base(metadata=meta)

class Table1(Base):
	__tablename__ = "Table1"
	id = Column(CHAR(36), primary_key=True)
	name = Column(VARCHAR(255))

class Table2(Base):
	__tablename__ = "Table2"
	id = Column(CHAR(36), primary_key=True)
	name = Column(VARCHAR(255), unique=True)
	table1_id = Column(CHAR(36), ForeignKey("Table1.id"))
```

I find that it is happening due to mismatch in signature calculation. 

https://github.com/sqlalchemy/alembic/blob/f723827c82dfdb1145f3c73a88ad61bda1ca8d7f/alembic/autogenerate/compare.py#L997-L998

At the lines above, here are the signatures in my tests:

For `conn_fk_by_sig`:
`(None, 'Table2', ('table1_id',), None, 'table1', ('id',), None, None, 'not deferrable')`

For `metadata_fks_by_sig`:
`(None, 'Table2', ('table1_id',), None, 'Table1', ('id',), None, None, 'not deferrable')`

Notice that the difference is only in the case of the referred table (`table1` and `Table1`). 

When I edited [the class](https://github.com/sqlalchemy/alembic/blob/f723827c82dfdb1145f3c73a88ad61bda1ca8d7f/alembic/autogenerate/compare.py#L384)(`_fk_constraint_sig`) to convert all referred table names to lowercase, it worked fine.

How can I fix this?

**Comment by zzzeek** [comment]
haven't run it yet but so far looks a whole lot like github.com/sqlalchemy/sqlalchemy/issues/4344, so perhaps some MySQL 5.7 has the issue also but this seems unlikely, MySQL 5.7 what exactly?  Can you run ``mysql -e "select @@version"`` please?

**Comment by zzzeek** [comment]
the issue does not reproduce for me using your metadata as given and on MySQL 5.7.26.  The special logic for https://bugs.mysql.com/bug.php?id=88718 is not invoked.  I get identical sigs adding a print statement to that spot:

```
CONN FK SIGS: {(None, 'Table2', ('table1_id',), None, 'Table1', ('id',), None, None, 'not deferrable'): <alembic.autogenerate.compare._fk_constraint_sig object at 0x7f165deca208>}
MT FK SIGS: {(None, 'Table2', ('table1_id',), None, 'Table1', ('id',), None, None, 'not deferrable'): <alembic.autogenerate.compare._fk_constraint_sig object at 0x7f165deca0b8>}

```

so need to know all about your MySQL version, is it from a specific distribution and maybe has dist-specific patches, or custom built, or something like that.

**Comment by zzzeek** [comment]
Oh also, OS platform in use!   MySQL's casing is totally different for OSX, Windows, where I cannot test as easily

**Comment by zzzeek** [comment]
please show output for:

    mysql -e "show variables like 'lower_case_table_names'" 

if you are on windows or OSX I'm going to say you should not be using uppercase names.  MySQL does not have reasonable behavior in this area.

**Comment by vinvinod** [comment]
I am on OSX:

```
mysql> show variables like 'lower_case_table_names';
+------------------------+-------+
| Variable_name          | Value |
+------------------------+-------+
| lower_case_table_names | 2     |
+------------------------+-------+
1 row in set (0.00 sec)

mysql> select @@version;
+-----------+
| @@version |
+-----------+
| 8.0.12    |
+-----------+
1 row in set (0.00 sec)
```

First I saw the issue in 8. Then I thought I switched from 8 to 5.7 ! I was wrong 🤦‍♂️

I just verified that this issue is not there in 5.7. Signatures are identical. Thanks.

I will be running this in 5.7 on a debian as well. Can I use uppercase there?

**Comment by zzzeek** [comment]
you don't get the issue on 5.7 and lower_case_table_names is still set to 2 ?  OK, I think there may be a SQLAlchemy bug with this as well, because the "correct for issue 88718" logic might not be doing the right thing for case convention #2 from what I am looking at, but it is not easy to get a test against this.

**Comment by zzzeek** [comment]
this will be handled by https://github.com/sqlalchemy/sqlalchemy/issues/4751 .

**Comment by zzzeek** [comment]
this is a new MySQL issue that I've reported at https://bugs.mysql.com/bug.php?id=96365
