### ISSUE TITLE
Alembic upgrade/downgrade one engine

### ISSUE THREAD

**Issue by anthony0bondar** [sqlalchemy/alembic#586]
Hello.

I need to perform alembic upgrade/downgrade only on one specific db_engine.

I have alembic which was INITed from multidb template. At the moment I have 4 db_engines listed in alembic.ini

I want be able to upgrade/downgrade only specific db_engine For example:
`alembic upgrade *db_engine1* head
`
That means that I'll run migration only on db_engine1, not on db_engine2.

**Comment by zzzeek** [comment]
you want to adapt the "-x" argument to accept your engine name as given.    See the example at https://alembic.sqlalchemy.org/en/latest/api/runtime.html?highlight=configure#alembic.runtime.environment.EnvironmentContext.get_x_argument.

I can show you something more specific if you need more help.

**Comment by zzzeek** [comment]
hope that worked!
