### ISSUE TITLE
Template in .ini for ScriptDirectory.from_config doesn't translate to windows paths

### ISSUE THREAD

**Issue by bubthegreat** [sqlalchemy/alembic#590]
When using the %(here)s/dir format for a script location, the expectation is that alembic should translate this pathing to an OS friendly format for me if needed.  It does not.

Example - in alembic.ini I have the following script_location:
```
[alembic]
# path to migration scripts
script_location = %(here)s/alembic
```
With this code pulling the config:
```
from alembic.config import Config as AlembicConfig
from alembic.script import ScriptDirectory

config_file = 'C:\\Users\\bubth\\Development\\PykuMUD\\src\\pykumud\\alembic.ini'
config = AlembicConfig(config_file)
script = ScriptDirectory.from_config(config)
```
And this directory structure:
```
'C:\\Users\\bubth\\Development\\PykuMUD\\src\\pykumud\\alembic\\env.py',
'C:\\Users\\bubth\\Development\\PykuMUD\\src\\pykumud\\alembic\\script.py.mako',
 'C:\\Users\\bubth\\Development\\PykuMUD\\src\\pykumud\\alembic\\versions',
```
Expectation:
`C:\\Users\\bubth\\Development\\PykuMUD\\src\\pykumud\\alembic`

Result:
`C:\\Users\\bubth\\Development\\PykuMUD\\src\\pykumud/alembic`

**Comment by bubthegreat** [comment]
It seems like the simplest solution to this is to implement os.path.normpath() on any paths we pull from the .ini file.

**Comment by zzzeek** [comment]
OK, I don't understand this issue.    when you say, "Expectation:", "Result:", where is that "result" coming from ?  I don't see you calling upon any API feature that would make use of this path without it being normalized.    When the ScriptDirectory makes use of this path, it uses the _version_locations attribute exclusively, which runs all paths through os.path.abspath(), which [implies normpath](https://docs.python.org/2/library/os.path.html#os.path.abspath).  So I don't know where you are seeing this non-normalized path coming from.

Need information on how to reproduce, thanks!

**Comment by sqla-tester** [comment]
**Mike Bayer** referenced this issue:

**Add test for normalization of script_dir, version_locations** https://gerrit.sqlalchemy.org/1470

**Comment by zzzeek** [comment]
OK I don't have enough info to make any change here.
