### ISSUE TITLE
remove python setup.py test

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/alembic#592]
references:

https://github.com/sqlalchemy/sqlalchemy/issues/4789

pypa/setuptools#1684

pytest-dev/pytest#5546

**Comment by zzzeek** [comment]
we forgot to remove test_requires

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Remove tests_require** https://gerrit.sqlalchemy.org/1475
