### ISSUE TITLE
Allow preserve comment on column rename in MySQL

### ISSUE THREAD

**Issue by randallpittman** [sqlalchemy/alembic#594]
**Versions:**
Python: 3.7.4 (Linux/x64/conda)
Alembic: 1.0.11
SQLAlchemy: 1.3.5
MariaDB: 10.3.13

**Steps to reproduce**

1. Have a table `storage_drive` with Integer column `drive_partition`, nullable, and comment `If more than one partition, the 1-based partition index.`
2. In alembic `upgrade()` migration function, issue the following command to change the column name to `partition_`:
```python
op.alter_column(
    "storage_drive",
    "drive_partition",
    existing_type=sa.Integer(),
    existing_comment="If more than one partition, the 1-based partition index.",
    new_column_name="partition_",
)
```

**Expected Result:**
Column is renamed to `partition_` and the comment is preserved.

**Actual Result:**
Column is renamed to `partition_` and the comment disappears.

**Investigation**

* I used my interactive debugger to step through the `alter_table` command, and eventually got to `alembic/ddl/mysql.py` line 47.
* Since `name is not None` evaluated to `True` , the call to `MySQLChangeColumn` at line 51 was executed.
* Notably, this call does _not_ include the `comment` keyword argument (vs. the `MySQLModifyColumn` call at line 77), so `existing_comment` was dropped.

**Workaround**
Add another `alter_column` call to reinstate the comment.
```python
op.alter_column(
    "storage_drive",
    "partition_",
    existing_type=sa.Integer(),
    comment="If more than one partition, the 1-based partition index.",
)
```

**Comment by randallpittman** [comment]
Note: In MySQL, the following two commands:

```sql
ALTER TABLE storage_drive CHANGE drive_partition partition_ INTEGER NULL;
ALTER TABLE storage_drive MODIFY partition_ INTEGER NULL COMMENT 'If more than one partition, the 1-based partition index.';
```

Can be combined into one:

```sql
ALTER TABLE storage_drive CHANGE drive_partition partition_ INTEGER NULL COMMENT 'If more than one partition, the 1-based partition index.';
```

**Comment by randallpittman** [comment]
Really, I'd think preserving comments would be default behavior, but it isn't default behavior in the database so I can see why it isn't default in alembic.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Include existing_comment in MySQLChangeColumn** https://gerrit.sqlalchemy.org/1431

**Comment by zzzeek** [comment]
Can you confirm this patch solves your issue:

```diff
diff --git a/alembic/ddl/mysql.py b/alembic/ddl/mysql.py
index 17ae2de..e919599 100644
--- a/alembic/ddl/mysql.py
+++ b/alembic/ddl/mysql.py
@@ -64,6 +64,9 @@ class MySQLImpl(DefaultImpl):
                     autoincrement=autoincrement
                     if autoincrement is not None
                     else existing_autoincrement,
+                    comment=comment
+                    if comment is not False
+                    else existing_comment,
                 )
             )
         elif (

```
