### ISSUE TITLE
--sql option does not generate SQL with the correct dialect

### ISSUE THREAD

**Issue by darwinyip** [sqlalchemy/alembic#597]
Redshift has keywords such as `sortkey` and `interleaved` which are provided by `sqlalchemy-redshift`.
When running `alembic upgrade head`, the generated SQL is correct with all the dialect's features. However when running `alembic upgrade head --sql`, the SQL generated is generic and does not contain the dialect specific keywords.

**Comment by zzzeek** [comment]
this is likely a dupe of #518 and this is a known issue.

**Comment by zzzeek** [comment]
OK this is not autogenerate you're referring towards.    this is just offline SQL mode.   are you using the correct dialect for --sql ?   if the correct DDL renders in online mode, it should render in offline mode as well.

**Comment by zzzeek** [comment]
can't reproduce:

alembic.ini contains:

   sqlalchemy.url = redshift+psycopg2://

migration contains:

```
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('foo',
    sa.Column('x', sa.Integer(), nullable=True),
    redshift_sortkey="bar"
    )
    # ### end Alembic commands ###

```

output:

```
INFO  [alembic.runtime.migration] Context impl RedshiftImpl.
INFO  [alembic.runtime.migration] Generating static SQL
INFO  [alembic.runtime.migration] Will assume transactional DDL.
BEGIN;

CREATE TABLE alembic_version (
    version_num VARCHAR(32) NOT NULL, 
    CONSTRAINT alembic_version_pkc PRIMARY KEY (version_num)
);

INFO  [alembic.runtime.migration] Running upgrade  -> efa7e407eb7b, rev1
-- Running upgrade  -> efa7e407eb7b

CREATE TABLE foo (
    x INTEGER
) SORTKEY (bar);

INSERT INTO alembic_version (version_num) VALUES ('efa7e407eb7b');

COMMIT;

```

do you see the correct impl being used when you run?

**Comment by darwinyip** [comment]
That was the issue. Closing.
