### ISSUE TITLE
Detect whether Alembic is running

### ISSUE THREAD

**Issue by decaz** [sqlalchemy/alembic#599]
I have a couple of event listeners configured for SQLAlchemy but I don't want to be them running during Alembic operations. I tried to put environment variable within `env.py` and use it when registering SA hooks but `env.py` runs after it. How can I properly detect whether Alembic is running and not register SA hooks? Maybe it is worth putting special environment variable by Alembic itself?

**Comment by decaz** [comment]
Easy but not the best fix: `'alembic' in sys.argv[0]`.

**Comment by zzzeek** [comment]
>  I tried to put environment variable within `env.py` and use it when registering SA hooks but `env.py` runs after it. 

that is strange because Alembic doesn't know anything about your application until your env.py imports it.   this is the part you'd want to get working.

> How can I properly detect whether Alembic is running and not register SA hooks? Maybe it is worth putting special environment variable by Alembic itself?

env.py is the first thing that should be running before your other code is imported, unless you've written a custom frontend, in which case you'd do your thing there.

**Comment by decaz** [comment]
Yes, it seems like the reason is because in the beginning of the `env.py` I have imports of my table classes. But I need them and they cannot be defined without SA which activates event listeners. It can be worked around by putting environment variable in `env.py` before such imports but it looks pretty ugly..

**Comment by zzzeek** [comment]
we should look then at what these event handlers are exactly and how you are setting them up.

options include:

1. set event handlers on specific objects, like engines, not classes, like Engine

2. have the events fire off but check a boolean within them if they should fire or not

3. set state on specific objects that you want the events to fire off for

4. set up the event handlers in a function, not at the import level, like:
```

def setup_handlers():
    @event.listens_for(...)
    def my_event(...)

if should_setup_handlers is True:
    setup_handlers()
```

5. have the handlers set up only if a certain variable is *true*, which you set up where your application normally runs from, that is, dont set the flag in env.py, set it in whatever_is_not_env.py

6. have a function to remove the event handelrs and call that in env.py

that's a bunch of options, I think option 1 is likely the best place to start

**Comment by decaz** [comment]
Early I used 5th option but now refactored it to the 1st option. Thanks!
