### ISSUE TITLE
autogenerate doesn't handle uppercase table and field names for MySql/MariaDB on Windows

### ISSUE THREAD

**Issue by pe2mbs** [sqlalchemy/alembic#604]
When using sqlite lowercase and uppercase identifiers are allowed. When then switching to another database like MySQL / MariaDB it generates to drop all tables and re-create them, even that there are no actual differences. The difference is that the database engine on Windows sets all identifier names to lower case. This seems to be also applicable to Oracle database. 
We like to have the database identifier names in uppercase. That thay are in lower case in the database it self is not a problem as the database engine converts everything to lowercase itself.

alembic should be able to handle/compare uppercase/lowercase identifiers as the same for specific database engines.

**Comment by zzzeek** [comment]
hi there-

unfortunately I do not believe there is any action alembic or SQLAlchemy can take here, the simple fact is that MySQL on windows has limited functionality as far as case sensitivity.    using all UPPERCASE identifiers on databases is generally problematic, as an all-lower case name in SQLAlchemy will suggest case insensitive names, and you should definitely be using case insensitive names.

**Comment by zzzeek** [comment]
specifically this:

> We like to have the database identifier names in uppercase. That thay are in lower case in the database it self is not a problem 

this is a contradiction.   you said you want the database names in uppercase, then that they are in lower case is fine.    I think you mean you want the column names *in python* to be in uppercase.   That's the opposite of how SQLAlchemy works, SQLAlchemy considers an UPPERCASE table identifier to be case sensitive, it will quote it, and you will have these problems.

the correct way to have a certain kind of name in Python vs. the one in the database is to use the .key attribute of Column:

```
t = Table(
   "foo", metadata, 
  Column("id", Integer, key="ID")
  Column("data", String(50), key="DATA")
)

```
with a table as above, you can use UPPERCASE names in Python while maintaining case insensitivity in the database:

`   stmt = select([t.c.ID, t.c.DATA]).where(t.c.DATA == 'foo')
`
To reduce the verbosity, make yourself a column function that outputs columns in this way:
```

    def ins_column(name, *arg, **kw):
        kw['key'] = name.upper()
        return Column(name, *arg, **kw)


```

**Comment by pe2mbs** [comment]
Hi,

I'm using ORM and my table definition look something like this;
class TableClasee( db.Model ):
    __tablename__ =  "MY_TABLE"
    D_MT_ID = Column( Integer, autonumber = True, primary_key = True )
    D_MT_NAME = Column( String(50) )
    ...

How do I make SQLalechmy/alembic case insensitive ?

**Comment by zzzeek** [comment]
> Hi,
> 
> I'm using ORM and my table definition look something like this;
> 
> > class TableClasee( db.Model ):
> > > **tablename** =  "MY_TABLE"
> > > D_MT_ID = Column( Integer, autoincrement = True, primary_key = True )
> > > D_MT_NAME = Column( String(50) )
> > > ...
> 
> How do I make SQLalchemy/alembic case insensitive ?

the most straightforward, though verbose, way, is to define the names explicitly:

```
class A(Base):
    __tablename__ = 'a'

    D_MT_ID = Column("d_mt_id", Integer, primary_key=True)
    D_MT_NAME = Column("d_mt_name", String)

```

for a more automated approach you can use an attachment event:

```
Base = declarative_base()

from sqlalchemy import event

@event.listens_for(Column, "before_parent_attach")
def _rename_column(column, table):
    if table.metadata is Base.metadata:
        column.name = column.name.lower()
        # can also set column.key here if desired

class A(Base):
    __tablename__ = 'a'

    D_MT_ID = Column(Integer, primary_key=True)
    D_MT_NAME = Column(String)

```

**Comment by pe2mbs** [comment]
Aha great,

And i assume i can to something similar for the table name, right?
I have never used events in SQLAlchemy, so from the documentation i understand  

@event.listens_for(Table, "before_parent_attach")
def _rename_column(table, parent):
    if parent.metadata is Base.metadata:
        table.name = table.name.lower()
        # can also set column.key here if desired

But what is the parent of the Table instance ?

**Comment by zzzeek** [comment]
the parent of the table is MetaData but the name of the table is explicit in any case, under `__tablename__`, so that is distinct from your classname and you don't need any event for that.   if you are trying to make `__tablename__` automatic then use the example at https://docs.sqlalchemy.org/en/13/orm/extensions/declarative/mixins.html#mixin-and-custom-base-classes
