### ISSUE TITLE
`sqlachemy.url` required in ini file even though docmentation says it isn't

### ISSUE THREAD

**Issue by silky** [sqlalchemy/alembic#606]
from [here](https://alembic.sqlalchemy.org/en/latest/tutorial.html#the-migration-environment):

![image](https://user-images.githubusercontent.com/129525/66089276-f1d18600-e5c1-11e9-8a78-5e14eac4abbd.png)

great, so i changed `env.py` to be like so:

```
    url = os.getenv("DB_CONNECTION_STRING")
```
instead of

```
    url = config.get_main_option("sqlalchemy.url")
```

i get the following error running `alembic current`

```
  ...
  File "alembic/env.py", line 64, in run_migrations_online
    poolclass=pool.NullPool,
  File "/home/noon/tools/miniconda3/envs/proj/lib/python3.6/site-packages/sqlalchemy/engine/__init__.py", line 477, in engine_from_config
    url = options.pop("url")
KeyError: 'url'
```

**Comment by silky** [comment]
a terrible hack is just to change ` run_migrations_online` like so:

```
def run_migrations_online():
    """Run migrations in 'online' mode.

    In this scenario we need to create an Engine
    and associate a connection with the context.

    """
    config_section = config.get_section(config.config_ini_section)
    url = os.getenv("DB_CONNECTION_STRING")
    config_section["sqlalchemy.url"] = url
    connectable = engine_from_config(
        config_section,
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    with connectable.connect() as connection:
        context.configure(
            connection=connection, target_metadata=target_metadata
        )

        with context.begin_transaction():
            context.run_migrations()


```

as that's the function that has the implicit dependency on `url`.

**Comment by zzzeek** [comment]
hi there -

OK I guess the documentation here confused you in that you were looking for the explicit mention of the letters "url", you in fact have to change how the engine is acquired in *both* places in the file, in both the "run_migrations_offline()" function which is what's used when you run with `--sql`,  as well as "run_migrations_online()" which is when you run without `--sql`, e.g. live database.    if you look at the conditional at the bottom of env.py you can see that one or the other of these functions runs.    I can of course try to make that sentence less misteading in that there are two places the URL is referenced.   If you are new to SQLAlhemy then these common functions might not be familiar to you.

**Comment by zzzeek** [comment]
let me reword the sentence.

**Comment by silky** [comment]
thanks @zzzeek ! :)
