### ISSUE TITLE
Configuration file path from environment variable

### ISSUE THREAD

**Issue by p1c2u** [sqlalchemy/alembic#608]
It would be nice to have possibility to set config path with environment variables.

In my case this would be useful for running migrations in docker container. Environment variables are most common and easiest way to configure containers. That's why i would prefer to use `ALEMBIC_CONFIG` environment variable than `alembic -c ${ALEMBIC_CONFIG}` which is painful to pass such command.

It's similar like in `docker-compose` that you can specify compose file with `-f` option or with `COMPOSE_FILE` environment variable.

Here's my PR for this #607

**Comment by zzzeek** [comment]
mmm OK I know we see these "FOO_CONFIG" environment variables around but I'm asking on twitter because it's still not clicking for me what we really get from these..unless the command is in some kind of script you don't immediate control over

**Comment by zzzeek** [comment]
ok and our first tweet is folks putting it in .zshrc or something like that

**Comment by zzzeek** [comment]
OK I am in favor of ALEMBIC_CONFIG however I believe if someone passes -c on the command line, that should supersede ALEMBIC_CONFIG.

**Comment by zzzeek** [comment]
ping...I'm going to do the simpler patch I proposed if I don't hear from you

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Allow ALEMBIC_CONFIG for config file location** https://gerrit.sqlalchemy.org/1514
