### ISSUE TITLE
Allow creating `.sql` files for migrations

### ISSUE THREAD

**Issue by exhuma** [sqlalchemy/alembic#609]
Before using `alembic` I was using `sqlalchemy-migrate` and it had the option to write migrations [as SQL files](https://sqlalchemy-migrate.readthedocs.io/en/latest/versioning.html#writings-sql-scripts).

This was extremely useful for applications where you *know* that it will always be deployed on the same DBMS.

When you want to support multiple DB back-ends it's clear that writing Python scripts using the alembic operations is preferable. But in all of our current projects we aim for only one DB back-end. So portability is not an issue and writing SQL scripts is viable.

More importantly, writing SQL scripts is in many situations easier than using the API.

Is there any interest in supporting this in `alembic`? If yes, I'd also be willing to work on that if you give me a few tips/pointers where to begin.

**Comment by zzzeek** [comment]
also `--template` is already proposed at #581

**Comment by exhuma** [comment]
> [...] a pure SQL file would not be directly usable since Alembic uses metadata inside the file to track it, and would need to have some kind of special markup at the top [...]

Did not think about this and I am fine with the recommendation of just opening the SQL file.
