### ISSUE TITLE
Postgres tests failing

### ISSUE THREAD

**Issue by seperman** [sqlalchemy/alembic#610]
Hello,

I cloned the repo, switched to `rel_1_2_0` and followed the instructions in `README.unittests.rst`. Then manually installed the dependencies that I found in tox.ini and setup.py

```
apipkg==1.5
Mako==1.1.0
mock==3.0.5
psycopg2==2.8.3
pyparsing==2.4.2
pytest==5.2.1
pytest-xdist==1.30.0
python-dateutil==2.8.0
python-editor==1.0.4
SQLAlchemy==1.3.10
```

Postgres version: `PostgreSQL 10.10`

When running `pytest -n 4 --db my_postgresql`, I get `93 failed, 923 passed, 276 skipped, 12 error`

Example tests that fail:

```
PGUniqueIndexTest_postgresql+psycopg2_10_10.test_uq_dropped
AssertionError: 'remove_table' != 'remove_constraint'
```

A bunch of tests are failing because `psycopg2.errors.InvalidSchemaName: schema "test_schema" does not exist` but nowhere in the docs it says how to create that test_schema. All I see is that there is a `test_schema.db` in .gitignore.

If you want, I can make a PR to address these in the docs but first I need to know how to even get it running!

**Comment by zzzeek** [comment]
The first part of README.unitests.rst is wrong, you no longer can run "python setup.py test".  You should just run "tox" by itself.  this creates a venv, installs everything you need, and will run against SQLite.

To run against Postgresql, README.unittests.rst explains that two additional schemas must be created, "test_schema" and "test_schema_2".   the database that you run against as the primary database also has to be entirely empty of any existing tables, the readme seems to not mention that so I suppose I thought that would be obvious at some point.

**Comment by zzzeek** [comment]
I've updated those points in the README.

**Comment by seperman** [comment]
Thank you!
