### ISSUE TITLE
Create database if not exists.

### ISSUE THREAD

**Issue by am17torres** [sqlalchemy/alembic#614]
I'm using the multi-database configuration and I'm  wondering if alembic is able to create new databases as they are added to the `databases` section in `alembic.ini`.

```ini
[alembic]
# path to migration scripts
script_location = ./db

databases = engine1, engine2  # do I need to manage this out of band from the migrations?

[engine1]
sqlalchemy.url = driver://user:pass@localhost/dbname

[engine2]
sqlalchemy.url = driver://user:pass@localhost/dbname2
```

**Comment by zzzeek** [comment]
hi there -

Alembic doesn't do anything with "CREATE DATABASE", that part is normally run by the database administrator manually, or as part of your software install / build system if you are using something like that (e.g. ansible, docker, puppet, shell scripts, etc).

you can also add this step to your env.py if you'd like, basically as env.py runs through engines, you can emit "CREATE DATABASE " based on what the URL says it should be.  you can parse the url using sqlalchemy.engine.url.make_url(url_string) then look at the "database" portion (if this is mysql or postgresql) and emit CREATE DATABASE from that given your "master" database connection.

**Comment by am17torres** [comment]
This is an awesome idea 👍 . Where might one define the "master" database connection?

**Comment by zzzeek** [comment]
probably in alembic.ini also!   you can read whatever values you like using the Config object.

if you get something going I will gladly add a recipe to the site that shows the basic idea.

**Comment by am17torres** [comment]
I ended up doing this which worked. 

```python
    for name in re.split(r",\s*", db_names):
        engines[name] = rec = {}
        rec["engine"] = engine = engine_from_config(
            context.config.get_section(name),
            prefix="sqlalchemy.",
            poolclass=pool.NullPool,
        )

        host_uri = re.sub(name + r"$", '', str(engine.url))
        if host_uri not in host_connections:
            host_connections[host_uri] = []

        host_connections[host_uri].append(name)

    for host, databases in host_connections.items():
        engine = create_engine(host)
        conn = engine.connect()
        try:
            for database in databases:
                logger.info(
                    "Ensuring database '%s' exists on host '%s'" % (database, host))
                # use connectionless execution
                conn.execute("CREATE DATABASE IF NOT EXISTS %s" % database)
        except Exception as ex:
            logger.error(ex)
        finally:
            conn.close()
```

The only nice to have feature I'm missing is supressing the warning if the database already exists.

**Comment by zzzeek** [comment]
so...this is mysql ?      that includes that you can connect to the host without the dbname at all, not always possible.

also you can do the URL like this:

```
>>> str_url = "mysql://scott:tiger@localhost/test"
>>> from sqlalchemy.engine.url import make_url
>>> url = make_url(str_url)
>>> import copy
>>> url_wo_host = copy.copy(url)
>>> url_wo_host.database = None
>>> print(url_wo_host)
mysql://scott:tiger@localhost

```
