### ISSUE TITLE
refelected argument in include_object hook get "False", while the table is already in database

### ISSUE THREAD

**Issue by Orenoid** [sqlalchemy/alembic#615]
I'm now using flask_migrate to manage my database, which has tables in it already, and I'm gonna need some of them.
So I use the include_object hook to ignore those existing tables or existing column in some of the tables. This works well before.
But after some changes on my project, the hook does not work well now. 
Even if I rollback the whole project to the initial version, drop the dev-database, create a new one with original data.  when I make migrations, it always create those existing table in the auto-generated migration file. And the "reflected" argument get "False" in the include_object hook function. 
I tried upgrading the database with those migrations, and it told me "table already exists".
Can somebody tell me how exactly the "reflected" argument would be "True" ?

**Comment by Orenoid** [comment]
env.py Code:
`
def include_object(object, name, type_, reflected, compare_to):
    return not reflected
`
`
def run_migrations_online():
    """Run migrations in 'online' mode.

    In this scenario we need to create an Engine
    and associate a connection with the context.

    """

    # this callback is used to prevent an auto-migration from being generated
    # when there are no changes to the schema
    # reference: http://alembic.zzzcomputing.com/en/latest/cookbook.html
    def process_revision_directives(context, revision, directives):
        if getattr(config.cmd_opts, "autogenerate", False):
            script = directives[0]
            if script.upgrade_ops.is_empty():
                directives[:] = []
                logger.info("No changes in schema detected.")

    connectable = engine_from_config(
        config.get_section(config.config_ini_section),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    with connectable.connect() as connection:
        context.configure(
            include_object=include_object,
            connection=connection,
            target_metadata=target_metadata,
            process_revision_directives=process_revision_directives,
            **current_app.extensions["migrate"].configure_args
        )

        with context.begin_transaction():
            context.run_migrations()
`
I'm quite sure it could work before.

**Comment by zzzeek** [comment]
im not sure what "before" and "After" refer to here, do you mean, different versions of your schema?    the "reflected" argument to include_object() is True if the object being passed in was acquired as the result of reflection from the database, and is not present in your model.  tables that you removed, columns that you removed, constraints, etc.  autogenerate sees all these things in the database and not your model where you removed them, so for all of these it calls include_object() with reflected=True.

**Comment by Orenoid** [comment]
> im not sure what "before" and "After" refer to here, do you mean, different versions of your schema?

Sorry, this might make the problem complicated. Let's now ignore the "before-after" problem, and treat it as a new project, which need to dealing with existing database.

Here is what I've done before I reply you:

1. drop the database and create a new one with original data, no alembic_version table in it.
2. clear the migration files in my project.
3. run the command to generate migration files.
4. The new generated version file shows that, in the upgrade() function, it create table for every sqlalchemy model (not sure how to name it ) in my project, no matter the table exists or not.

To be more expicitly, now I have: 
an entirely new model A, no corresponding table yet.
models B, C, having same table name and column definition for the table in db.
models D, F, with table existing, but not every column is defined in model class.
I was expecting that only table A should be created. But the migration just creates all of them. What's more, the columns in tables created in migration file, are exactly the same ones in my models.

I'm not sure if I have given enough infomation. Thanks in advance.

**Comment by Orenoid** [comment]
If I misunderstand the usage of "reflected" argument, what should I do in this situation, for "creating only table A"
