### ISSUE TITLE
Detect Foreign Tables (FDW)

### ISSUE THREAD

**Issue by EddyMM** [sqlalchemy/alembic#616]
`alembic revision --autogenerate ...` does not seem to detect foreign tables created using the [Postgres FDW](https://www.postgresql.org/docs/11/postgres-fdw.html)

Instead it proceeds to assume the foreign tables do not exist.
Is there a work-around you can recommend for now?

**Comment by EddyMM** [comment]
Using `including_schemas=True` as well as an `include_object` function in the configuration of the context solved my problem.

```
...
def include_object(object, name, type_, reflected, compare_to):
    if type_ == 'table' and \
            object.name in excluded_schemas:
        return False
    return True

...

context.configure(
            connection=connection,
            target_metadata=target_metadata,
            include_object=include_object,
            include_schemas=True
        )
```

**Comment by EddyMM** [comment]
A long term fix needed though.

**Comment by zzzeek** [comment]
I dont understand why the first comment is that it does not see foreign tables, and then the solution is to add include_schemas, which I assume is allowing them to be seen, and then an include_object which excludes them.   these two statements appear to contradict.


can you provide complete context for what it is you are trying to do ?  does your model have Table objects corresponding to these foreign tables, and if so why do they need to be excluded?    additionally it's not clear why the include_object hook is not sufficient as it is intended explicitly for the use case of excluding tables that one would not want included.

**Comment by EddyMM** [comment]
I'll add a bit more context.
I have database 1 and 2.

Database 1 has tables A, B, C
Database 2 has D, E

Database 1 uses D and E as foreign tables.

I am using Alembic + SQLAlchemy for the app server that uses database 1. I have modeled D and E in the app server and works okay with SQLAlchemy.
Attempts of running `alembic revision --autogenerate ...` however result in the migration script showing create statements for D and E on the upgrade() ... indicating that Alembic isn't recognizing the Foreign tables. 

You're right about the include_schemas vs include_object contradicting though. The `include_schemas=True` wasn't helping so I chose to exclude the models D and E using include_object. Should have removed the `include_schemas=True`.

**Comment by zzzeek** [comment]
OK so the best way to do this, assuming long term you only are running migrations in the single schema, is to leave include_schemas=False, and then for the separation of D, E, either use a separate MetaData object, or use include_object hook that excludes them.    If it were me I would just use a separate MetaData collection for tables that are outside of those that my application is actually maintaining.   The only thing that changes is that if you need ForeignKey() objects between the two metadatas, you can't use strings to refer to the other table, you need to put the real column object in there, like `ForeignKey(d_table.c.id)`.  However, I don't know if PostgreSQL's foreign tables thing lets you have foreign keys between the two databases in any case so this doesn't really matter.

multiple MetaData with declarative is achieved either by using two separate Base classes, or making an abstract declarative class that features the alternate metadata:

```
Base = declarative_base()

class ForeignDataBase(Base):
    __abstract__ = True
    metadata = MetaData()

class A(Base):
   ..

class B(Base):
  ...

class C(Base):
   ...

class D(ForeignDataBase):
   ...

class E(ForeignDataBase):
   ...

```

**Comment by EddyMM** [comment]
Alright, thanks. Decided to use the include_object hook to exclude them.
