### ISSUE TITLE
use_alter not generating ALTER instruction ==> Unable to resolve circular foreign key dependency

### ISSUE THREAD

**Issue by ptitoliv** [sqlalchemy/alembic#626]
Dear alembic community,

My application has a particular schema with a circular dependency between two tables. The SQLAlchemy documentation says that for resolving that issue, we must use use_alter when declaring the foreignkey.

I tried that option, but my issue is that when executing the upgrade operation, the ALTER instruction is not generated ==> I generated the SQL script using the offline mode (--sql parameter) and there is no ALTER directive generated.

Is it a bug or am i missing something ?

The class are described here : https://pastebin.com/UW1M2Ti3

My alembic version is 1.0.11 and I try to generate for mariadb 10.

Thanks for your analysis and answer.

**Comment by zzzeek** [comment]
this is a known issue #326 for which you'll have to work around for now by doing op.create_foreign_key() after the fact .

**Comment by zzzeek** [comment]
discussion can continue on #326.
