### ISSUE TITLE
Would migrations work when using Table function to define database tables. 

### ISSUE THREAD

**Issue by OdinTech3** [sqlalchemy/alembic#627]
Does alembic work with sqlalchemy approach of creating tables with the `Table` class instead of the `declarative_base`?

**Comment by zzzeek** [comment]
yes, alembic only deals with Table / MetaData collections and it knows nothing about the ORM or declarative base.    right here: https://alembic.sqlalchemy.org/en/latest/autogenerate.html where you see "Base.metadata", if you don't have a declarative base, then you'd just have, "metadata".

**Comment by OdinTech3** [comment]
So using `declarative_base()` or using Table to define your db model in sqlalchemy would not affect alembic. So if I had a db table like so

```python
AgentTable = Table(
    "agents",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("agent_id", String)
)
```

and I created the table using `metadata.create_all`  then a later realized i needed to add another column

```python
AgentTable = Table(
    "agents",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("agent_id", String),
    Column("agent_name", String)
)
```

Alembic would be able to create the migration in this kind of situation correct?

**Comment by zzzeek** [comment]
yes however it is awkward if you have already used metadata.create_all() to create your database, because this implies when someone checks out your application, they have to run two different kinds of programs to set up the database.

**Comment by OdinTech3** [comment]
I will stick with `metadata.create_all()` for creating tables then
