### ISSUE TITLE
How to refresh sqlalchemy connection?

### ISSUE THREAD

**Issue by kuba-lilz** [sqlalchemy/alembic#630]
We're using alembic not just for sql schema migrations, but also other data schema migrations, since it provides a convenient way to ensure migrations order.

When non-sql operations in our migration scripts take long time (say up of 10 minutes), at the end of migration alembic fails with `connection not available` message, e.g.
```
sqlalchemy.exc.OperationalError: (mysql.connector.errors.OperationalError) MySQL Connection not available.
[SQL: UPDATE alembic_version SET version_num='d8dd70cc0e5a' WHERE alembic_version.version_num = '8dca0a20feb5']
```

I believe the real problem is that sql connection that alembic established at the beginning of the upgrade session has gone stale by the time upgrade was finished and alembic tries to commit new version number to `alembic_version` table.

Is there some way to explicitly refresh the connection alembic uses to connect to a database, so we could avoid the problem above?

**Comment by zzzeek** [comment]
hi there -

I would suggest preventing the connection from timing out during an operation.   This is likely a driver-side thing and I would do is not use mysql.connector, and instead use PyMySQL or mysqlclient which are much more widely used and less buggy.  the database connection should not be dying in the middle of an actual operation.   the "stale connection" thing happens in MySQL when the connection is fully idle, but it should not be going away in the way you describe.

As for the answer, if the connection died in the middle of the operation, it is gone and an error raise is guaranteed. After the error raise, the connection will note that it is in "disconnected" state and it will re-connect on the next operation.     A way to automate this is to use the "pre-ping" feature documented at https://docs.sqlalchemy.org/en/13/core/pooling.html?highlight=pre_ping#disconnect-handling-pessimistic , however, that pre-ping only occurs when you checkout a new connection.  for MySQL this would be per -migration script, assuming its transaction per migration.

but first order of business is that a connection should absolutely not be going away when an actual operation is taking place.

**Comment by kuba-lilz** [comment]
Thank you for taking time to reply :)

> This is likely a driver-side thing and I would do is not use mysql.connector, and instead use PyMySQL or mysqlclient 

The world of python mysql connection libraries, with their similar names, is a bit confusing to me.
The exact library we are using now is `mysql-connector-python==8.0.16`. If there is a reason to choose a different library, I would be happy to hear about it.

> but first order of business is that a connection should absolutely not be going away when an actual operation is taking place.

I thought this isn't fully in hands of client though. If server decides to close the connection, because it didn't hear from client in 10 minutes (as client, for my case, was busying doing non-mysql migrations on large data), connection would go away. Am I wrong here?

(I control server and can set higher timeouts, but that's just moving stakes, rather than really addressing the problem)

I thought there might be a way of asking alembic (explicitly or implicitly) to reestablish a connection if it detects it dropped. But if connection dropped that means transaction failed, so it's not a simple matter of reconnecting and continuing from where we left off, right? Setting up alembic to use engine with `pool_pre_ping=True` option wouldn't solve that problem. And now that I look at it from transactions point of view I see it probably shouldn't try to - it's better to be explicit about failed transactions.

If there is no cleaner way around the issue, I'm ok with adding a periodic ping to database to keep connection alive during the non-mysql processing portion.

E.g. for server set to timeout connections after 10 seconds, here's a migration that fails:

```python
def upgrade():

    total_seconds = 15

    # Simulate some long running non-mysql operation
    for second in range(total_seconds):

        print("{}/{} Sleeping...".format(second, total_seconds))
        time.sleep(1)
```

If I add a ping once a second, as in:

```python
def upgrade():

    total_seconds = 15

    # Simulate some long running non-mysql operation
    for second in range(total_seconds):

        print("{}/{} Sleeping...".format(second, total_seconds))
        time.sleep(1)

        # Ping database to keep connection fresh
        alembic.context.get_bind().execute("SELECT 1 ;")
```

migration succeeds. Do you see a better approach?

> assuming its transaction per migration

On a side note - is it possible to split migration into a few transactions? I assume not, both because treating migrations as atomic is desired and because `env.py::run_migrations_online()` literally says:
```python
with alembic.context.begin_transaction():
    alembic.context.run_migrations()
```

**Comment by kuba-lilz** [comment]
I guess it's more correct to say - I could hack my way around transaction per migration behaviour by changing implementation of `env.py::run_migrations_online()` and creating transactions myself inside migration scripts, but I would be losing migrations atomicity - which I most likely don't want ^^

**Comment by zzzeek** [comment]
Hi there -

I just noted an important word in your original message, **non-sql**.  I apologize that I did not see this word as that changes the answer.   I am assuming this means something that is not making use of the connection at all while the transaction stays open.

Put simply, in an ideal case, you should be committing your transaction before this ten minute operation begins, returning the connection to the connection pool, and then starting a new transaction with a new pool procured from the pool after it completes.     I would not have an idle transaction open like that and in fact I wouldn't really consider it a good idea to have any significant non-sql operations occurring within the scope of schema migrations in any case.    Feel free to share what this ten-minute-long, non SQL operation is, as I would be seeking alternative architectures for having this be in the middle of a migration.

Assuming you aren't going for that, within an Alembic migration script, the API for checking in the connection and getting a new one are limited.     So an alternative approach is to force the transaction to commit, then invalidate the connection so it reconnects on the next usage:

    op.get_bind().execute("COMMIT")
    op.get_bind().invalidate()
    # run long operation

the connection should re-connect on the next use without an error being raised.


> The world of python mysql connection libraries, with their similar names, is a bit confusing to me.
> The exact library we are using now is `mysql-connector-python==8.0.16`. If there is a reason to choose a different library, I would be happy to hear about it.

the MySQL driver landscape is not confusing if you stick to the simple statement of "use mysqlclient or pymysql" :).

this still stands as mysql-connector is the source of a lot of problems (although probably not this one).   see the note at https://docs.sqlalchemy.org/en/13/dialects/mysql.html#module-sqlalchemy.dialects.mysql.mysqlconnector .

**Comment by kuba-lilz** [comment]
In our case most often the long running non-sql operation is moving files within azure blob storage.
This is for data that is split between sql table and azure blob storage, e.g. a Photo class that stores photo id, camera id and photoshoot time in sql, for easy querying, but image binary in azure storage:

```python
class Photo(BASE_PERSISTENCE_CLASS):
    """
    Photos ORM - maps to photos table
    """

    __tablename__ = "photos"

    id = sqlalchemy.Column(sqlalchemy.String(40), primary_key=True)
    camera_id = sqlalchemy.Column(sqlalchemy.String(40), sqlalchemy.ForeignKey('cameras.id'))
    datetime_in_utc = sqlalchemy.Column(sqlalchemy.DateTime(), nullable=False)

    def get_image(self, block_blob_service):

        blob_name = "{camera_id}/{shooting_datetime}.jpg".format(
            camera_id=self.camera_id,
            shooting_datetime=self.datetime_in_utc.strftime('some_format_here'))

        return utilities.get_image_from_azure_blob(
            block_blob_service, container_name='photos', blob_name=blob_name)
```

In above implementation binary data (jpg file) is saved in azure at path `{camera_id}/{shooting_datetime}.jpg`.
Say at some point we decide to move to `{camera_id}/{photo_id}.jpg` schema instead.

To do that we have to first copy over all the `{camera_id}/{shooting_datetime}.jpg` pictures to `{camera_id}/{camera_id}.jpg` path.

Migration for this would look something like this:

```python
def upgrade():

    # Fetch all photos orm objects
    # (in real code we create session a bit different, this is just a quick and dirty example)
    session = sqlalchemy.orm.sessionmaker(bind=bind)()
    photos = session.query(myapp.Photo).all()
    session.close()

    # Copy photos binaries from old path to new path.
    # Long running operation for x GBs of photos
    for photo in photos:

        old_path = "{camera_id}/{shooting_datetime}.jpg".format(
            photo.camera_id, 
            photo.datetime_in_utc.strftime('some_format_here'))

        new_path =  "{camera_id}/{photo_id}.jpg".format(photo.camera_id, photo.id)

        # In reality you need to do a bit more magic with azure storage to copy a file,
        # but the general idea holds
        block_blob_service.copy_blob(container="photos", old_path, new_path)
```

I totally understand that above usage is considered outside of scope of alembic's purpose.
But alembic provides a convenient way to assure schema version and perform migrations and I'm happy to use it for non-sql data over introducing more tools versioning method to keep track of. Alembic helps me keep everything tidy in one place :)

> the MySQL driver landscape is not confusing if you stick to the simple statement of "use mysqlclient or pymysql" :)

Clearly I have some more reading to do, thank you for the tip.

> Put simply, in an ideal case, you should be committing your transaction before this ten minute operation begins, returning the connection to the connection pool, and then starting a new transaction with a new pool procured from the pool after it completes.

Since default implementation of `env.py::run_migrations_online()` wraps migrations in transactions, not the other way round, I will probably try not to work with `multiple transactions in migration` ordering, but I see your point. In future, as binary data grows, migrations like above might take hours and not minutes, at which case I might indeed go this route.


```
op.get_bind().execute("COMMIT")
op.get_bind().invalidate()
# run long operation
```

Yaay, this is the solution I was looking for, no periodic ping necessary ^^
If I structure my migrations as following:
```
# read-only sql operations here
# ...

op.get_bind().execute("COMMIT")
op.get_bind().invalidate()

# long running, but idempotent, non-sql operations here
# ...

# possibly write mysql here, but preferably move this part to a separate migration
# ...
```
then I should be ok :)

Once again thank you for your comments, they were very helpful.
And to reiterate - I understand I'm somewhat abusing alembic for purpose it wasn't designed for, but to us it's a great tool for generic data schema versioning, not just sql schemas.
