### ISSUE TITLE
Tests do not pass on windows

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/alembic#632]
Under windows some tests of alembic fail.

The main reason for failures are 
- a Permission error `PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'scratch\\scripts\\foo.db'`, when setting up some tests with sqlite
- slash/backslash difference ` call('foobar\\versions') != call('foobar/versions')`
- newline with `\n` vs `\r\n`

This is mainly to let you know, I'm not sure if it feasible to ensure that the tests work also on windows, since I guess it's hard to setup a ci environment with windows

if this is the expect behavior it can be closed

**Comment by zzzeek** [comment]
it's not ideal and there are ways to fix these things, if....someone wants to work on them ! :) but no biggie. will leave open.

**Comment by zzzeek** [comment]
Need complete stack trace for "The process cannot access the file" error.  this should not be occurring.
