### ISSUE TITLE
Alembic CLI doesn't work in python 3.6 conda env

### ISSUE THREAD

**Issue by roemhildtg** [sqlalchemy/alembic#642]
None of the cli commands print or do anything in my python environment created with conda. Any tips for troubleshooting this? I can provide further information as needed, but I'm not currently sure where to start. 

Here's what a sample console transcript looks like:
```
(snowflakes) C:\Users\groemhildt\projects\wsb-inspections-sde-migrations>alembic init alembic

(snowflakes) C:\Users\groemhildt\projects\wsb-inspections-sde-migrations>alembic list_temmplates

(snowflakes) C:\Users\groemhildt\projects\wsb-inspections-sde-migrations>python --version
Python 3.6.8 :: Anaconda, Inc.

(snowflakes) C:\Users\groemhildt\projects\wsb-inspections-sde-migrations>
```
The commands don't have any errors and there are no messages printed. 

This particular conda env is a little bit special, it is the bundled one that comes with ArcGIS Pro, https://pro.arcgis.com/en/pro-app/arcpy/get-started/what-is-conda.htm, and I have cloned that one into a new env called `snowflakes`. 

System info:
Windows 10 x64
Python 3.6.8 
Conda 4.3.27

**Comment by zzzeek** [comment]
I dont't know anything about Conda. Does Conda package Alembic and if so can you look to them for support ?

**Comment by roemhildtg** [comment]
I can do that. Its so bizarre, I've never seen an issue like this before with python packages. I'll close this for now.

**Comment by zzzeek** [comment]
OK thanks, I hope they can help.    I dont' really know anything about what conda does.
