### ISSUE TITLE
Can this tool be used for non-python applications?

### ISSUE THREAD

**Issue by ShravanVarma** [sqlalchemy/alembic#649]
We have many applications under various languages(e.g PHP, Java, .Net) and wondering if we could use this tool without being language-dependent. I am trying to understand how much effort is needed for me to achieve that.

Thanks

**Comment by zzzeek** [comment]
You can use alembic in context with an application that runs in a different platform, sure, however if you want to use the "autogenerate" feature, you'd still need to have a set of Table metadata set up in Python.   Whether or not you have that, you can certainly have migration files that have ops inside of them, those migration files are of course written in Python but the operations apply just to the database, which can be consumed by any kind of application.

**Comment by zzzeek** [comment]
short answer you'd have some python code in your application but the existing php/.net whatever can just run without knowing about any of the python stuff.

**Comment by ShravanVarma** [comment]
I also want to use alembic for **Raw SQL queries only** so I will play around with this and see how it goes for different apps. Thanks
