### ISSUE TITLE
inspect.formatannotation is not docuemtned and should be vendored 

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/alembic#657]
see https://github.com/sqlalchemy/sqlalchemy/issues/5138

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Vendor inspect.formatannotation** https://gerrit.sqlalchemy.org/1713

**Comment by zzzeek** [comment]
note this does not actually affect things right now, the above user has a broken import.
