### ISSUE TITLE
There is no straight forward way to use the version_table_schema kwarg

### ISSUE THREAD

**Issue by MosheVai** [sqlalchemy/alembic#659]
I want to have the alembic_version table in the schema  named `'foo'` using `version_table_schema='foo'` for [`context.configure`][1] in `env.py`.

I tried to make a migration file, with this `update` function:

`    op.execute("create schema foo")`

However I run into a bit of a catch 22 situation as the schema is not yet created and alembic cant check what version its in. 

Is there no way to use the `version_table_schema` kwarg without manual intervention? do i need to have a separate `env.py` and versions folder to create the schema? 

  [1]: https://alembic.sqlalchemy.org/en/latest/api/runtime.html#alembic.runtime.environment.EnvironmentContext.configure

**Comment by zzzeek** [comment]
hi there -

if you want your alembic environment to automatically create the schema for which you want the alembic version table present, you need to create this in your env.py itself.  The creation of the "alembic_version" table itself occurs outside of the scope of running the actual migrations so the schema must also.

```
    def run_migrations_online():
        connectable = ...

        with connectable.connect() as connection:

            connection.execute("CREATE SCHEMA IF NOT EXISTS foo")

            context.configure(
                # ...
                compare_type=True,
                connection=connection, target_metadata=target_metadata
            )

            with context.begin_transaction():
                context.run_migrations()

```

**Comment by MosheVai** [comment]
Ohh, sounds nice, thanks. @zzzeek 
closing it.
