### ISSUE TITLE
downgrade from specific head when multiple heads are present?

### ISSUE THREAD

**Issue by eeshugerman** [sqlalchemy/alembic#660]
Say I have three revisions, two are heads, the other is a branchpoint:
```
    B
  /
A
  \
    C
```
Is there a way to rollback only `B` or only `C`?

If I do `alembic downgrade B-1` (or `C-1`), both B and C are rolled back (which _does_ make sense...).

As an aside, `alembic downgrade -1` rolls back one or the other, but I can't figure out what determines which gets rolled back -- when I try it, then do `upgrade heads`, then try it again, sometimes it will be different the second time.

**Comment by zzzeek** [comment]
can you take a look at #464 this sounds like the same thing.     no plans to work on that anytime soon unless someone is very motivated to help think about it.

**Comment by eeshugerman** [comment]
yep, that looks like the same ask, sorry for the duplicate.

**Comment by sqla-tester** [comment]
**Simon Bowly** has proposed a fix for this issue in the **master** branch:

**New downgrade algorithm to fix branch behaviour** https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/2530
