### ISSUE TITLE
more regressions with type comaprisons

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/alembic#671]
this comaprison should return no change, because "Unicode" is the generic type:
```

diff --git a/tests/test_autogen_diffs.py b/tests/test_autogen_diffs.py
index e1e5c8d..7fa4465 100644
--- a/tests/test_autogen_diffs.py
+++ b/tests/test_autogen_diffs.py
@@ -795,6 +795,8 @@ class CompareMetadataToInspectorTest(TestBase):
         (Unicode(32), VARCHAR(32), False, config.requirements.unicode_string),
         (VARCHAR(6), VARCHAR(12), True),
         (VARCHAR(6), String(12), True),
+        (mysql.VARCHAR(200, charset='utf8'), Unicode(200), False, ),
+        (String(255, collation='utf8_bin'), String(255), False)
     )
     def test_string_comparisons(self, cola, colb, expect_changes):
         is_(self._compare_columns(cola, colb), expect_changes)

```

**Comment by pbecotte** [comment]
Looks like you removed the config.requirements.mysql line from those two tests?

When I run it that way the VARCHAR/UNICODE test passes, but the String one fails with 

psycopg2.errors.UndefinedObject) collation "utf8_bin" for encoding "UTF8" does not exist
(sqlite3.OperationalError) no such collation sequence: utf8_bin

Are you getting a different result? I updated off of master and ran against postgres/mysql/oracl/sqlite

**Comment by zzzeek** [comment]
the version I just released should have those tests qualified with "mysql required", it passed on CI for all backends: https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/1802

i put the wrong change number into it,drat

**Comment by zzzeek** [comment]
tox -e py37-sqlite-postgresql-mysql -- tests/test_autogen_diffs.py 

passes for me from latest master....
