### ISSUE TITLE
What is messing with whitespace in revision scripts? Can it be disabled?

### ISSUE THREAD

**Issue by eeshugerman** [sqlalchemy/alembic#675]
If I add 
```
var = [1,2]
```
or
```
var = [1,         2]
```
anywhere in my `script.py.mako` and then run `alembic revision`,  this line becomes 
```
var = [1, 2]
```
in the resulting revision script.

Why? Can I disable this somehow?

I noticed this when attempting to pass in some carefully formatted Python code as a string with `template_args`.

Thanks!

**Comment by zzzeek** [comment]
that would only happen if you have a [code formatter](https://alembic.sqlalchemy.org/en/latest/autogenerate.html#applying-post-processing-and-python-code-formatters-to-generated-revisions) set up which is not the default mode of operation.  you'd need to disable that.

**Comment by eeshugerman** [comment]
Oh geeze :man_facepalming: I can't believe didn't realize that. I do have `black` enabled.

Thanks again!
