### ISSUE TITLE
Support for functional index

### ISSUE THREAD

**Issue by seperman** [sqlalchemy/alembic#676]
Currently functional indexes are skipped during autogeneration.
There is even a test for it:
https://github.com/sqlalchemy/alembic/blob/master/tests/test_autogen_indexes.py#L1172

```
            "Skipped unsupported reflection",
            "autogenerate skipping functional index",
```

Is this feature on the roadmap to be supported?

This ticket probably is a duplicate but I could not find the exact one searching in the tickets.
Thanks

**Comment by zzzeek** [comment]
this would be a deliverable for SQLAlchemy.  There's no roadmap for this feature however any contributor should feel free to set up an issue at github.com/sqlalchemy/sqlalchemy and work on this.

**Comment by zzzeek** [comment]
there would also be some integration work on the alembic side for comparison logic.

**Comment by AntonOfTheWoods** [comment]
@zzzeek , this seems to be partially supported under certain usecases, namely when an index is modified. 

Just messing around I found I got this generated, when I put `None` for my index name (which was actually creating a collision with another index... anyway!)

```
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_datable_from_lang', table_name='datable')
    op.create_index(op.f('ix_datable_from_lang'), 'datable', [sa.text("lower('source_text')"), 'from_lang', 'to_lang'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_datable_from_lang'), table_name='datable')
    op.create_index('ix_datable_from_lang', 'datable', ['from_lang'], unique=False)
    # ### end Alembic commands ###

```

Does that mean that sqlalchemy actually has support, or is that a red herring and support hasn't been implemented?

**Comment by CaselIT** [comment]
What sqlalchemy and alembic version are you using?
Sqlalchemy 2 added reflection for functional indexes, but they should still be ignored by alembic, so that seems a bug in the skil logic. Until alembic supports them the behaviour is undefined for that kind of indexes 

The issue that tracks support in alembic is https://github.com/sqlalchemy/alembic/issues/1098

**Comment by AntonOfTheWoods** [comment]
Perfect, thanks guys, I'm subscribed to that ticket now and now praying to the GitHub gods for SA 2.0 :-D.

**Comment by CaselIT** [comment]
It will be still a bit of time before rc1. Lots of things have changed in sqlalchemy v2 so it's best to move slowly.
Thanks for testing it, it's really helpful.

I'll check to see if we miss a skip index somewhere in alembic now that functional indexes are reflected
