### ISSUE TITLE
Add --version argument to cli

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/alembic#677]
I was looking for the alembic version in an env, and the cli does not seem to expose it.

There is special action of argparse for this. and is supported also in [python2](https://docs.python.org/2/library/argparse.html#action), so it should be fairly easy to add

**Comment by sqla-tester** [comment]
**CaselIT** has proposed a fix for this issue in the **master** branch:

**Add version to cli** https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/1844
