### ISSUE TITLE
[Question] - How to populate table with data, when running migrations ?

### ISSUE THREAD

**Issue by vjanz** [sqlalchemy/alembic#679]
Hello guys,
I am using alembic to make migrations, everything is working fine.

One of the tables from my database needs to be populated with data as long as the migrations run, so what I mean is, I have a CSV file, and I must populate the fields of x table from that csv file.

My question is: Is there a way to populate a specific table in database while running migrations.
Simply said when I run migrations for ex:alembic upgrade head, to create all the tables and db, but one of the tables to be pre-populated from a csv file?

Any help is appreciated..
Thank you in advance

**Comment by zzzeek** [comment]
sure, you can invoke any SQL you'd like in your migration file, and for bulk inserts of data there is a helper which is the bulk_insert method:  https://alembic.sqlalchemy.org/en/latest/ops.html?highlight=bulk_insert#alembic.operations.Operations.bulk_insert

but you can use any SQLAlchemy Core / ORM thing you want in a migration file too.

the reason data migrations are not always terrific in a migration file is that they are not always possible to reverse, and some environments also are trying to do "live" migrations which means in-file data migrations are not sufficient (applications keep writing old data), but certainly just for fixed data in a new table you're adding, bulk_insert is it.

**Comment by vjanz** [comment]
@zzzeek , thank you very much for quick response. I actually want to use ORM to add those data, since I have already write a function to do that operation. I ran it just for testing(pytest) and it worked with no problem. All I want is to integrate that function, in migration, so when the migration run, the tabels are populated with data just like in tests
So basically:
```
def add_data(db_session: ScopedSession):
    with db_session as db:
        with open('data.csv') as csv_file:
            csv_reader = csv.reader(csv_file, delimiter=',')
            line_count = 0
            for row in csv_reader:
                if line_count == 0:
                    line_count += 1
                    continue
                else:
                    record = Currency(**{
                        'id': int(row[0]),
                        'name': row[1],
                        'scale': int(row[3]),

                    })
                    db.add(record)
                    db.commit()
                    db.refresh(record)
```

**Comment by zzzeek** [comment]
the reason that can be a problem is that you want this migration to remain functional in perpetuity, and your ORM models may have changed so would no longer work in this migration once it's older.

that said if you have an approach for the ORM models, usually that you are setting upa model that's local to that migration, or you are making sure your ORM models will always work for this older migration, or you are rolling up old migrations, the Session itself you can set up on the current Alembic connection as session = Session(op.get_bind()), so it will occur on the same connection / transaction as your migration.

**Comment by vjanz** [comment]
@zzzeek this orm model, is not going to change after it's decided how it's going to be.
In general, other models will consume from this, but the data that I am trying to populate, for this model are not likely to change, they're more or less static.

**Comment by zzzeek** [comment]
should be good then
