### ISSUE TITLE
attributes['config_ini_section'] Always 'alembic' In Multiple Environment Case

### ISSUE THREAD

**Issue by smitty1eGH** [sqlalchemy/alembic#680]
Thank you for SQLAlchemy/Alembic. Version is 1.4.2

# 0. GOAL
SQLAlchemy/Alembic combination that supports unit testing against SQLite for the model,
then a set of migrations both to add production lookup data and to and dialect-specific Column flourishes, e.g. FULLTEXT. 
Initially seeking to leverage https://alembic.sqlalchemy.org/en/latest/cookbook.html#building-an-up-to-date-database-from-scratch
to get my SQLite memory-only base case working.

#============================================
# 1. This function at the top of my models.py:
...usual SQLAlchemy imports, followed by declarative model classes...
`meta = MetaData()`
`Base = declarative_base(metadata=meta)

`def create_all(db_engine, alembic_config_path):`
`    '''Generate this set of models using a database engine and prepare`
`         for usage with Alembic by adding a version_table.`
`    '''`
`    meta.create_all(db_engine)`
`    with db_engine.begin() as connection:`
`        alembic_cfg = Config(alembic_config_path)`
`        alembic_cfg.attributes['connection'] = connection`
`        alembic_cfg.attributes['config_ini_section'] = 'sqlite_memory' #LOOK_AT_ME`
`        command.stamp(alembic_cfg, "head")`

#============================================
# 2. ...fails this test:
`import pytest`
`from sqlalchemy.orm import Session`
`from sqlalchemy import create_engine`

`def test_hd_analytics():`
`    from nextngc.models import create_all`
`    engine = create_engine("sqlite://")`
`    create_all(engine, '/home/osboxes/proj/nextngc/nextngc/etc/alembic.ini')`

#============================================
# 3. ...with this trace:
tests/test_model1.py:15: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
nextngc/models.py:21: in create_all
    command.stamp(alembic_cfg, "head")
../lib/python3.8/site-packages/alembic/command.py:545: in stamp
    script = ScriptDirectory.from_config(config)
../lib/python3.8/site-packages/alembic/script/base.py:126: in from_config
    script_location = config.get_main_option("script_location")
../lib/python3.8/site-packages/alembic/config.py:293: in get_main_option
    return self.get_section_option(self.config_ini_section, name, default)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <alembic.config.Config object at 0x7f25c8fce820>, section = 'alembic', name = 'script_location', default = None

    def get_section_option(self, section, name, default=None):
        """Return an option from the given section of the .ini file.
    
        """
        if not self.file_config.has_section(section):
>           raise util.CommandError(
                "No config file %r found, or file has no "
                "'[%s]' section" % (self.config_file_name, section)
            )
E           alembic.util.exc.CommandError: No config file '/home/osboxes/proj/nextngc/nextngc/etc/alembic.ini' found, or file has no '[alembic]' section

#============================================
# 4. Digging, it looks like self.config_ini_section is not honoring my line above:

   alembic_cfg.attributes['config_ini_section'] = 'sqlite_memory' #LOOK_AT_ME

   ...on line 285. A hard-coded hack confirmed this. I am unsure the preferred place to  handle this apparent error, or I'd submit a PR.  
 
https://github.com/sqlalchemy/alembic/blob/master/alembic/config.py#L285

**Comment by zzzeek** [comment]
OK I think maybe the docs aren't clear here.   to set configuration options that Alembic itself is going to consume, you do it like this:

```
from alembic.config import Config
alembic_cfg = Config()
alembic_cfg.set_main_option("script_location", "myapp:migrations")
alembic_cfg.set_main_option("sqlalchemy.url", "postgresql://foo/bar")
alembic_cfg.set_section_option("mysection", "foo", "bar")

```

the part where you put things in config.attributes, that's used for things that *your own* env.py might like to see later.  however the .attributes dictionary is **separate** from the main configuration elements.   the set_main_option() / set_section_option() is populating a Python stdlib Config object which is under the .file_config attribute.

https://alembic.sqlalchemy.org/en/latest/api/config.html

**Comment by zzzeek** [comment]
I'm assuming this worked, feel free to close these when you're done
