### ISSUE TITLE
[Question] Creation of alembic_version Table When Building From Scratch

### ISSUE THREAD

**Issue by smitty1eGH** [sqlalchemy/alembic#682]
# 0. This is good

meta = MetaData()
Base = declarative_base(metadata=meta)

def create_all(db_engine, alembic_config_path):
    '''Generate this set of models using a database engine and prepare
         for usage with Alembic by adding a version_table.
    '''
    meta.create_all(db_engine)
    with db_engine.begin() as connection:
        alembic_cfg = Config(alembic_config_path)
        alembic_cfg.set_main_option("script_location", "alembic" )
        command.stamp(alembic_cfg, "head")

# 1. This is the test case
def test_hd_analytics():
    from nextngc.models import create_all
    engine = create_engine("sqlite://")
    create_all(engine, '/home/osboxes/proj/nextngc/nextngc/etc/alembic.ini')
    Session = sessionmaker(bind=engine)
    session = Session()
    conn  = session.connection()
    result = conn.execute('SELECT name FROM SQLITE_MASTER ORDER BY name DESC;')
    for row in result:
        print(row[0])

# 2. No alembic_version table
Working from https://alembic.sqlalchemy.org/en/latest/cookbook.html#building-an-up-to-date-database-from-scratch

I got everything in my models.py, but there is no alembic_version table, with or without purge=true in the command.stamp() invocation.

I also experimented with explicitly add an alembic_version table, per the code, with no joy.

The log output is as follows:
tests/test_model1.py db_names='sqlite_memory'
INFO  [alembic.env] Migrating database sqlite_memory
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running stamp_revision  -> 566653957210

I made sure there was no alembic/versions and alembic/versions/__pycache__ interference.

Please cluebat.

**Comment by zzzeek** [comment]
try not using a sqlite memory database, perhaps there are multiple engines getting used.   turn on SQL echoing and you should see the CREATE TABLE proceed.

**Comment by smitty1eGH** [comment]
This is good:
**def test_hd_analytics():
    from nextngc.models import create_all
    engine = create_engine("sqlite:///foo.db")
    create_all(engine, '/home/osboxes/proj/nextngc/nextngc/etc/alembic.ini')
    Session = sessionmaker(bind=engine)
    session = Session()
    conn  = session.connection()
    result = conn.execute('SELECT COUNT(*) FROM alembic_version;')
    for row in result:
        print(row[0])

I thought that the 'stamp' command was going to put 'head' in the version_num column.

tests/test_model1.py db_names='sqlite_memory'
INFO  [alembic.env] Migrating database sqlite_memory
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
0

Let me work on my data loading transition and see if that doesn't educate me.
Thank you so kindly.

**Comment by smitty1eGH** [comment]
** Using the  tmp_path fixture to drop a .db in /tmp just doesn't seem to be a workable. **

import os
import pytest
from sqlalchemy.orm import Session
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker

from nextngc.models import create_all

@pytest.fixture
def temp_db(tmp_path):
    try:
        os.makedirs(tmp_path)
    except:
        pass
    return 'sqlite:///' + str(tmp_path) + '/foo.db'

def test_hd_analytics(temp_db):
    engine = create_engine(temp_db)
    create_all(engine, '/home/osboxes/proj/nextngc/nextngc/etc/alembic.ini')
    Session = sessionmaker(bind=engine)
    session = Session()
    conn  = session.connection()
    result = conn.execute('SELECT COUNT(*) FROM alembic_version;')
    for row in result:
        print(row[0])

**Comment by smitty1eGH** [comment]
Looking at alembic.ini, I see my source of woe:

[sqlite_memory]
sqlalchemy.url = sqlite:///foo.db
script_location = alembic

#FirstDayNewEyes
