### ISSUE TITLE
Code docstring are missing from the online documentation

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/alembic#689]
The doc-strings in multiple parts of the code are not reported in the docs.

Example of this is the `alter_columns` documentation:
https://github.com/sqlalchemy/alembic/blob/d791c575e95614f53c282a9f22166646dc46b9a0/alembic/operations/ops.py#L1651-L1761
And this is what is generated in the docs intead
https://alembic.sqlalchemy.org/en/latest/api/operations.html?highlight=alter_columns#alembic.operations.ops.AlterColumnOp.alter_column

**Comment by zzzeek** [comment]
this is the docstinrg for the one is is displayed:

"This method is proxied on the Operations class, via the Operations.alter_column() method."

that's correct, but then the rest of it is not coming out so that is probably the zzzeeksphinx updates I made

**Comment by zzzeek** [comment]
except alembic is not using zzzeeksphinx...

**Comment by CaselIT** [comment]
Where is `"This method is proxied on the Operations class, via the Operations.alter_column() method."` added?

Maybe instead of appending the to the docstring it is replaced?

**Comment by zzzeek** [comment]
there's a missing "members" that seemed to not make a difference before and now it does, lets rebuild site

**Comment by CaselIT** [comment]
Seems easy enough.
If it fixes it, I'll look around if some other part is also missing.

**Comment by CaselIT** [comment]
How long does it usually takes for the website to update?

**Comment by zzzeek** [comment]
i built manually, so the thing that was broken for me is there now.  however, I think you still don't like how it displays anyway, which is that it shows a link to the docstring elsewhere.   that's a more complicated change but at the same time I wouldn't want the same docstirng in two places.  this is a bigger issue with the whole awkward way that Alembic monkeypatches this global "op" namespace and a better plan would be for us to just start working away from that whole architecture.

**Comment by zzzeek** [comment]
oh actually the link you have is towards the AlterColumnOp object itself, so that's another case where a method is pulled off of AlterColumnOp and moved into a different namespace, so...that's kind of how that part is.

**Comment by zzzeek** [comment]
this is the actual doc:

https://alembic.sqlalchemy.org/en/latest/ops.html#alembic.operations.Operations.alter_column

**Comment by CaselIT** [comment]
> i built manually, so the thing that was broken for me is there now

oh ok, I thought it was like sqlalchemy that deploys automatically

**Comment by CaselIT** [comment]
Maybe we can reopen this or create a new one?

**Comment by CaselIT** [comment]
I've built them offline and it work now 👍 

> his is a bigger issue with the whole awkward way that Alembic monkeypatches this global "op" namespace and a better plan would be for us to just start working away from that whole architecture.

Yes I think that it would help. Also to make alembic more pep484 friendly.
Maybe it could be an plan for alembic 2, but for after sqlalchemy 1.4 is out :)

**Comment by zzzeek** [comment]
well the thing you referred to in this issue is actually not that big monkeypatch thing, it's the fact that an operation like Operations.alter_column comes from the AlterColumnOp.alter_column() method.  This is not how things started with Alembic but in order to make the system extensible, all the XYZOp classes were added and that's how people can make new operations that become available on the Operations namespace.

I'm sure this all could have been done differently but it's probably not worth changing now as it works quite well.
