### ISSUE TITLE
Mark current revision in history output

### ISSUE THREAD

**Issue by ziima** [sqlalchemy/alembic#690]
It'd helpful if the history of revisions showed also a marker of a current revision of a database.

I suggest to print a `(current)` or similar marker in the history output to denote current revision of a database.

**Comment by zzzeek** [comment]
hi there -

please use -i or --indicate-current

```
usage: config.py history [-h] [-r REV_RANGE] [-v] [-i]

optional arguments:
  -h, --help            show this help message and exit
  -r REV_RANGE, --rev-range REV_RANGE
                        Specify a revision range; format is [start]:[end]
  -v, --verbose         Use more verbose output
  -i, --indicate-current
                        Indicate the current revision
alembic.config history -i
hi
<base> -> bc7e28ed1604 (head) (current), rev1

```

**Comment by ziima** [comment]
Thanks. Sorry, I didn't notice. Is there a reason, not to show current by default?

**Comment by zzzeek** [comment]
it requires hitting the database whereas plain history does not.

**Comment by ziima** [comment]
Got it. Thanks
