### ISSUE TITLE
set additional PRAGMA statements for sqlite

### ISSUE THREAD

**Issue by marcinkuzminski** [sqlalchemy/alembic#693]
**Describe your question**
Based on changed in sqlite (more info: https://github.com/django/django/pull/10733/commits/c8ffdbe514b55ff5c9a2b8cb8bbdf2d3978c188f)

I'd like to execute additionally PRAGMA legacy_alter_table = ON
Where would be a suitable place to do it?

I'm getting an error:

```
    raise exc.NoSuchTableError(table.name)
sqlalchemy.exc.NoSuchTableError: migration_tmp
```

While executing such migration:
```
    with op.batch_alter_table(repository.name) as batch_op:
        batch_op.execute('PRAGMA legacy_alter_table = ON') # this doesn't work here...
        repo_name_idx = 'r_repo_name_idx'
        if repo_name_idx in repo_name_indexes:
            batch_op.drop_index(repo_name_idx)
        for name in repo_name_constraints:
            if name:  # sqlite can have this empty, then it raises an error
                batch_op.drop_constraint(name, type_='unique')

        batch_op.alter_column(repo_name_column.name, type_=Text)
        batch_op.alter_column(clone_uri_column.name, type_=Text)
        batch_op.create_index('r_repo_name_idx', ['repo_name'], mysql_length=255)
        batch_op.add_column(Column('repo_name_hash', String(40), unique=False))
```

**Comment by zzzeek** [comment]
you would want to do this as soon as you connect inside your env.py and use the event hook as described at https://docs.sqlalchemy.org/en/13/dialects/sqlite.html#foreign-key-support so that it occurs immediately.

**Comment by marcinkuzminski** [comment]
Thanks, that did it. didn't knew the trick from the docs !
