### ISSUE TITLE
Using alembic.ini with pg8000 connect_args / ssl_context 

### ISSUE THREAD

**Issue by fbouliane** [sqlalchemy/alembic#696]
**Is your feature request related to a problem? Please describe.**
I had difficulty to pass the parameter "ssl_context" to pg8000 using alembic.ini
This stackoverflow suggest the right usage for sqlalchemy : https://stackoverflow.com/a/25095643
But the format in alembic.ini doesn't allow passing a dictionnary in the connect_args.
pg8000 driver doesn't take ssl_mode directly in the urlparams neither so this doesn't work.

The ssl_context allow me to connect to a ssl protected postgres database so it's kind of important.
The database wouldn't allow me without having this parameter set.

In order to make it work, I had to remove the usage of the alembic.ini altogether, use the python api to craft the sqlalchemy connection in my code and "pass it" to the migration engine, such as :
https://gist.github.com/fbouliane/32b08153c71b830a44de0289411f3622

The documentation being not explicit for such use case it was a little difficult to put in place. And I'm not sure this address the case when generating migration.

**Describe the solution you'd like**
Either of those solution would have helped:
- add documentation for such use case in a section associated to pg8000 of alembic.
- add a way to pass a dict to connect_args in alembic.ini
- a specific parameters for this is sqlalchemy / alembic.ini 

I have never participated in the sqlalchemy / alembic project, but I can probably do a documentation pull-request if instructed what we wish to be there. 

**Thanks for your time**

**Comment by CaselIT** [comment]
I believe that in this case you are supposed to edit these parts of the default `env.py` 
https://github.com/sqlalchemy/alembic/blob/e7453f14bc972f1206144f1155ea3dc52469ea95/alembic/templates/generic/env.py#L40
https://github.com/sqlalchemy/alembic/blob/e7453f14bc972f1206144f1155ea3dc52469ea95/alembic/templates/generic/env.py#L59-L65
so that is uses a different method for obtaining an url and the engine.

Some documentation regarding this can be found at
https://alembic.sqlalchemy.org/en/latest/tutorial.html#editing-the-ini-file in the `sqlalchemy.url` bullet.

Probably some commnets in the default `env.py` could be added regarding the possibility of obtaining the url/connection in some other way

**Comment by zzzeek** [comment]
> 
> In order to make it work, I had to remove the usage of the alembic.ini altogether, use the python api to craft the sqlalchemy connection in my code and "pass it" to the migration engine, such as :
> https://gist.github.com/fbouliane/32b08153c71b830a44de0289411f3622

OK that's way more effort than you need.  Simply adjust the env.py script in your environment to add these arguments when you invoke create_engine(), that's what env.py is there for, for programmatic adjustments to things.

also the ssl arguments can be added to the query string:

    sqlalchemy.url = postgresql+pg8000://user:pass@hostname/dbname?sslmode=require

this is docuemnted at https://docs.sqlalchemy.org/en/13/core/engines.html#custom-dbapi-connect-arguments

**Comment by fbouliane** [comment]
@CaselIT @zzzeek  sounds good for using in the `env.py` rather than overriding the whole thing.

> connectable = engine_from_config(..., connect_args={'ssl_context': True})

works fine.

@zzzeek just so if someone else tries that solution. 
When trying `?ssl_context=True`, I get the
`str' object has no attribute 'wrap_socket`` error because pg8000 expect either true / false or a sslcontext

https://github.com/tlocke/pg8000/blob/master/pg8000/core.py#L1163-L1168
The string "True" doesnt work there, it must be a bool so it's considered correctly.

Thanks for your help !

**Comment by zzzeek** [comment]
OK, there's a filter that can turn "True" into a boolean but that woudl require a change to pg8000.  this is sqlalchemy side in any case.
