### ISSUE TITLE
Does not add imports of external modules like geoalchemy2 in the migrations file

### ISSUE THREAD

**Issue by diptangsu** [sqlalchemy/alembic#703]
For a column in a model class like this,
```
from geoalchemy2 import Geography
import gino

db = gino.Gino()

class Table(db.Model):
    ...
    geom_point = db.Column(Geography(geometry_type='POINT', srid=4326))
```
This is the corresponding value in the migrations file generated using alembic.
```
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    ...
    op.create_table('crime_data',
    ...
    sa.Column('geom_point', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, from_text='ST_GeogFromText', name='geography'), nullable=True),
    )
    ...
```
However, it does not `import geoalchemy2` on top. It has to be manually added for the code to work, which is fine because it's a very simple change. But I guess this can be added as an improvement if not a bug.

I have not tried this with other external modules but this is the case with `geoalchemy2`.

**Comment by zzzeek** [comment]
hi there -

this is [documented](https://alembic.sqlalchemy.org/en/latest/autogenerate.html#controlling-the-module-prefix):

> The imports for the above type again must be made present within the migration, either manually, or by adding it to script.py.mako.

add the imports to your script.py.mako so that you don't have to type them repeatedly.

**Comment by diptangsu** [comment]
Oh. Okay. Thanks for pointing me in the right direction.
