### ISSUE TITLE
Downgrade programatically using command.downgrade

### ISSUE THREAD

**Issue by mmaelicke** [sqlalchemy/alembic#705]
**Describe your question**

Similar to #603 I want to run a migration downgrade programmatically like:

```python
al_config = Config()
command.downgrade(al_config, '-1')
```
The revision script is *not* autogenerated and the `env.py` contains an `Engine` object connecting a test (PostgreSQL) database. 
When running the CLI, everything works as expected, but running the downgrade like shown above, the same revision on the same database runs into a table lock, whenever the revision drops a foreign key column. 

I feel like I am missing something, while trying to mimic the CLI downgrade command. Do you have an idea, why the `command.downgrade` and `alembic downgrade` could behave differently, or point me to the implementation of the downgrade (CLI) command, so I can check myself?

**Additional context**
I am running the `command.downgrade` inside a CI  `pytest` against a test database to check whether a new revision screws something up that is not reflected by my development database. I already tried to call the alembic CLI via subprocess in the `pytest` function, but I run into the very same table lock problem.

I already changed the `poolclass` in `create_engine` to `NullPool`. Other than using default pool I get some output from alembic, before the table lock occurs:

```
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running downgrade d9b539aa0f56 -> dce6a45a0786
```
Whereas without the usage of `NullPool`, there is no output at all. However `pg_stat_activity` shows me that there is a table lock by the connection used by alembic on the table where I want to drop a foreign key column and the `Alter table ...  drop column...` query is blocked.

**Have a nice day!**
Thank you and you too! And thanks for this excellent tool

**Comment by zzzeek** [comment]
is this a test suite?   is the alembic downgrade being run in the test itself or in like a teardown method?  basically any connection that was used to emit SQL queries on the table in question will place locks on it in PG that prevent it from being migrated in ways that would interact with that statement's selected objects.

this is not really related to downgrading or whatever it has to do with how you are setting up engines, how you are getting connections and emitting queries and how you are ensuring those connections are returned to the pool before going to the next step.

pg_stat_activity is showing you what tables have locks, however I would assume pg_stat_activity is showing you *two* separate database sessions, otherwise there would be no lock contention.  is that the case?  and if so, can you identify the source of the pre-existing session in your code?   you basically have to remove things until you can see the operation in question open up.

**Comment by mmaelicke** [comment]
Thanks for the quick reply.
So in this use case, the downgrade *is* the test. Basically, the code example is wrapped by a pytest function and that's it. I am writing a lot of db revisions right now and the test suite downgrades a clean install of the project, to check if the revision is screwing something else up. Up to now, I did that by hand running the downgrade by `alembic downgrade -1`, which works perfectly fine. 
So my initial intention was to ask whether there are some differences between `command.downgrade(..., '-1')` and `alembic downgrade -1` because I read the docs like the CLI is wrapping `command` and so I just went for it. 

Concerning the table lock, I am still trying to understand what is going on. I do not get consistent behavior from the test suite, which is weird. The other session (which is obviously there) is an idle sequence update that has nothing to do with the revised tables (there are no constraints that could possibly lock the table, I think). I still have to look into this.

My issue was intended as a question concerning the different behavior between `command.downgrade` and `alembic downgrade`, because I cannot see how they would affect table locks differently unless I am missing something. I couldn't find the CLI implementation in the alembic code to check how it is calling `command` myself.

**Comment by zzzeek** [comment]
the CLI implementation basically calls command.downgrade() directly, the command.downgrade Python function is sitting inside of the argparse structure that alembic's CLI uses.  code for that is in alembic/config.py at https://github.com/sqlalchemy/alembic/blob/master/alembic/config.py#L552

**Comment by mmaelicke** [comment]
Thanks for pointing out. 
I rebuild the [`main` function](https://github.com/sqlalchemy/alembic/blob/69e65b6d4ec959548689484edf617fd81b4f384c/alembic/config.py#L563) and everything works as expected as CLI, but not inside a test. I will stick to my manual tests as they work as expected and maybe come back to this at some other point in time. It still does not really make sense to me, but never mind.
Thanks for pointing me to the CLI implementation, that was already really helpful. Thanks for your help and I'll close the issue, as I expect it not to be related to alembic, but related to me having wrong assumptions about the way alembic handles transactions or something like that, at the end of the day.
