### ISSUE TITLE
mssql_drop_foreign_key generates statement that raises pyodbc.ProgrammingError (Incorrect syntax near '`')

### ISSUE THREAD

**Issue by Nuqlear** [sqlalchemy/alembic#716]
**Describe the bug**
```py
op.drop_column("assignment", "employee_profile_id", mssql_drop_foreign_key=True)
```
This line is [generating the following statement](https://github.com/sqlalchemy/alembic/blob/52ef05c936170109f2f457751f4940e4269595c3/alembic/ddl/mssql.py#L200):
```sql
declare @const_name varchar(256)
select @const_name = [name] from
sys.foreign_keys fk join sys.foreign_key_columns fkc
on fk.object_id=fkc.constraint_object_id
where fkc.parent_object_id = object_id('assignment')
`and col_name(fkc.parent_object_id, fkc.parent_column_id) = 'employee_profile_id'
exec('alter table assignment drop constraint ' + @const_name)
```
which leads to pyodbc.ProgrammingError:
```
pyodbc.ProgrammingError: ('42000', "[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Incorrect syntax near '`'. (102) (SQLExecDirectW)")
```
**Expected behavior**
Foreign key dropped alongside column without errors.

**Versions.**
 - OS: Ubuntu 18.04
 - Python: 3.7.4
 - Alembic: 1.4.2
 - SQLAlchemy: 1.3.14
 - Database: Azure SQL Server
 - DBAPI: pyodbc==4.0.30

**Comment by CaselIT** [comment]
Strange. Seems to be a typo introduced in https://github.com/sqlalchemy/alembic/commit/6e3079526635092c748d33e897bfcdf5482eecc8.

**Comment by CaselIT** [comment]
@gordthompson I'm not familiar sql server, do backticks ('`') have a particular meaning in it?

**Comment by sqla-tester** [comment]
**Oleg Shigorin** has proposed a fix for this issue in the **master** branch:

**Fixes #716. Remove typo in _exec_drop_col_fk_constraint** https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/2105

**Comment by gordthompson** [comment]
> 
> 
> @gordthompson I'm not familiar sql server, do backticks (`` ` ``) have a particular meaning in it?

AFAIK, no.

**Comment by CaselIT** [comment]
thanks, should be a typo then.

**Comment by zzzeek** [comment]
how did this ever work?  user at https://github.com/sqlalchemy/alembic/issues/621#issuecomment-553261001 maybe didnt actually run this part?

**Comment by sqla-tester** [comment]
**Oleg Shigorin** has proposed a fix for this issue in the **master** branch:

**Remove typo in _exec_drop_col_fk_constraint** https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/2105
