### ISSUE TITLE
Alembic Audit Log Table

### ISSUE THREAD

**Issue by claweyenuk** [sqlalchemy/alembic#718]
**Is your feature request related to a problem? Please describe.**
I noticed a one-off issue that I suspect could have happened if the server was not shut down during a migration and it wrote some data mid-migration. I was wondering when a particular migration happened in the past and if it coincides with the issue. Unfortunately, there are no logs with that information.

**Describe the solution you'd like**
I think it would be nice if there was a table in the DB, say `alembic_history`, that had a date & a from/to version. This could track when `stamp` is used or when `upgrade`/`downgrade` is used, and perhaps success/failure in case a migration fails.

**Describe alternatives you've considered**
Logging to file and storing that somewhere shared. It's possible, but storing in the database seems natural too.

**Additional context**
None.

**Have a nice day!**

**Comment by zzzeek** [comment]
hi there -

this is #309 .  if you have more specific ideas as to how this feature should work, adding specifics to that issue would be helpful.    it currently lacks developer interest so if people were interested in helping to make it happen, that would help.

**Comment by claweyenuk** [comment]
Thank you, I completely missed that.

I will keep it in mind, I don't have a great record of getting projects like this done, but if I can gather some time together I will take a stab.
