### ISSUE TITLE
Not detecting a Postgres VARCHAR changing to TEXT

### ISSUE THREAD

**Issue by TMiguelT** [sqlalchemy/alembic#719]
**Describe the bug**
Despite having enabled the type checking feature, this particular type change doesn't seem to be detected

**Expected behavior**
Ideally altering a table from `Column(String(80))` to `Column(Unicode)` should be detected, generating `op.alter_column(..., _type=Unicode)`

**To Reproduce**
1. Use Postgres
2. Initially the model should be
```
class User(db.Model, CRUDMixin):
    __tablename__ = 'users'
    user_id = Column(Integer, primary_key=True)
    username = Column(String(80, convert_unicode=True), unique=True, nullable=False)
```
3. Create a new autogenerated migration
4. Change the model to
```
class User(db.Model, CRUDMixin):
    __tablename__ = 'users'
    user_id = Column(Integer, primary_key=True)
    username = Column(Unicode, unique=True, nullable=False)
```
5. Create a new autogenerated migration. At this point, this change will not be included in the migration

**Versions.**
 - OS: Ubuntu 18.04
 - Python: 3.6.9
 - Alembic: 1.4.0
 - SQLAlchemy: 1.3.13
 - Database: Postgres 9.5.6
 - DBAPI: psycopg2-binary==2.8.5

**Comment by zzzeek** [comment]
hi -

do you mean `UnicodeText` ?   `Unicode` and `String` both generate VARCHAR.

**Comment by zzzeek** [comment]
I can confirm changing from String(50) to UnicodeText() works.  The reason String(50) to Unicode() generates nothing is because alembic's type comparison logic is still trying to err on the side of no false positives, and since Unicode() is basically String(None), it assumes this datatype is simply not as specific as the one in the database and that there should be no change.  if you used Unicode(100), that change in length would be detected.  But you can use UnicodeText() and that's actually the TEXT type (internally they are all the same on Postgresql as you likely know) and that gets detected.

**Comment by TMiguelT** [comment]
Ah, I see your point, `Unicode()` isn't a very good type definition since it should either have a length or be `UnicodeText()`. I think the code I'm working on *meant* the latter, but I can't do much about that now (I wonder why `length=None` is even allowed in SQLAlchemy?).

The problem here, though, is that I think a `Unicode()` column in plain SQLAlchemy maps to `TEXT` in postgres while `Unicode(80)` maps to VARCHAR(80). So changing the table definition _is_ actually a functional change, but alembic is treating it as non-functional. Considering this, is it still reasonable to err on the side of no false positives? Or at least, in the future should there be a config flag to toggle this sensitivity?

Anyway, thanks for the answer.

**Comment by zzzeek** [comment]
length is optional for PostgreSQL's VARCHAR.  you can say just VARCHAR and that's what length=None does:

```
>>> from sqlalchemy import Unicode
>>> from sqlalchemy.dialects import postgresql
>>> print(Unicode().compile(dialect=postgresql.dialect()))
VARCHAR

```

**Comment by TMiguelT** [comment]
Okay yep, this seems like very reasonable behaviour. I'm convinced this isn't a problem with `alembic`, it's a problem with the person who wrote the code I'm working on and believed that they changing to `String(80)` to `Unicode()` was equivalent to changing `VARCHAR` to `TEXT` in raw SQL, which it isn't.

**Comment by chidioguejiofor** [comment]
@multimeric  I don't think `String(80) and TEXT are the same. One has a max_length of 80(internally represented as VARCHAR(80)) and the TEXT doesn't have a max length.

I sort of experienced the same thing while using flask and PostgreSQL. I changed my type from `String(21)` to `Text` but it was not detected when generating migrations. 

I was able to fix this by generating a migration file( using `flask db revision`) with the following code:

```python 

def upgrade():
    op.alter_column("Message", "text", type_=sa.TEXT)


def downgrade():
    op.alter_column("Message", "text", type_=sa.VARCHAR(length=21))
```

Changes the text column of the Message table from VARCHAR(21) to TEXT.

**Comment by Olegt0rr** [comment]
the same bug
`String(255) -> Text` not detected

**Comment by zzzeek** [comment]
> the same bug `String(255) -> Text` not detected

definitely works with correct configuration.  just tried it again to make sure, here's a sample

```py
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "test",
        "name",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.Text(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###

```

**Comment by zzzeek** [comment]
yes compare_type=True would be it, and this only applies to run_migrations_online.  offline does not do database reflection

**Comment by karolpawlowski** [comment]
Thanks @zzzeek
