### ISSUE TITLE
setup.cfg / pyproject.toml Support

### ISSUE THREAD

**Issue by webartifex** [sqlalchemy/alembic#720]
Is it reasonable to add support for storing the alembic configuration in a setup.cfg or pyproject.toml file?

**Comment by zzzeek** [comment]
hi this is #708.    I'm personally -1 on it because pyproject.toml is part of the application's source code management,  whereas alembic.ini concerns deployment of the application itself.   that is, putting a database URL in pyproject.toml is like hardcoding it in a .py file IMO.

**Comment by zzzeek** [comment]
please pick this up at #708
