### ISSUE TITLE
Alembic doesn't change the version table name when using a custom alembic environment

### ISSUE THREAD

**Issue by vitaly-krugl** [sqlalchemy/alembic#722]
**Describe the bug**
My app uses the Airflow packages which has its own alembic configuration. My app also needs to manage the version history for the app's own tables separately from Airflow's in the same database. When I follow instructions in https://alembic.sqlalchemy.org/en/latest/cookbook.html#run-multiple-alembic-environments-from-one-ini-file and use a custom environment name via `alembic --name my_app_env upgrade head`, I get this error: 
```FAILED: Can't locate revision identified by 'a66efa278eea'``` and see from the logs that Alembic was still using the version table name "alembic_version" instead of basing the version table name on the custom environment supplied via the `--name` arg:
```
2020-08-06 22:17:08,873 INFO sqlalchemy.engine.base.Engine {'name': 'alembic_version'}
INFO  [sqlalchemy.engine.base.Engine] {'name': 'alembic_version'}
2020-08-06 22:17:08,888 INFO sqlalchemy.engine.base.Engine SELECT alembic_version.version_num 
FROM alembic_version
INFO  [sqlalchemy.engine.base.Engine] SELECT alembic_version.version_num 
FROM alembic_version
```

**Expected behavior**
I expected Alembic to use the custom environment name supplied via the `--name` arg as the base for naming the version table. For example, if I pass `--name my_app_env`, then I expected the new version table to be named something like `my_app_env_alembic_version`.

**To Reproduce**
Follow the steps included in **Describe the bug** section.

**Error**

```
FAILED: Can't locate revision identified by 'a66efa278eea'
```

**Versions.**
 - OS: Linux 4.19.76-linuxkit x86_64
 - Python: Python 3.8.3
 - Alembic: 1.4.2
 - SQLAlchemy: 1.3.18
 - Database: postgres:10.11
 - DBAPI: psycopg2 2.8.4

**Comment by zzzeek** [comment]
hi there -

the "--name" option does not make the assumption that each configurational section refers to the same schema in the same database and was originally intended to refer to different databases altogether, where each database would have the expected "alembic_version" table.   

in your case, you are using the --name argument for multiple sections in the same database, so differently-named alembic_version tables are required.  However, it is not the SQLAlchemy/Alembic way to hardcode naming conventions into the library, instead you are encouraged to create your own conventions based on your specific needs.   Within alembic this is the purpose of the `env.py` file which is present in your alembic environment and allows programmatic construction of pretty much any scenario.

In this case, the "--name" argument is accessible at runtime via the [config_ini_section](https://alembic.sqlalchemy.org/en/latest/api/config.html?highlight=config_ini_section#alembic.config.Config.config_ini_section) config attribute, and the version table name is controlled by the [version_table](https://alembic.sqlalchemy.org/en/latest/api/runtime.html?highlight=version_table#alembic.runtime.environment.EnvironmentContext.configure.params.version_table) parameter.   So in env.py inside of run_migraions_online() you would see:

```
def run_migrations_online():

    # ...

    with connectable.connect() as connection:

        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            version_table="alembic_version_%s" % config.config_ini_section,
            # ...
        )

        with context.begin_transaction():
            context.run_migrations()

```

**Comment by vitaly-krugl** [comment]
Thanks @zzzeek - The `context.configure(version_table=...)` recommendation worked out for me. I'm closing the issue.

**Comment by lafrech** [comment]
I'm designing an app with a plugin interface. Plugins may define tables in the same DB and may use alembic for their own migrations.

I faced the same issue. Passing a different alembic version table name in each plugin does solve the issue. I hardcode the name in the plugin env.py:

```py
# Prefix used in all plugin table names. Each plugin should have a different prefix.
PLUGIN_PREFIX = "p_feature"
VERSION_TABLE = f"{PLUGIN_PREFIX}_alembic_version"

    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            process_revision_directives=process_revision_directives,
            version_table=VERSION_TABLE,
        )
```

When autogenerating a migration, alembic keeps the core application tables (since these are imported in the plugin model) but unfortunately, it also tries to drop the alembic version table from the core app.

To prevent this, I added an `include_name` callable:

```py
def include_name(name, type_, parent_names):
    if type_ == "table":
        # Don't drop tables that are unknown in the model... unless these are really tables dropped from the plugin.
        return (name in target_metadata.tables) or name.startswith(PLUGIN_PREFIX)
    return True

    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            include_name=include_name,
            process_revision_directives=process_revision_directives,
            version_table=VERSION_TABLE,
        )
```

The condition in `include_name` is derived from https://alembic.sqlalchemy.org/en/latest/autogenerate.html#omitting-table-names-from-the-autogenerate-process except IIUC, this recipe does not allow dropping tables that are actually removed from the model, hence my addition with the prefix.

Not sure it is the best solution, but I thought it might be worth sharing.
