### ISSUE TITLE
Question about multiple bases and dependencies

### ISSUE THREAD

**Issue by Wim-De-Clercq** [sqlalchemy/alembic#725]
**Describe your question**
Imagine `base1` has revisions **A** --> **B** --> **C**
Imagine `base2` has just revision **B'**

The **B'** depends on **B**.
But the **C** revision does a change which would break applying **B'**.

I can make an `alembic upgrade` work if I do:
```
alembic upgrade base2@head
Executes: A, B, B'
alembic upgrade base1@head
Executes: C
```
This, however, requires people who do the alembic upgrade to have specific knowledge of which branch to do when, which I would like to avoid. Imagine if there are more than 2 bases, the set of instructions to execute gets complicated quickly.

By default `alembic upgrade heads` would execute `A, B, C, B'` which wouldn't work.
Is there something I can declare on **B'** to have priority to run right after **B**, before **C** to make this work?

**Comment by zzzeek** [comment]
this is a use case for the [branch dependencies](https://alembic.sqlalchemy.org/en/latest/branches.html#branch-dependencies) feature .  Using the depends_on attribute of a migration, you would establish that B' is dependent on B, and that C is dependent on B'.

this should in theory allow a single "upgrade heads" to do the right thing.

**Comment by Wim-De-Clercq** [comment]
But I feel like setting it on C is on the wrong side of things.

I am hoping to create a library/package with its own database model and alembic versioning that other projects can use or extend. The base model can't / doesn't know about how other projects will implement and use it. So I'm ideally looking for a change I can do to revision **B'** to say it must run before **C** rather than changing **C** because it doesn't need to know about B.

**Comment by zzzeek** [comment]
then simply the C migration will need to be forwards-patched by B' in some way at runtime.     if you are interested I would support a new module-level attribute for this as there is no event hook at this time to allow this to be cleanly implemented however I would need a contributor to provide a pull request with tests.

**Comment by zzzeek** [comment]
the hook would be as follows:

```
import sqlalchemy as sa

from alembic import op


revision = "9560e61652ae"
down_revision = None
branch_labels = None
depends_on = None


def on_revision_map_load(revision_map):
    """A hook that is called after the complete revision map has been loaded.

    allows migration scripts to add additional cross-dependencies dynamically.

    """


def upgrade():
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass

```

then a migration would say:
```

def on_revision_map_load(revision_map):
    """A hook that is called after the complete revision map has been loaded.

    allows migration scripts to add additional cross-dependencies dynamically.

    """
    C = revision_map.get_revision("C")
    Bprime = revision_map.get_revision("Bprime")

    revision_map.add_dependency(Bprime, C)

    # or perhaps the API can work via ids directly:
    # revision_map.add_dependency("Bprime", "C")

```
however I dont know what you had in mind for how this "B'" file is supposed to know about "C".

**Comment by Wim-De-Clercq** [comment]
> however I dont know what you had in mind for how this "B'" file is supposed to know about "C".

Initially, when the **B'** would be written, I assume before C exists there won't be a problem. 

----
This is also where I'm at right now. There is no problem at the moment. But it is something that's not impossible to happen in the future, and I'd like to know there's a proper solution at hand.

----

When later on, the base1 project decides to refactor a column name or something, unknowingly breaking **B'** in the process. Then the other project (base2 above) would see that during testing when they upgrade the library version-- assuming the test database gets setup with alembic.

Then people can either look at the latest successful revision of the previous version of the base1 project (which is **B**) and just pick the next revision, whatever it is, and use that one next to set at the module level attribute / in `on_revision_map_load` code. 
Or of course, people can go dig deeper to figure out the specific revision that causes the breakage, but it actually doesn't matter much.

Developers would have to change an existing revision's code a little bit (just adding the dependency in the **B'** file), which I usually won't condone, because the file won't run again on servers where the database is already deployed. However, for adding another dependency on a revision like this, I don't see much harm in this.

----
I'll check out the `on_revision_map_load`, it looks promising.

**Comment by zzzeek** [comment]
yes, the hook does not exist as of yet, this is a proposal that would in theory help you to solve your issue.  some problems with this hook as proposed however are that we would need to define an ordering by which the hooks are invoked in migration files, which would be likely history order, but then those hooks are trying to alter that history, and maybe this is not a good way to do this.  another option is to have the hook be something someone can do in their env.py just once, that avoids all the thorny issues, but again since it's not clear how you see this being used then im not really sure.

another proposal, which might be simpler to implement, is to support a new attribute "is_depended_on" that just allows a B' to name a C.   If you have motivation to help with a PR for the latter we can do that.

**Comment by Wim-De-Clercq** [comment]
> another proposal, which might be simpler to implement, is to support a new attribute "is_depended_on" that just allows a B' to name a C. If you have motivation to help with a PR for the latter we can do that.

I'd be up for that. We seem to have a hell of a timezone difference though x).


Another question. Don't you feel that it's bad, in the current state, when using different base branches (or I think it's the same when working with split branches, although not sure). That the order of revisions doesn't stay the same forever?

Like 
```
base1: A > B
            \ depends_on
base2:        Bx

alembic upgrade runs A > B > Bx


Couple weeks later
base1: A > B > C > D
            \ depends_on
base2:        Bx > Cx

alembic upgrade runs A > B > C > D > Bx > Cx
```
Doesn't that always introduce a risk for future alembic upgrades to fail?

I can understand when there would be no depends_on this doesn't matter, because the revisions are so different and seperate there is no way to clash.

But in the case of split branches (if 1 branch in the future makes changes no longer compatible with the beginning of branch 2) or seperate bases with a depends_on, I feel it's a little risky, no? 
Wouldn't it be better to treat `depends_on` as a "run immediately after" instead of just "after"

**Comment by zzzeek** [comment]
> > another proposal, which might be simpler to implement, is to support a new attribute "is_depended_on" that just allows a B' to name a C. If you have motivation to help with a PR for the latter we can do that.
> 
> I'd be up for that. We seem to have a hell of a timezone difference though x).
> 
> ```
> 
> Doesn't that always introduce a risk for future alembic upgrades to fail because revisions are put in between 2 revisions that used to be run one after the other?

if folks are putting cross-dependent revisions in two separate base branches, which is a bad idea unless they are prepared to manually resolve dependencies, then yes.


> 
> But in the case of split branches (if 1 branch in the future makes changes no longer compatible with the beginning of branch 2) or seperate bases with a depends_on, I feel it's a little risky, no?
> Wouldn't it be better to treat `depends_on` as a "run immediately after" instead of just "after"

I'm not sure how such an ordering could be produced, without simply having another "depends on" of some kind that automatically sets up "depends_on" on these subsequent revisions.  that is, the algorithm to come up with this traversal is already **extremely complicated**.   it's code that i don't touch,and if i have to, I need to spend a couple of days re-familiarizing with it.    to introduce a second system of constraints within it would be impractical.  so this new constraint that you refer towards would need to be expressed as another "depends_on" somehow.  if you can solve the problem at that level then sure.  however I don't know that you can assume that adding such a rigid constraint, in all cases automatically, is going to provide for enough flexibility as each time you add more "depends_on" in a topological graph, you lose the ability to add other kinds of constraints without adding cycles.


> 
> Update: note this is a question i have no good solution for. You could say, yes Bx should run after B to stay consistent with the past, but then what about C and Cx where no depends_on was specified, there you may get inconsistent again because alembic doesn't know which one came first.

**Comment by zzzeek** [comment]
it looks like for actionable items in this issue we proposed an "on_revision_map_load" hook which I would support, however I don't have plans to work on this unless someone else wants to contribute.
