### ISSUE TITLE
[QUESTION] Is it possible to mark a revision as a "milestone"?

### ISSUE THREAD

**Issue by dhermes** [sqlalchemy/alembic#727]
For example, consider a scenario where a column `users.name` is being renamed to `users.username`:

```sql
-- Revision 000000000001
CREATE TABLE users (
    id UUID NOT NULL,
    "name" TEXT NOT NULL,
);
-- Revision 000000000002
ALTER TABLE users
  ADD COLUMN username TEXT;
-- Revision 000000000003
ALTER TABLE users
  ALTER COLUMN username
  SET NOT NULL; -- Don't do this on a large table!
-- Revision 000000000004
ALTER TABLE users
  DROP COLUMN name;
```

During a rolling update of the codebase, if the active revision was `000000000001`, then applying all the migrations up to `000000000004` would cause the current code to fail anywhere that it referenced `users.name`.

Is there some kind of "milestone" metadata to set on `000000000002` to say "don't apply migrations past this point"? In this contrived case, application owners would need to
- apply up to `000000000002`
- deploy code that starts writing to `users.username`
- make sure some offline job runs to backfill `users.username` with the contents of `users.name`
- apply up to `000000000003`
- deploy code that no longer depends on `users.name`
- apply up to `000000000004`

**Comment by zzzeek** [comment]
> For example, consider a scenario where a column `users.name` is being renamed to `users.username`:
> 
> During a rolling update of the codebase, if the active revision was `000000000001`, then applying all the migrations up to `000000000004` would cause the current code to fail anywhere that it referenced `users.name`.

So a rolling upgrade scheme would never do a RENAME of a column.  rolling upgrade scenarios require that you only add new columns and tables during an "expand" phase, then update all the code which has to communicate with both old and new columns/tables at the same time (either via the app or with triggers), then a "contract" phase can remove the old columns once they are no longer used.

rolling upgrade schemes are very difficult to do and require careful planning every time.  I have not seen any improvements on this fact.   Here's a blog post that seems to lay out the whole situation very well: https://thorben-janssen.com/update-database-schema-without-downtime/


> 
> Is there some kind of "milestone" metadata to set on `000000000002` to say "don't apply migrations past this point"? In this contrived case, application owners would need to
> 
>     * apply up to `000000000002`
> 
>     * deploy code that starts writing to `users.username`
> 
>     * make sure some offline job runs to backfill `users.username` with the contents of `users.name`
> 
>     * apply up to `000000000003`
> 
>     * deploy code that no longer depends on `users.name`
> 
>     * apply up to `000000000004`

you can assign any name you'd like to a revision, either by "alembic revision --rev-id <name>" or by just editing the migration file,  and you can also assign additional "labels" to it as described at https://alembic.sqlalchemy.org/en/latest/branches.html#working-with-branch-labels.   then you can "alembic upgrade <labelname>"  or just "alembic upgrade <revision>"

**Comment by dhermes** [comment]
Thanks for the quick response and sorry for my delay! In conversations with colleagues it occurred to me it'd be possible to write "milestone" helpers with the existing tooling. (I waited to reply because I was hoping to get enough time to write up a sample.) Will try to post the shape of my idea in this thread soon but consider the issue closed, thanks!
