### ISSUE TITLE
No module named alembic.__main__; 'alembic' is a package and cannot be directly executed

### ISSUE THREAD

**Issue by MosheVai** [sqlalchemy/alembic#728]
I am trying to run alembic inside a venv inside of WSL-2 Ubuntu.
I am using using the following command:
```
python -m alembic revision --autogenerate -m "create foo"
```
resulting in 
```python-exception
/home/ubuntu/code/my-repo/venv/bin/python: No module named alembic.__main__; 'alembic' is a package and cannot be directly executed
```

python version: Python 3.7.8
alembic version:  1.4.0

**Comment by zzzeek** [comment]
usually you should invoke alembic via the entrypoint script  /path/to/venv/bin/alembic.   if you want to invoke from the python executable directly you would need to say "python -m alembic.config".

**Comment by CaselIT** [comment]
I guess a `__main__.py` that just invokes `config.py` may be added?

**Comment by zzzeek** [comment]
that would be great, yeah.

**Comment by CaselIT** [comment]
@MosheVai if you want to propose a pr it would be great!

**Comment by MosheVai** [comment]
@CaselIT sure

**Comment by CaselIT** [comment]
No I mean literally just
```py
from config import main
if __name__ == "__main__":
    main()
```

**Comment by sqla-tester** [comment]
**CaselIT** has proposed a fix for this issue in the **master** branch:

**Add ``__main__.py`` file to alembic package to support invocation** https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/2313
