### ISSUE TITLE
Support identity columns

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/alembic#730]
This is just a placeholder 
After https://github.com/sqlalchemy/sqlalchemy/issues/5527 is done support for identity columns should be added to alembic

**Comment by sqla-tester** [comment]
**CaselIT** has proposed a fix for this issue in the **master** branch:

**Add support identity columns.** https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/2371
