### ISSUE TITLE
alembic attempts to reflect tables that should be filtered out when using include_schemas / include_object

### ISSUE THREAD

**Issue by odesenfans** [sqlalchemy/alembic#733]
Hello,

I am using alembic in conjugation with PostgreSQL12 + TimeScaleDB. I am attempting to use dedicated schemas for my tables. Apparently the correct procedure is to set `include_schemas=True` and use `include_object` to filter out unwanted objects. TimeScaleDB creates a few schemas when installing the extension (ex: `_timescaledb_cache`, `_timescaledb_catalog`, etc). I want to filter them out, resulting in the following code in `env.py`:

```
APP_SCHEMAS = {"my_schema1", "my_schema2"}


def include_object(object, name, type_, reflected, compare_to):
    if type_ == "table":
        return object.schema in APP_SCHEMAS
    else:
        return "timescaledb" not in name


def run_migrations_online():
    ...
    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            version_table_schema=version_table_schema,
            target_metadata=target_metadata,
            include_schemas=True,
            include_object=include_object,
        )
```

Turns out, alembic still tries to reflect tables before excluding them. This is a problem in this particular use case because some tables defined by TimeScaleDB do not have columns, resulting in a lovely `sqlalchemy.exc.NoSuchTableError: cache_inval_hypertable` exception. I'm not interested in these tables and I don't really care why they are designed that way; I just want to ignore them entirely.

I isolated this code (alembic 1.4.2):
```
    for s, tname in conn_table_names.difference(metadata_table_names):
        name = sa_schema._get_table_key(tname, s)
        exists = name in removal_metadata.tables
        t = sa_schema.Table(tname, removal_metadata, schema=s)

        if not exists:
            ...
            inspector.reflecttable(t, None)
        if autogen_context.run_filters(t, tname, "table", True, None):
```

Is this a known issue? Is there any known workaround?

Otherwise, I can think of at least two possibilities:
1. Filter out unwanted objects early and do not attempt to reflect them.
2. Make the include_schemas parameter evolve to take an iterable of schemas instead of a boolean.

Any opinions on this?

**Versions.**
 - OS: macOS Mojave
 - Python: 3.8
 - Alembic: 1.4.2
 - SQLAlchemy: 1.3.18
 - Database: PostgreSQL12 + TimeScaleDB
 - DBAPI:

**Comment by zzzeek** [comment]
hey there.

the feature you need here is described at #650.   this is an "include_names" hook that takes place before "include_object".   the issue proposes an env.py + CLI version but just starting with the env.py is likely all people need usually.

the SQLAlchemy issue for not being able to reflect the table is at https://github.com/sqlalchemy/sqlalchemy/issues/3247 .

I have tested a workaround for you right now which is to put this in your env.py:


```
from alembic.autogenerate.compare import comparators, _autogen_for_tables

@comparators.dispatch_for("schema")
def filter_schemas(autogen_context, upgrade_ops, schemas):
    if "_timescaledb_cache" in schemas:
        schemas.remove("_timescaledb_cache")
    if "_timescaledb_catalog" in schemas:
        schemas.remove("_timescaledb_catalog")

    return _autogen_for_tables(autogen_context, upgrade_ops, schemas)

```

this allows you to override the existing autogen_for_tables hook.   obviously it's using private API for part of it, so this is not a long term solution.    If someone can work on #650 that would expedite as I think that's probably a pretty important thing we need b.c. i agree that it reflects all the tables we dont want is a big problem in a lot of ways.

**Comment by gjeusel** [comment]
In fact, you'll also need to remove the previously `_autogen_for_tables` registered hook from the registry like so:

```python

def filter_schemas(autogen_context, upgrade_ops, schemas):
    timescaledb_schemas = {
        "_timescaledb_internal",
        "_timescaledb_config",
        "_timescaledb_catalog",
        "_timescaledb_cache",
        "timescaledb_information",
    }
    schemas = schemas - timescaledb_schemas
    return _autogen_for_tables(autogen_context, upgrade_ops, schemas)


comparators._registry[("schema", "default")] = [filter_schemas]
```

**Comment by zzzeek** [comment]
overall #650 will fix this so closing.
