### ISSUE TITLE
Google BigQuery

### ISSUE THREAD

**Issue by MCFHTAGENTS** [sqlalchemy/alembic#738]
Would it be possible to add support for google bigquery with the pybigquery module?

**Comment by zzzeek** [comment]
Alembic can work with bigquery but I don't know what kinds of table altering instructions bigquery supports.   There is also [batch mode](https://alembic.sqlalchemy.org/en/latest/batch.html) but that requires "INSERT FROM SELECT" which im not sure they have either.

To get alembic connectvity you would need to request this feature from pybigquery at https://github.com/mxmzdlv/pybigquery and they need to add an DefaultImpl subclass to their module.

The example at [sqlalchemy-redshift](https://github.com/sqlalchemy-redshift/sqlalchemy-redshift/blob/master/sqlalchemy_redshift/dialect.py#L32) shows the basic idea:

```python

try:
    import alembic
except ImportError:
   pass
else:
    from alembic.ddl import impl
    class PyBigQueryImpl(impl.DefaultImpl):
        __dialect__ = "bigquery"

```

that will register "bigquery" as a dialect in Alembic and then you can run alembic ops using it, at the very least op.execute(<some sql>).

as far as how to actually alter table constructs in bigquery, someone would have to work out what those operations would be and they can be added to the above PyBigQueryImpl.

**Comment by jimfulton** [comment]
Is there anything akin to the SQLAlchemy compliance tests?

(It doesn't look like it.)

**Comment by zzzeek** [comment]
ideally there would be, and there's an issue for this somewhere, but right now no, not really.    I would imagine BigQuery "schemas" are *very* different in any case.

**Comment by jimfulton** [comment]
BigQuery schemas are fairly standard.  They mainly lack indexes and constraints (other than required).

We run 198 of the compliance tests. :)

Anyway, I'm about to find out how hard this is.
