### ISSUE TITLE
How to package migrations ?

### ISSUE THREAD

**Issue by bersace** [sqlalchemy/alembic#742]
Hi,

**Describe your question**

I searched documentation for best practice on how to ship alembic migration. Do you have any advice ?

Thanks

**Comment by zzzeek** [comment]
hi there -

I dont have any special advice, alembic migrations are .py files so I'd place them into a package as part of your application.

for example openstack neutron does it here: https://github.com/openstack/neutron/tree/master/neutron/db/migration   (they have an enormous migration tree)

you of course have to define for your end users how they will run migrations and often people will create custom frontends.    the doc at https://alembic.sqlalchemy.org/en/latest/api/commands.html shows how to run alembic commands programmatically.

I've never myself shipped an application that itself includes migration files, the openstack apps (which are huge) are the examples I have, there may be others out there.

**Comment by bersace** [comment]
@zzzeek thanks for the quick anwser. Good references :+1:
