### ISSUE TITLE
Are there plans to add type annotations / type hints / stub files for mypy?

### ISSUE THREAD

**Issue by MartinThoma** [sqlalchemy/alembic#745]
Type hints make it possible to use mypy to check automatically for bugs. They can be added by annotating the functions / methods directly or by adding stub files.

Are there plans to add stub files or type hints to alembic?

**Comment by zzzeek** [comment]
sure, this is based on the migration of SQLAlchemy and Alembic to python 3 only first.  SQLAlchemy 1.4 has to come out, then SQLAlchemy 2.0 will be python 3 only.  around the same time we can look into alembic going python 3 only as well and then it will be a lot less resistance to type annotating.

but there's also a particular problem with Alembic which is that the whole "alembic.op" thing is a little too magical so we also probably need to change how migration files are written, as far as the imports at the top, that is "from alembic import op" will have to do something like "alembic.get_op()" .     cc @caselit 

this is fairly long term stuff unless people are interested in working on it more immediately.

**Comment by CaselIT** [comment]
Regarding the magic of `alembic.op`, [pep-562](https://www.python.org/dev/peps/pep-0562/) that adds `__getattr__`/`__dir__` for modules may help a bit, but it's still hard to type a module that dinamically loads its method.
Another alternative may be that `op` is no longer a module, but a class instance.

Regarding strub files, I'm personally not familiar with them. I know that they have a separate extension (`.pyi` ?) and I think are shipped alongside the package on pypi. If these could be used, maybe the time horizon would be shorter, and can maybe be a "stopgap" until a more pep484 friendly version of alembic is done.

@MartinThoma do you have experience using / distributing them?

**Comment by MartinThoma** [comment]
I have tried stub files before and it seemed pretty straight forward for a small pure-python package. Essentially you have a `xyz.pyi` next to a `xyz.py` file. The `.pyi` file only contains the signature with an ellipsis:

```
from typing import Any, Dict

def signature(some: int, types: Dict[str, Any]) -> str:
    ...
```

If the test coverage is good, one can create them semi-automatically with MonkeyType. If the signature changes, one needs to change the pyi file as well. If new functions are added, the signature needs to be added to the pyi file.

C-extensions / bindings are one known blind-spot for me where I currently don't know how it works.

I will soon add [a mypy plugin for a smaller project](https://github.com/miguelgrinberg/Flask-HTTPAuth/issues/112#issuecomment-703163407), maybe that is one option for alembic as well. Official support and thus integration into the official package would be nice, though.

**Comment by CaselIT** [comment]
Initial work is on https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/2758

we are trying to get this moving for 1.7 soonish™

**Comment by zzzeek** [comment]
that's been merged and we also added generation of .pyi files for the "alembic.op" and "alembic.config" namespaces in 1977047a11124221461ad8daee502bc4c74d5f6c so things should be pretty good now.
