### ISSUE TITLE
narrow the "target database is not up to date" autogenerate check when a specific head is given

### ISSUE THREAD

**Issue by Mrgoulonghui** [sqlalchemy/alembic#751]

**Comment by Mrgoulonghui** [comment]
pip install alembic==1.3.0

**Comment by zzzeek** [comment]
hey there -

this is expected behavior for now, however I suppose the system could be enhanced such that the check for "not up to date" only takes into account the head branch that's being worked on.   there are no plans to add this right now however people are welcome to work on it.

**Comment by zzzeek** [comment]
this seems like it would be complicated and it's best that autogenerate is only run when the database is fully up to date.
