### ISSUE TITLE
Migration script not working with Postgres and SQLAlchemy ORM (FastAPI)

### ISSUE THREAD

**Issue by NAVHITS** [sqlalchemy/alembic#752]
**I was setting up Postgres with FastAPI and SQLAlchemy. When I try to migrate the models with Alembic the migration file does not have the migrations. It is just passing the functions. Let me know if I'm doing something wrong.**

**Steps I followed**
* `alembic init alembic`
* Added the database URL in `env.py`
* Made some changes in `alembic.ini`
* After making the models, I ran `alembic revision -m "First commit"`
* This generated a migration file
* Next I ran `alembic upgrade head`
* All of these ran without errors
* But the table was not created in Postgres, obviously because the migration file did not have the migrations.
* Not sure what went wrong. There are no mistakes in the models.

The model
```py
class User(Base):
    __tablename__ = "users"

    id = Column(Integer, primary_key=True, index=True)
    data = Column(JSON)
```

Here's the code,
```py
from logging.config import fileConfig

from sqlalchemy import engine_from_config
from sqlalchemy import pool

from alembic import context
import os, sys
from dotenv import load_dotenv

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
load_dotenv(os.path.join(BASE_DIR, ".env"))
sys.path.append(BASE_DIR)

config = context.config

config.set_main_option("sqlalchemy.url", os.environ["DATABASE_URL"])

fileConfig(config.config_file_name)

import models

target_metadata = models.Base.metadata

def run_migrations_offline():
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )

    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online():
    connectable = engine_from_config(
        config.get_section(config.config_ini_section),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    with connectable.connect() as connection:
        context.configure(connection=connection, target_metadata=target_metadata)

        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()

```

The generated migration file
```py
from alembic import op
import sqlalchemy as a

# revision identifiers, used by Alembic.
revision = '0ff8f69f9ac5'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    pass

def downgrade():
    pass

```

**Additional context**
To make it work, I had to manually add the migrations. But this becomes a bit hectic when I've to do this constantly. Any help appreciated! Thanks :)

**Comment by CaselIT** [comment]
Hi,

Thanks the expected behaviour. You need to use autogenerate to make alembic create the migrations. See https://alembic.sqlalchemy.org/en/latest/autogenerate.html

**Comment by NAVHITS** [comment]
@CaselIT I've used autogenerate and I got an error and it displays all the available options to use. I guess this is because of some configuration mistakes that I would've made. Let me check and see if it still exists for me. Else I will acknowledge here and close the issue :)

**Comment by NAVHITS** [comment]
Update: I identified the error, was with `target_metadata` in `env.py` There was an import issue. Was able to fix this and run properly. Closing this issue for now. Thanks :)
