### ISSUE TITLE
use column.copy() for column operations due to SQLAlchemy "column is already attached" issue

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/alembic#753]
the change in https://github.com/sqlalchemy/sqlalchemy/issues/5618 is now hitting me as I'm trying to write a recipe for someone.  when we take columns into the operations we should just run _copy() on them so that we dont get the already attached to table issue.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Copy column that's already attached** https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/2345
