### ISSUE TITLE
Testing updates

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/alembic#759]
Various testing cleanup odds and ends:
- Alembic includes the `testing/exclusions.py`. Since 1.5 targets sa 1.3+ that could probably be removed.
- Computed tests should include sqlite (ideally there should be a way to get these capabilities from sqlalchemy)

**Comment by sqla-tester** [comment]
**CaselIT** has proposed a fix for this issue in the **master** branch:

**Use exclusions from sqlalchemy** https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/2419

**Comment by sqla-tester** [comment]
**CaselIT** has proposed a fix for this issue in the **master** branch:

**Use exclusions from sqlalchemy** https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/2419
