### ISSUE TITLE
Segmentation fault (core dumped) while creating migration

### ISSUE THREAD

**Issue by Ahtii** [sqlalchemy/alembic#762]
Hi,
I have installed alembic and setup `env.p` file for alembic but once i run my migration using the following command:

`alembic revision --autogenerate -m "create tables"`

I get the following error 

`Segmentation fault (core dumped).`

I tried reinstalling and setting up alembic once again but I get the same problem. Please help

My pc:
os: ubuntu 18
python: 3.6
alembic: 1.4.3

Edit:

I tried manually create the migrations with:

`alembic revision -m "create user table"`

The above command ran without any problem but when i run:

`alembic upgrade head` 

I get the same error.

It works perfectly in my friends pc. Their config:
Ubuntu 20
Python 3.8.5

**Comment by CaselIT** [comment]
Alembic does not use any c extension, so I don't think it's alembic fault. 

Sqlalchemy does so maybe it's a problem with its wheels? Could also indicate which version of sqlalchemy you are using?
Also could you try uninstalling it, and reinstall from source with the command to see if it helps:
```
pip install --no-binary :all: sqlalchemy
```

**Comment by Ahtii** [comment]
Thanks for the reply I will try it. Can it be problem with python itself ? or its virtualenv

**Comment by CaselIT** [comment]
If you can recreate the virtualenv that for sure could help.

**Comment by Ahtii** [comment]
Okay still the same error what i have tried:

1. Deleted virtual environment folder and project.
2. Installed latest version of python 3.8.6 
3. Recreated virtualenv with the command:
    `virtualenv myproject-env -p python3.8`
4. Installed required dependence included alembic 1.4.3
    and sqlalchemy 1.3.20.
5. Ran `pip install --no-binary :all: sqlalchemy`

But still the same error. :(

**Comment by Ahtii** [comment]
@CaselIT  Okay still the same error what i have tried:

1. Deleted virtual environment folder and project.
2. Installed latest version of python 3.8.6 
3. Recreated virtualenv with the command:
    `virtualenv myproject-env -p python3.8`
4. Installed required dependence included alembic 1.4.3
    and sqlalchemy 1.3.20.
5. Ran `pip install --no-binary :all: sqlalchemy`

But still the same error. :(

I also tried downgrading sqlalchemy to 1.3.18 still no luck.

Alembic works perfectly in my friends pc. Their config:
Ubuntu 20
Python 3.8.6

**Comment by CaselIT** [comment]
What is the dbapi and database you are using?

Running other commands also has the same problem?
You could try `history` to see if alembic without accessing the db works, and maybe `current` to see if accessing the db does work.

**Comment by Ahtii** [comment]
What is dbapi ? 
I am using `mysql-connector-python 8.0.22` and `mysql-connector 2.2.9` and `alembic history` works without any error while `alembic current` gives the same error does that mean there is something wrong with my database ? I am using mysql 5.7.32

**Comment by Ahtii** [comment]
Okay fixed the problem I reinstalled `mysql-connector 2.2.9` and it fixed the problem :) Thanks anyways :D
