### ISSUE TITLE
Feature request: Support chronological revision file names

### ISSUE THREAD

**Issue by frmdstryr** [sqlalchemy/alembic#767]
**Is your feature request related to a problem? Please describe.**

Currently revisions use a random (or hash?) "revision_id" that is inserted at the start of the revision file name which causes sorting in editors to be random unless it's manually re-sorted by modified date (if the IDE supports it). Even sorting by modified date doesn't work if some sort of refactor updates a migration.

**Describe the solution you'd like**

1. Put the revision at the end of the filename so logical sorting can be done by a manually added or auto generated prefix
2. Ideally alembic could auto add a branch+auto incremented prefix or a timestamp to the start

**Describe alternatives you've considered**

Is there some sort of configuration for this?

**Additional context**

![image](https://user-images.githubusercontent.com/380158/101365631-0cf8ef00-3872-11eb-89dd-d4c39528e969.png)

Looking at this, which one is the latest revision?

**Have a nice day!**

**Comment by zzzeek** [comment]
hey there -

please use file_template as documented at https://alembic.sqlalchemy.org/en/latest/tutorial.html#editing-the-ini-file .   probably using a date template at the beginning would be most generic here.

```
file_template - this is the naming scheme used to generate new migration files. The value present is the default, so is commented out. Tokens available include:

        %%(rev)s - revision id

        %%(slug)s - a truncated string derived from the revision message

        %%(year)d, %%(month).2d, %%(day).2d, %%(hour).2d, %%(minute).2d, %%(second).2d - components of the create date, by default datetime.datetime.now() unless the timezone configuration option is also used.


```

**Comment by frmdstryr** [comment]
Ah, figured it was there somewhere. Thanks!

**Comment by frmdstryr** [comment]
Could a new token `count` be added? Doing a full timestamp is pretty noisy...

**Comment by zzzeek** [comment]
what would we be counting?

**Comment by frmdstryr** [comment]
I think the number of revisions from base to head +1 would make sense. 

If there's branches the count could be duplicated but the revision id is unique so it don't think it matters.

**Comment by zzzeek** [comment]
but everything would be out of order again, defeating the purpose of the count.  I should fill you in that this counting issue was task number one when I decided to write a new migration tool to replace sqlalchemy-migrate.  sa-migrate uses an integer counter as you describe and it was a nightmare.  I work with Openstack apps for my day job many of which are still on sa-migrate.   they literally have dozens of empty "placeholder" revisions between every "actual" revision in order to deal with this.   

really, the way to see the "chronological" order is to use the "alembic history" command.

**Comment by zzzeek** [comment]
also it's not just "duplication", if you have branches that were made at very different times, if you have backporting of branches, you can easily see situations like "1, 2, 3, 4, 45, 46, 47, 5, 6, 7, 8", etc.  it gets useless pretty fast.   this is why we try to encourage finding other ways to achieve he goal here.

**Comment by frmdstryr** [comment]
I see in that case timestamps don't help either... is the revision id required in the name?  If so the versions could be re-indexed after the branch is re-merged (however that works).  

It'd still be helpful for small projects like mine :) but in any case I understand it might be best to just not have it.

**Comment by zzzeek** [comment]
the names of the files don't matter at all they can just be the datestamp if you'd like.

**Comment by zzzeek** [comment]
but yes, a "re-indexing of the names" is what would be needed to generally support filenames being in "order", which is also kind of not useful for a large scale branch-and-merge situation as the filename changes would make it that much harder to track down changes.

**Comment by frmdstryr** [comment]
Yeah being able to re-insert into history messes that up.   

The only other thing that could possibly work would be to to make a count a float then multiply the count from  "distance from main"   branch where the distance is always multiplied by 1/100 (or 1/1000)  of the parent branch's distance.  So any branch gets a fraction of the tree that infinitely grows smaller. 

Eg so above it would be `1, 2, 3, 4.01, 4.02, 4.03, 5, 6, etc...`

If there were two branches `1, 2, 3, 4.01, 4.0101, 4.0102, etc... 4.03, 5, 6, etc...`.  

Not sure if I described that right but I hope you get the idea. It'd work as long as you never create 100 or 1000 migrations off of any branch (which I hope would never happen lol).

**Comment by zzzeek** [comment]
that still doesn't really change anything as far as branches being merged without having to rename all the files which I would not consider a best practice I'd want to encourage.   So I'm noticing there is not a nice way to extend the tokens that can be placed here, I can give you a hacky one (basically change the file_template at runtime) but I would support being able to supply a function in the env.py that delivers additional tokens to the file template when alembic revision is run.
