### ISSUE TITLE
server_default not working with python datetime

### ISSUE THREAD

**Issue by Ahtii** [sqlalchemy/alembic#768]
I am trying to use `server_default` instead of `default` because of the reasons mentioned in [this](https://stackoverflow.com/questions/13370317/sqlalchemy-default-datetime) post (second answer) but I get the following error:

`sqlalchemy.exc.ArgumentError: Argument 'arg' is expected to be one of type '<class 'str'>' or '<class 'sqlalchemy.sql.elements.ClauseElement'>' or '<class 'sqlalchemy.sql.elements.TextClause'>', got '<class 'datetime.datetime'>'`

with this code:

`created_date = Column(DateTime, server_default=datetime.utcnow())`

**Comment by zzzeek** [comment]
hey there -

docs for server_default are at https://docs.sqlalchemy.org/en/13/core/defaults.html#server-defaults .

you can't send a Python function for server_default, you need to use a database-side function derived from the [func](https://docs.sqlalchemy.org/en/13/core/sqlelement.html?highlight=func#sqlalchemy.sql.expression.func) namespace, like "func.now()".

**Comment by Ahtii** [comment]
@zzzeek but i want a utc time which is not possible with `func.now()` but still i tried it by replacing `datetime.utcnow()` with `func.now()` and now i get Null value in the database. Then i tried replacing `server_default` with `default` and it works there. How would i use utc with `server_default` ?

**Comment by zzzeek** [comment]
> @zzzeek but i want a utc time which is not possible with `func.now()` but still i tried it by replacing `datetime.utcnow()` with `func.now()` and now i get Null value in the database. 

the database table / column has to be created with this setting. if you are adding it after the fact, you'd need to run a migration that will alter the default value of the column.  however it's easier if you are just in development to drop the table and recreate it with the server default function you are looking for.

> Then i tried replacing `server_default` with `default` and it works there. How would i use utc with `server_default` ?

what database are you targeting?   each database has a different syntax for this.  if you are looking to create a DB-agnostic platform then you'd want to look into a recipe like https://docs.sqlalchemy.org/en/13/core/compiler.html#utc-timestamp-function

**Comment by Ahtii** [comment]
Okay i recreated the table and now `server_default` works now thanks :) 

The database I am using is MySql and i already checked that link but it doesn't mention MySql

**Comment by zzzeek** [comment]
MySQL only supports "TIMESTAMP" as a datatype, so you would craete your table using the TIMESTAMP data type.  The timestamp is stored in UTC.      You should read https://dev.mysql.com/doc/refman/8.0/en/datetime.html and https://dba.stackexchange.com/a/24904 .

**Comment by Ahtii** [comment]
@zzzeek Just tried to play around with this:

```
from sqlalchemy.sql import expression
from sqlalchemy.ext.compiler import compiles
from sqlalchemy.types import DateTime

class utcnow(expression.FunctionElement):
    type = DateTime()

@compiles(utcnow, 'mysql')
def my_utcnow(element, compiler, **kw):
    return "UTC_TIMESTAMP()" 
```

and then used it in Colum:

`created_date = Column(DateTime(timezone=True), server_default=func.now())`

But that gave Null value.

**Comment by Ahtii** [comment]
@zzzeek Just playing around with:

```
 from sqlalchemy.sql import expression
 from sqlalchemy.ext.compiler import compiles
 from sqlalchemy.types import DateTime

 class utcnow(expression.FunctionElement):
     type = DateTime()

 @compiles(utcnow, 'mysql')
 def my_utcnow(element, compiler, **kw):
     return "UTC_TIMESTAMP()" 
```
and column:

`created_date = Column(DateTime, default=utcnow())`

I moved to `default` again from server_default` as it seems to recreate the table everytime to make `server_default` work

**Comment by Ahtii** [comment]
@zzzeek I also wanna know if I can contribute to Sqlalchemy please give one chance i will work hard.

**Comment by zzzeek** [comment]
hey there -

feel free to hang out on gitter where the devs are: https://gitter.im/sqlalchemy/devel 

contribution is self-motivated so feel free to look through open issues, more in github/sqlalchemy/sqlalchemy where there should be some tagged as "easy".
