### ISSUE TITLE
Alembic is generating alter columns same as models

### ISSUE THREAD

**Issue by matheusads** [sqlalchemy/alembic#771]
I'm working on a legacy multi-tenant postgres database. And now we are mapping to clean SQLAlchemy new code. I'm using alembic to generate the new migrations operations(until now are just SQL scripts).

**The problem:**

Alembic generate this type of code

`op.alter_column('my_table', 'enabled',
           existing_type=sa.BOOLEAN(),
           nullable=False,
           existing_server_default=sa.text('true'))`

**And in models we declare as:**

` class MyTable(Base): 
\_\_tablename_\_ = "my_table" 
\_\_table_args_\_ = {"schema": None}

enabled = sa.Column(sa.Boolean, nullable=False, default=True) `

I think this is not right or necessary. Is this correct? If Yes, why? If Not, how to avoid generate this type of code. It happens with other tables/columns many times. The database has more than 300 tables.

Part of my env.py. In include_object I just return True if is not reflected, else False.

`         with connectable.connect() as connection:

        connection.execute(f"SET search_path to '{schema}'")
        connection.dialect.default_schema_name = schema
        connection.execution_options(schema_translate_map={None: schema})

        context.configure(
            connection=connection, target_metadata=target_metadata,
            version_table_schema=schema, include_object=include_object
        )

        with context.begin_transaction():
           context.run_migrations()
`

**Comment by zzzeek** [comment]
> I'm working on a legacy multi-tenant postgres database. And now we are mapping to clean SQLAlchemy new code. I'm using alembic to generate the new migrations operations(until now are just SQL scripts).
> 
> **The problem:**
> 
> Alembic generate this type of code
> 
> `op.alter_column('my_table', 'enabled', existing_type=sa.BOOLEAN(), nullable=False, existing_server_default=sa.text('true'))`
> 
> **And in models we declare as:**
> 
> ` class MyTable(Base):
> __tablename__ = "my_table"
> __table_args__ = {"schema": None}
> 
> enabled = sa.Column(sa.Boolean, nullable=False, default=True) `
> 
> I think this is not right or necessary. Is this correct? 

seems wrong, sure

> If Yes, why? If Not, how to avoid generate this type of code. 

since you are using multitenancy I would assume that when you run autogenerate, your env.py sees the same table over and over again in many schemas and gets confused, as I note you are setting schema_translate_map which is likely going to think your tables are in a different schema than the one it is reflecting, which would come out as the "default" schema since you are setting search_path.


> Part of my env.py. In include_object I just return True if is not reflected, else False.
> 
> ` with connectable.connect() as connection:
> 
> ```
>     connection.execute(f"SET search_path to '{schema}'")
>     connection.dialect.default_schema_name = schema
>     connection.execution_options(schema_translate_map={None: schema})
> 
>     context.configure(
>         connection=connection, target_metadata=target_metadata,
>         version_table_schema=schema, include_object=include_object
>     )
> 
>     with context.begin_transaction():
>        context.run_migrations()
> ```

I would suggest following the cookbook example at https://alembic.sqlalchemy.org/en/latest/cookbook.html#rudimental-schema-level-multi-tenancy-for-postgresql-databases that I've worked out ensures that each tenant is treated as the "default" schema without Alembic having to guess which schema is which.   Looks mostly like what you have but lose the "schema_translate_map" part of it.




> 
> `

**Comment by matheusads** [comment]
Even with these changes the autogenerate is the same. 

I just don't understand why it happens.

**Comment by zzzeek** [comment]
maybe look at the logging that alembic outputs?  it will tell you when it sees something as new or added.    are you using compare_types or compare_server_default?   can you share an example of a model that has this problem as well as your env.py ?

**Comment by matheusads** [comment]
I found my error, I used docker-compose run instead **exec**. Sorry man
