### ISSUE TITLE
1.5.0 missing templates?

### ISSUE THREAD

**Issue by WilliamMayor** [sqlalchemy/alembic#780]
**Describe the bug**
After a fresh install on a new project I can't run `alembic init` because it's missing the 'generic' template. If I try to run `list_templates` I get an error that the templates directory can't be found.

**Expected behavior**
Alembic initialises the environment.

**To Reproduce**

```sh
python3 -m venv venv
. venv/bin/activate
pip install alembic==1.5.0
alembic init migrations
```

**Error**

```
$ alembic init migrations
  FAILED: No such template 'generic'
$ alembic list_templates
Available templates:

Traceback (most recent call last):
  File "/usr/local/bin/alembic", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/alembic/config.py", line 559, in main
    CommandLine(prog=prog).main(argv=argv)
  File "/usr/local/lib/python3.9/site-packages/alembic/config.py", line 553, in main
    self.run_cmd(cfg, options)
  File "/usr/local/lib/python3.9/site-packages/alembic/config.py", line 530, in run_cmd
    fn(
  File "/usr/local/lib/python3.9/site-packages/alembic/command.py", line 17, in list_templates
    for tempname in os.listdir(config.get_template_directory()):
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.9/site-packages/alembic/templates'
```
This error is copied directly from the docker image I'm working in that doesn't have the venv from the above example.

**Versions.**
 - OS: Debian GNU/Linux 10 (buster)
 - Python: 3.9.1
 - Alembic: 1.5.0
 - SQLAlchemy: 1.3.22
 - Database: PostgreSQL
 - DBAPI: psycopg2

**Have a nice day!**

**Comment by zzzeek** [comment]
we switched from setup.py to setup.cfg for our metadata and I forgot to test this.  will have 1.5.1 release ASAP

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**fix erroneous package_dir directive** https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/2488

**Comment by zzzeek** [comment]
OK 1.5.1 is released, I just did a full pip install here and it seems to work.   feel free to try it out!
