### ISSUE TITLE
Manage Views with Alembic

### ISSUE THREAD

**Issue by totalhack** [sqlalchemy/alembic#785]
**Describe your question**

I've come across a few posts that show approaches to creating view objects with `sqlalchemy`. Some common ones are discussed on [this](https://stackoverflow.com/questions/9766940/how-to-create-an-sql-view-with-sqlalchemy) SO question. 

All of the ones I've seen seem to depend on calling `create_all`, and even `sqlalchemy-utils` (I know this is not something you maintain) appears to be doing that [under the hood](https://github.com/kvesteri/sqlalchemy-utils/blob/2e8ee0093f4a33a5c7479bc9aaf16d7863a74a16/sqlalchemy_utils/view.py#L161). 

I had hoped I could just use a declarative approach to creating a view and then use `alembic` to autogenerate a revision, but it doesn't seem to pick them up. Is there a recipe out there that shows how to create and use views with alembic? Is [this cookbook example](https://alembic.sqlalchemy.org/en/latest/cookbook.html#create-operations-for-the-target-objects) the best approach? Looks like it doesn't do autogeneration and is a little less "built in" than I was expecting. 

Ideally i'd be able to do one of the following with declarative syntax and have alembic detect views/changes:

```python
# Using sqlalchemy-utils create_view
class MyView(Base):
    __table__ = create_view(
        name="my_view",
        selectable=sa.select(<selectable stuff here>),
        metadata=Base.metadata,
    )

# Made up alternative syntax
class MyView(Base):
    is_view = True
    __tablename__ = "my_view"    
    __definition__ = sa.select(<selectable stuff here>)
```

Thanks for taking a look.

**Comment by totalhack** [comment]
The workaround I've come up with for this so far is to maintain a list of views and then use CREATE OR REPLACE VIEW anytime I run migrations. So it doesn't actually track in the migration files, but at least syncs the views with the current model anytime I run a migration. Roughly:

```python
# some model file

my_selectable = sa.select(...)

class MyView(Base):
    __tablename__ = "my_view"
    __selectable__ = my_selectable
    __table__ = create_view(
        name="my_view",
        selectable=my_selectable,
        metadata=Base.metadata,
    )

views = [MyView]
```

Then in env.py...

```python
from sqlalchemy.schema import DDLElement
from sqlalchemy.ext import compiler

from some_code.db import get_engine
from some_code.models.base import BaseModel, views # views is a compiled list of all views from sub models at this point

<snip...the normal env.py stuff>

class CreateView(DDLElement):
    def __init__(self, name, selectable):
        self.name = name
        self.selectable = selectable

@compiler.compiles(CreateView)
def compile_create_materialized_view(element, compiler, **kw):
    return "CREATE OR REPLACE VIEW {} AS {}".format(
        element.name,
        compiler.sql_compiler.process(element.selectable, literal_binds=True),
    )

for view in views:
    print(f"Processing view: {view}")
    # My base model sets __table_args__ 
    view_name = view.__table_args__["schema"] + "." + view.__tablename__
    res = get_engine().execute(CreateView(view_name, view.__selectable__))
```

Maybe there is a better way though?

**Comment by zzzeek** [comment]
the cookbook example you linked towards refers right at the top to the project at https://github.com/olirice/alembic_utils , which claims to support autogenerate.  I worked a bit with that developer early on to get that project started, maybe it works!   that's what I got.

**Comment by totalhack** [comment]
That project looks to be specific to Postgres, I'm using MySQL. But I'll look there for inspiration if my workaround gets tired. Thanks for the feedback!
