### ISSUE TITLE
altering primary_key column generates alter_column with nullable dropped

### ISSUE THREAD

**Issue by sdspikes** [sqlalchemy/alembic#788]
**Describe the bug**
After a table is created with a primary key, if that key is updated to have a comment (or presumably any other change) the resulting [migration](https://github.com/sdspikes/alembic-primary-key-null-minimal-example/blob/main/alembic/versions/2_add_comments.py#L21) drops `nullable=False`, generating a [sql](https://github.com/sdspikes/alembic-primary-key-null-minimal-example/blob/main/generated_sql_version_2.sql#L3) command like: `ALTER TABLE key_and_nullable MODIFY id INTEGER(11) NULL AUTO_INCREMENT COMMENT 'auto-incrementing key';`

This occurs even if the [column](https://github.com/sdspikes/alembic-primary-key-null-minimal-example/blob/main/alembic/env.py#L33) had nullable set explicitly.

**Expected behavior**
The generated migration should have `nullable=False` for autoincrementing columns (or at least for primary keys).

The generated SQL should be: `ALTER TABLE key_and_nullable MODIFY id INTEGER(11) NOT NULL AUTO_INCREMENT COMMENT 'auto-incrementing key';`

**To Reproduce**
[Repo with a minimal example](https://github.com/sdspikes/alembic-primary-key-null-minimal-example).  In particular the second migration and the generated SQL as linked above.

**Versions.**
- OS: Debian GNU/Linux rodete (x86-64)
- Python: 3.8.6
- Alembic: 1.4.3
- SQLAlchemy: 1.3.22
- Database: mysql Ver 15.1 Distrib 10.5.8-MariaDB, for debian-linux-gnu (x86_64) using EditLine wrapper
- DBAPI: mysql

**Additional context**
This migration (both through alembic and running as the raw SQL) seems to run without any problem in my local environment and does not actually change the key to be nullable, but in my work dev environment, running the SQL errors out, which seems reasonable, a primary key shouldn't be nullable.  I'm not sure what's different about the dev environment without further investigation, but this really should be generated as not nullable anyway.

**Comment by zzzeek** [comment]
this is local to the autogenerate feature

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Remove obsolete SQLAlchemy pk issue workaround** https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/2521

**Comment by zzzeek** [comment]
add existing_nullable=False to those alter_column() ops for now, this fix will be in the next release.  thanks for the report
