### ISSUE TITLE
Alembic and Aurora Data API

### ISSUE THREAD

**Issue by edalongeville** [sqlalchemy/alembic#794]
Hello,

I have an Aurora mysql DB cluster. I use this dialect:
https://github.com/chanzuckerberg/sqlalchemy-aurora-data-api

In order to connect to my Aurora cluster from sqlalchemy, I create the following engine:
```
engine = create_engine(
            f"mysql+auroradataapi://:@/{db_name}",
            echo=True,
            connect_args=dict(aurora_cluster_arn=cluster_arn, secret_arn=secret_arn),
        )
```
As you can see, instead of using the format `driver://user:pass@localhost/dbname`, I pass my Aurora cluster arn and an AWS Secrets Manager arn (storing username and password).

My Problem:
Alembic expects the following line in alembic.ini:
`sqlalchemy.url = driver://user:pass@localhost/dbname`
In my use case, having this line in the configuration file is impossible: I do not know the user, password and host until runtime (when SQLAlchemy will connect to AWS Secrets Manager via the `secret_arn` and fetch this data).

Solutions using env vars, such as [this one](https://stackoverflow.com/a/55190497), do not work with the auroradatapi dialect.

**How can I configure Alembic to make it create an engine similar to the one above, using the mysql+auroradataapi dialect, and passing secret_arn and cluster_arn as parameters?**

Thanks!

**Comment by CaselIT** [comment]
Hi,

`sqlalchemy.url` is entirely optional in the ini.
Looking at https://github.com/sqlalchemy/alembic/blob/master/alembic/templates/generic/env.py
- for `run_migrations_online` you can create an engine any way you want, also re-using the function in your application
- for `run_migrations_offline` you just need to provide the prefix to that the proper driver can be loaded. that is `"mysql+auroradataapi://"`

Hope it helps

**Comment by CaselIT** [comment]
Please reopen if you are still facing the issue

**Comment by faizulhai24** [comment]
@edalongeville : I am facing the same exact situation. Were you able to get migrations running with Aurora Data API?
