### ISSUE TITLE
Allow modifying logging config when running via the API

### ISSUE THREAD

**Issue by exhuma** [sqlalchemy/alembic#795]
**Is your feature request related to a problem? Please describe.**

`env.py` unconditionally runs `logging.fileConfig()` even if alembic migrations are run via the API (`alembic.command.upgrade()`)

**Describe the solution you'd like**

When migrations are executed via the API I would like my logging config to remain untouched. This would leave me in control of setting different log-levels for `alembic` loggers.

**Describe alternatives you've considered**
I am considering doing modifications inside `env.py` in the project which needs this. This will allow me to get the intended result. But having some way to expose this via the API would make this cleaner, and other people could also benefit from this.

**Comment by zzzeek** [comment]
hi there -

env.py *is* the API.  this file should be modified to fit your needs, and that is why the logging configuration is there.  Alembic itself does not set up any logging configuration at all, so I'm not sure what other "API" could be exposed.

**Comment by zzzeek** [comment]
this is all documented here:

https://alembic.sqlalchemy.org/en/latest/tutorial.html#editing-the-ini-file

> [loggers], [handlers], [formatters], [logger_*], [handler_*], [formatter_*] - these sections are all part of Python’s standard logging configuration, the mechanics of which are documented at Configuration File Format. As is the case with the database connection, these directives are used directly as the result of the logging.config.fileConfig() call present in the env.py script, which you’re free to modify.

**Comment by CaselIT** [comment]
feel free to reopen if you still has issues with this
