### ISSUE TITLE
How to check or edit the autogenerated migration?

### ISSUE THREAD

**Issue by sp1rs** [sqlalchemy/alembic#801]
When we autogenerate the migration through alembic, I would like to ensure that the migration file generated passes few checks. For example, if we add an index to a column the autogenerated file should automatically add `postgresql_concurrently=True` to the attribute. 

Is there any programmatical way to verify the autogenerated migration?

**Have a nice day!**

**Comment by zzzeek** [comment]
If you have explicit rules, like all indexes should have postgresql_concurrently, then i would recommend receiving the revision directives using process_revision_directives: https://alembic.sqlalchemy.org/en/latest/api/runtime.html#alembic.runtime.environment.EnvironmentContext.configure.params.process_revision_directive which receives the autogenerated structure, walks through it, and verifies that the expected elements are present.

You can likely make this a simpler operation by using an autogenerate rewriter: https://alembic.sqlalchemy.org/en/latest/api/autogenerate.html#fine-grained-autogenerate-generation-with-rewriters  , where you would for this example instrument the CreateIndexOp:

```
@writer.rewrites(ops.CreateIndexOp)
def add_index(context, revision, op):
    if not op.kw.get("postgresql_concurrently", False):
      raise Exception("need flag")

```

**Comment by sp1rs** [comment]
Thanks a lot for the answer, now the thing is `create index concurrently` cannot run with the transaction block. How can I run only the index command in the auto-commit mode?

**Comment by zzzeek** [comment]
we made a special construct for this case specifically, see autocommit_block at https://alembic.sqlalchemy.org/en/latest/api/runtime.html#alembic.runtime.migration.MigrationContext.autocommit_block
