### ISSUE TITLE
Revision filename for post_write_hooks options passed in wrong position

### ISSUE THREAD

**Issue by maresb** [sqlalchemy/alembic#819]
**Describe the bug**

While trying to run `pre-commit` as a post-write hooks, I encountered a failure. My config was

```
hooks = pre-commit
pre-commit.type = console_scripts
pre-commit.entrypoint = pre-commit
pre-commit.options = run --files
```

The failure occurred because the pre-commit command was being run as
```bash
pre-commit /path/to/revision_file.py run --files
```
instead of
```bash
pre-commit run --files /path/to/revision_file.py
```

**Expected behavior**

The [documentation](https://alembic.sqlalchemy.org/en/latest/autogenerate.html#basic-formatter-configuration) states:
> The path of the revision file is sent as a single positional argument to the script after the options.

However, checking the code, [this is not the case](https://github.com/sqlalchemy/alembic/blob/8043d5d2b46a2d12e445c8d352d0249447340613/alembic/script/write_hooks.py#L111), as it is being passed as the *first* argument.

**Additional note**

The command line [options are being split](https://github.com/sqlalchemy/alembic/blob/8043d5d2b46a2d12e445c8d352d0249447340613/alembic/script/write_hooks.py#L113) using `str.split()`, but for command line options it's much better to use `shlex.split()` since that properly handles things like quoting.

***PR incoming...***

**Comment by CaselIT** [comment]
thanks!
