### ISSUE TITLE
Allow setting cwd of post-write hooks

### ISSUE THREAD

**Issue by maresb** [sqlalchemy/alembic#822]
**Is your feature request related to a problem? Please describe.**

I am running pre-commit as a post-write hook. However, when using `command.revision()`, the working directory may be outside of my repository, in which case my `.pre-commit-config.yaml` is not found.

**Describe the solution you'd like**

In my `alembic.ini` I want to add the following line under the `[post_write_hooks]` section
```ini
pre-commit.cwd = %(here)s
```
in order to have a reproducible cwd.

**PR incoming...**

**Comment by sqla-tester** [comment]
**Ben Mares** has proposed a fix for this issue in the **master** branch:

**Add cwd post-write hook option** https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/2685
