### ISSUE TITLE
(MINOR) Running tox leaves pysqlite_test_schema.db in repository root

### ISSUE THREAD

**Issue by maresb** [sqlalchemy/alembic#824]
Not at all urgent, just very slightly annoying...

**Describe the bug**

After running `tox` there is an empty file named `pysqlite_test_schema.db` which is left over in the root directory of the repository. Furthermore, this file is not included in `.gitignore`, so it clutters the `git status`.

**Expected behavior**

I expect that running `tox` should have minimal side-effects, and that any such side-effects should be automatically ignored by `git`.

**To Reproduce**

```bash
git clone https://github.com/sqlalchemy/alembic.git
cd alembic
tox
git status
```

**Error**

```
On branch master
Your branch is up to date with 'origin/master'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	pysqlite_test_schema.db

nothing added to commit but untracked files present (use "git add" to track)
```

**Versions.**
 - OS: Ubuntu 20.04
 - Python: 3.8 via tox
 - Alembic: `master`
 - SQLAlchemy: ? (via tox)
 - Database: apparently sqlite via tox
 - DBAPI: ?

**Comment by CaselIT** [comment]
Hi,

Thanks for reporting. If you could open a pr to add the file to the .gitingore or remove it at the end of the tests it would be super!
