### ISSUE TITLE
Generically execute UpgradeOps

### ISSUE THREAD

**Issue by olirice** [sqlalchemy/alembic#830]
**Describe your question**

Given `alembic.operations.ops.UpgradeOps`, is there a way to generically execute the ops against a db session?

The reason for this question is to enable [alembic_utils](https://github.com/olirice/alembic_utils) to refer to entities that might be being created in the same autogen context. For example, trying to create a `Table` and a `PGView` where the view depends on the table.

something like

```python
upgrade_ops: UpgradeOps

sess: Session

for migration_op in upgrade_ops.ops:
    stmt = op_to_sql_text(migration_op) # this is the part I haven't been able to figure out 
    sess.execute(stmt)

# Solve for required migration ops on alembic_utils types here
```

**Additional context**
In support of https://github.com/olirice/alembic_utils/issues/41

Thanks!

**Comment by zzzeek** [comment]
there's an example of how to run these at https://alembic.sqlalchemy.org/en/latest/cookbook.html#run-alembic-operation-objects-directly-as-in-from-autogenerate .    They have be passed to Operations.invoke() where Operations can refer to any Connection object.

**Comment by olirice** [comment]
perfect, thank you  🙌
