### ISSUE TITLE
Alembic generates wrong argument when using PasswordType of sqlalchemy_utils

### ISSUE THREAD

**Issue by ivanlen** [sqlalchemy/alembic#837]
**Describe the bug**
I am defining a model 

```
class User(Base):
    __tablename__ = "users"
    id = Column(Integer, Sequence('user_id_seq'), primary_key=True)
    password = Column(PasswordType(
        schemes=['pbkdf2_sha512', 'md5_crypt'],
        deprecated=['md5_crypt'],
        max_length=1000))
```

and when I run the migration I obtain the following in the migration py file:
```
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('access_code', sqlalchemy_utils.types.password.PasswordType(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
```

note that `max_length=1000` was replaced by `length=1000`

Then when I run the migration I obtain an error:
`KeyError: "unknown CryptContext keyword: 'length'"`

**Expected behavior**
the migration shouldn't change the argument name.

If I hardcode max_length in the migration file everything works fine.

**Error**
`KeyError: "unknown CryptContext keyword: 'length'"`

**Versions.**
 - OS: Ubuntu 18.04
 - Python: 3.7.10
 - Alembic: 1.5.8
 - SQLAlchemy: 1.4.7
 - sqlalchemy-utils 0.37.1
 - Database: MySql 8.0.23
 - DBAPI:

**Comment by zzzeek** [comment]
this is likely a change that needs to occur on the sqlalchemy-utils side.      Alembic is mostly calling repr() on the object, so you probably need to report this over there.
