### ISSUE TITLE
add some kind of option/recipe to turn TinyInt + length 1 into a boolean for mysql

### ISSUE THREAD

**Issue by sqlalchemy-bot** [sqlalchemy/alembic#84]
**Migrated issue, originally created by Lucian Ursu ([@lucianu](https://github.com/lucianu))**

I have a field which is defined as Boolean in my SQLAlchemy models and represented as TinyINT in the MySQL database. Every time I run alembic revision --autogenerate, the migration contains code to convert the field from TinyINT to Boolean.

**Comment by zzzeek** [comment]
this is a dupe of #605 which has finally been resolved.
