### ISSUE TITLE
Can no longer use `%(here)s` in script option in alembic.ini on windows

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/alembic#841]
**Describe the bug**
The change in d4146eceb4258ab5a4af9fa6c711e6677e19e91b has switched to using shlex to split the command line agurment.

Taking the example config:
```ini
hooks=black
black.type=console_scripts
black.entrypoint=black
black.options=--config %(here)s/pyproject.toml
```
The problem is that on windows a path is expanded as `C:\\foo\\bar\\baz` and is transformed to `C:foobabaz` that is definitely not the same.
~~Quoting the path with `"`, like this `"%(here)s/pyproject.toml"`, seem to fix the issue.~~ Also setting `posix=False` on windows seems to be a fix

**Comment by CaselIT** [comment]
I've done some other tests, and using `"` does not work

**Comment by sqla-tester** [comment]
**CaselIT** has proposed a fix for this issue in the **master** branch:

**Fixed a bug where paths defined in post-write hook options** https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/2820
