### ISSUE TITLE
Autogenerate creates duplicate commands for unique constraints

### ISSUE THREAD

**Issue by enkelli** [sqlalchemy/alembic#844]
**Describe the bug**

`alembic revision --autogenerate` creates duplicate lines for unique constraints in `upgrade()` method.
It does not affect actual upgrade in DB, but it looks strange in revision script.

**Expected behavior**
No duplicate records in revision script.

**To Reproduce**

After `alembic init alembic` I added the following code to `alembic/env.py`
```py
import sqlalchemy as sa
import sqlalchemy.orm as orm 
...

Base = orm.declarative_base()

class TestTable(Base):
    __tablename__ = 'test_table'

    id = sa.Column(sa.Integer, primary_key=True)
    value = sa.Column(sa.String, unique=True)

target_metadata = Base.metadata
```

**Error**

After `alembic revision --autogenerate` I got the following upgrade script:
```py
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('value'),
    sa.UniqueConstraint('value') #  <--- This is duplicate
    )   
    # ### end Alembic commands ###

```

**Versions.**
 - OS: Arch Linux (5.12.2)
 - Python: 3.9.5
 - Alembic: 1.6.0+
 - SQLAlchemy: 1.4.15
 - Database: PostgreSQL 12.6 (Debian 12.6-1.pgdg100+1)

**Additional context**
This happens on version 1.6.0 and newer.
1.5.8 works as expected.

**Have a nice day!**

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Remove unique/index flags when copying table** https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/2834

**Comment by zzzeek** [comment]
thanks for reporting

**Comment by mgasner** [comment]
Believe that this fix may have broken some previously valid migrations -- we have observed https://github.com/dagster-io/dagster/blob/master/python_modules/libraries/dagster-postgres/dagster_postgres/alembic/versions/c63a27054f08_add_snapshots_to_run_storage.py#L36 failing on alembic 1.6.4 (passes on 1.6.3) with the following:
```

E               sqlalchemy.exc.ProgrammingError: (psycopg2.errors.InvalidForeignKey) there is no unique constraint matching given keys for referenced table "snapshots"
--



E
--



E               [SQL: ALTER TABLE runs ADD FOREIGN KEY(snapshot_id) REFERENCES snapshots (snapshot_id)]
--


<span class="term-fg31 term-fg1">E               (Background on this error at: http://sqlalche.me/e/14/f405)</span>```

I don't have a minimal repro for this but will try to get one in the next couple of days.

**Comment by zzzeek** [comment]
> Believe that this fix may have broken some previously valid migrations -- we have observed https://github.com/dagster-io/dagster/blob/master/python_modules/libraries/dagster-postgres/dagster_postgres/alembic/versions/c63a27054f08_add_snapshots_to_run_storage.py#L36 failing on alembic 1.6.3 (passes on 1.6.2) with the following:
> 
> ```
> sqlalchemy.exc.ProgrammingError: (psycopg2.errors.InvalidForeignKey) there is no unique constraint matching given keys for referenced table "snapshots"
> [SQL: ALTER TABLE runs ADD FOREIGN KEY(snapshot_id) REFERENCES snapshots (snapshot_id)]
> --
> ```
> 
> I don't have a minimal repro for this but will try to get one in the next couple of days.

so crazy there were no tests for that, see #848
