### ISSUE TITLE
unique/index flag broken by  acc82bf

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/alembic#848]
the create_table we changed in #844 is also used by the op.create_table() op where we don't have a reflected table to work with so the check we added must be made more specific still.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**differentiate CreateTableOp from model vs. op.create_table()** https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/2839
