### ISSUE TITLE
`DropIndexOp` does not render keyword arguments such as `postgresql_concurrently`

### ISSUE THREAD

**Issue by jetzhou** [sqlalchemy/alembic#849]
**Describe the bug**
https://github.com/sqlalchemy/alembic/commit/101136605150d50fe0a3b6e7bc6c2ad90bbeb9df added kwargs support to drop index operation in SQL generation. However, in autogenerate render step, an operation such as this one:
```py
alembic.operations.ops.DropIndexOp(
    'example_index',
    postgresql_concurrently=True,
)
```
will be rendered to
```py
op.drop_index(op.f('example_index'))
```
which ignores the `postgresql_concurrently` kwarg.

**Expected behavior**
```py
alembic.operations.ops.DropIndexOp(
    'example_index',
    postgresql_concurrently=True,
)
```
should render in autogenerate to 
```py
op.drop_index(op.f('example_index'), postgresql_concurrently=True)
```

**To Reproduce**
Test code that does not pass
```py
    def test_render_drop_index_custom_kwarg(self):
        t = Table(
            "test",
            MetaData(),
            Column("id", Integer, primary_key=True),
            Column("active", Boolean()),
            Column("code", String(255)),
        )
        idx = Index(None, t.c.active, t.c.code, somedialect_foobar="option")
        op_obj = ops.DropIndexOp.from_index(idx)
        eq_ignore_whitespace(
            autogenerate.render_op_text(self.autogen_context, op_obj),
            "op.drop_index(op.f('ix_test_active'), table_name='test', "
            "somedialect_foobar='option')",
        )

```

**Versions.**
 - OS: Ubuntu 21.04 
 - Python: 3.9.5
 - Alembic: 1.6.4
 - SQLAlchemy: 1.3.19
 - Database: PostgreSQL
 - DBAPI: psycopg

**Additional context**
Proposed fix: https://github.com/jetzhou/alembic/commit/6392a287179ed746f709ba1e0e07ccab3ea8e4c6

**Have a nice day!**

**Comment by zzzeek** [comment]
will have to look and see if we have existing precedent for this, which I think we should, like for indexes etc.

**Comment by zzzeek** [comment]
looks like you have  a fix ready!  that's a PR, please send.    I assume most of the other constructs are OK in this regard

**Comment by jetzhou** [comment]
Thanks @zzzeek for the triage! Created PR for this.

**Comment by zzzeek** [comment]
thanks for following all the guidelines on this!   most people dont :)  but it makes it easy

**Comment by sqla-tester** [comment]
**Jet Zhou** has proposed a fix for this issue in the **master** branch:

**Add kwargs support to DropIndexOp autogenerate render** https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/2844

**Comment by zzzeek** [comment]
thanks!  1.6.5 is released.

**Comment by jetzhou** [comment]
Woohoo! Thanks for taking a look and the quick + efficient PR prorcess!
