### ISSUE TITLE
Create set of specific "suite" tests suitable for testing with third-party dialects

### ISSUE THREAD

**Issue by gordthompson** [sqlalchemy/alembic#855]
**Is your feature request related to a problem? Please describe.**
Alembic lacks a set of specific "suite" tests similar to what SQLAlchemy has for supporting third-party dialects.

**Describe the solution you'd like**
Create such a test suite, presumably in "alembic/testing/suite". Ensure that those tests are visible from a normal `pip install alembic`.

**Describe alternatives you've considered**
It is possible to run all of the current tests from the Alembic source tree, but that includes many tests that are either strictly internal to Alembic or address idiosyncrasies of the SQLA internal dialects (SQLite, Oracle, etc.).

**First steps**
Review current Alembic tests and identify candidates for inclusion in the "suite" tests, specifically those that are not
- testing Alembic internals (database-agnostic), or
- testing some esoteric behaviour for one of the SQLA internal dialects.

**Comment by sqla-tester** [comment]
**Gord Thompson** has proposed a fix for this issue in the **master** branch:

**Implement "test suite" (WIP)** https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/2867

**Comment by gordthompson** [comment]
Okay, with the current Alembic mods in …

https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/2867

… I've gotten the tests to run from within a sqlalchemy-cockroachdb source tree:

https://github.com/gordthompson/sqlalchemy-cockroachdb/tree/alembic_suite

I moved "test_op.py" into the Alembic suite because it was one of the tests that tripped up the CrDB dialect and therefore provided the opportunity to work around the issues

https://github.com/gordthompson/sqlalchemy-cockroachdb/blob/alembic_suite/test/test_suite_alembic.py

So now I guess we need to decide what *other* Alembic tests we want to move from "local" tests to "suite" tests. Any suggestions, @zzzeek ?

**Comment by zzzeek** [comment]
OK so that's great, good start, so what we need to do here and I will help, is identify "backend" tests and also write new ones that only exercise things the DB impl needs.
