### ISSUE TITLE
re-vendor "editor"

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/alembic#856]
the python-editor package now has a deprecation warning:

    DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives

project looks to be not maintained since 2019:   https://github.com/fmoo/python-editor
 
a newer package looks to be maintained but has lots of dependencies (two) for what is like a ten line program: https://github.com/rec/editor    

this "editor" concern is very trivial and not worth relying upon these come-and-go ten line packages out there so I suggest we re-vendor this.   our original impl can be seen in 7b91b325ff43a0e9235e0f15b57391,

**Comment by sqla-tester** [comment]
**CaselIT** has proposed a fix for this issue in the **master** branch:

**Revendor editor and make dateutil optional** https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/2872
