### ISSUE TITLE
KeyError on postgresql_include

### ISSUE THREAD

**Issue by sbronson** [sqlalchemy/alembic#874]
Like #513, but for PostgreSQL.  Porting e01041b worked for me.

**Comment by CaselIT** [comment]
Thanks for reporting.

If you can open a pr with the porting you done we can merge it. Thanks

**Comment by Robak23** [comment]
Do you know in which version will it be included? Is there some workaround for now?

**Comment by zzzeek** [comment]
hopefully 1.7.0

**Comment by sqla-tester** [comment]
**Steven Bronson** has proposed a fix for this issue in the **master** branch:

**Fix postgresql_include in create_index** https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/3010
