### ISSUE TITLE
change rules for SQLIte batch alter_column for special cases

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/alembic#883]
### Discussed in https://github.com/sqlalchemy/alembic/discussions/882

According to this SQLite's official document, "add column" with a primary key or unique key constraint, or having some kinds of server default needs the recreate style:

https://www.sqlite.org/lang_altertable.html#alter_table_add_column

code here we are changing is in sqlite.py

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**qualify sqlite batch add column for dynamic defaults** https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/2995
