### ISSUE TITLE
Wheels are createed with `py2.py3` compatibility tag

### ISSUE THREAD

**Issue by layday** [sqlalchemy/alembic#893]
Alembic > 1.7 does not support Python 2, but wheels are created with the `py2.py3` compatibility tag in the filename, declaring compatibility with Python 2.

**Comment by zzzeek** [comment]
great, are you sending a PR ?

**Comment by zzzeek** [comment]
see it, thanks

**Comment by CaselIT** [comment]
Does py2 try to install it, or its still blocked by the python_version constraint?

Asking to check if we need to release a 1.7.1 and yank 1.7 or not

**Comment by zzzeek** [comment]
i deleted the univresal wheel file from pypi and manually put up a py3 only wheel so there's no rush on this

**Comment by sqla-tester** [comment]
**layday** has proposed a fix for this issue in the **master** branch:

**Do not tag wheel as being compatible with Python 2** https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/3031

**Comment by CaselIT** [comment]
I did not remember that files could be deleted from pypi

**Comment by zzzeek** [comment]
they can only be deleted "forever", meaning they can't be replaced.   this is the one situation where we dont actually have to replace it, so it works .
