### ISSUE TITLE
Optional arguments in pyi file are considered positional by mypy

### ISSUE THREAD

**Issue by cblegare** [sqlalchemy/alembic#895]
**Describe the bug**

In the `pyi` files, some arguments marked as `Optional` miss a default value, and thus are considered positional (hence required) by mypy.

**Expected behavior**

Keyword and optional arguments should be annotated as such.

**To Reproduce**

Write a migration, use the `op.drop_table` function, run mypy.

**Error**

```
migrations/versions/954fd0bb09be_add_users_table.py:26: error: Missing positional argument "schema" in call to "drop_table"
        op.drop_table("users")
        ^
```

**Versions.**
 - Python: 3.8
 - Alembic: 1.7.0
 - SQLAlchemy: 1.4.17

**Suggestion**

Maybe add default values to Optional arguments in pyi files?

**Have a nice day!**

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**restore default values for keyword arguments in stubs** https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/3032

**Comment by zzzeek** [comment]
if you could click on that review and see that I did it right that would be helpful.   cc @CaselIT

**Comment by cblegare** [comment]
Haven't run it locally, but this indeed looks good to me :)

**Comment by CaselIT** [comment]
same for me
