### ISSUE TITLE
Mypy failure for `create_table_comment`

### ISSUE THREAD

**Issue by nbhargava** [sqlalchemy/alembic#903]
**Describe the bug**

`mypy` in child repos fail for `create_table_comment`. The stubs have that keyword argument `existing_comment` has type `None` instead of type `Optional[str]`.

**Expected behavior**

Backwards compatibility should be maintained and the type of `existing_comment` in `create_table_comment` should be `Optional[str]`.

**To Reproduce**
Please try to provide a [Minimal, Complete, and Verifiable](http://stackoverflow.com/help/mcve) example, with the migration script and/or the SQLAlchemy tables or models involved.
See also [Reporting Bugs](https://www.sqlalchemy.org/participate.html#bugs) on the website.

Run `mypy` over the following with alembic 1.7.1.

```py
from alembic import op

op.create_table_comment('a', 'b', 'c')
```

**Error**

```
foo.py:3: error: Argument 3 to "create_table_comment" has incompatible type "str"; expected "None"  [arg-type]
```

**Versions.**
 - OS: macOS 10.15.7
 - Python: 3.8.8
 - Alembic: 1.7.1
 - SQLAlchemy: 1.4.23
 - Database: N/A
 - DBAPI: N/A

**Additional context**
N/A

**Comment by CaselIT** [comment]
Thanks for reporting!

**Comment by CaselIT** [comment]
> Backwards compatibility should be maintained and the type of existing_comment in create_table_comment should be Optional[str].

the error is definitely in the stubs, no change was made on the logic

**Comment by sqla-tester** [comment]
**Colin Adams** has proposed a fix for this issue in the **main** branch:

**Fix type annotation in `op.create_table_comment`** https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/4567
