### ISSUE TITLE
Alembic testing requires SQLAlchemy >= 1.4

### ISSUE THREAD

**Issue by JordanP** [sqlalchemy/alembic#905]
**Describe the bug**
`alembic/testing/__init__.py` imports `from sqlalchemy.testing.config import combinations` but that function has only been introduced in SQLA 1.4 (in https://github.com/sqlalchemy/sqlalchemy/commit/ed553fffd65a063d6dbdb3770d1fa0124bd55e23#diff-25990d7b3400b883e380180d22e5e707a21c6ab9510b39bc999b7555b33a83d7R22)

**Expected behavior**
Either `install_requires` should specify `SQLAlchemy>=1.3.0` or `alembic/testing` should not import those functions 

**To Reproduce**
`pip install sqlalchemy==1.3.3 alembic==1.7.1`

```py
import alembic.testing
```

**Error**

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/venv/lib/python3.8/site-packages/alembic/testing/__init__.py", line 9, in <module>
    from sqlalchemy.testing.config import combinations
ImportError: cannot import name 'combinations' from 'sqlalchemy.testing.config' (/tmp/venv/lib/python3.8/site-packages/sqlalchemy/testing/config.py)
```

**Comment by CaselIT** [comment]
Hi,

`combinations` was added during the 1.3 series, so you should install one of the later versions. The pipelines tests using the 1.3 series: https://github.com/sqlalchemy/alembic/actions/runs/1183868493

Was there a particular reason for using 1.3.3?

**Comment by CaselIT** [comment]
The first version that added it was the 1.3.11

**Comment by JordanP** [comment]
@CaselIT you are right. 

No specific reason for 1.3.3,I am going to upgrade to the latest version of 1.3. Sorry for the bogus bug report. Thanks for your insights !

**Comment by CaselIT** [comment]
No problem
