### ISSUE TITLE
Outdated cookbook suggestion to use branched connections 

### ISSUE THREAD

**Issue by chrisjsewell** [sqlalchemy/alembic#908]
**Describe the bug**

In https://alembic.sqlalchemy.org/en/latest/cookbook.html#sharing-a-connection-with-a-series-of-migration-commands-and-environments,
it gives a recipe using a branched connection.
However, as per `Connection._branch`:

> deprecated:: 1.4 the "branching" concept will be removed in SQLAlchemy 2.0 as well as the "Connection.connect()" method which is the only consumer for this.

**Expected behavior**

The section would provide a "v2 compliant" solution

Thanks!

**Comment by zzzeek** [comment]
agree, the general idea is to just lose the "with connectable.connect()" part, it was trying to guess if the given "connection" were an Engine or Connection.    no more guessing, it's a Connection.   can accept a PR for this.

**Comment by chrisjsewell** [comment]
Thanks for the rapid response!
So to clarify, you feel there should be no side effects to just running with no context manager?

(p.s. just spent the last few hours watching your v2 YouTube tutorial; super helpful 🙏)

**Comment by zzzeek** [comment]
yup something like that, because the recipe has "with connctoin.begin()" on the outside of the alembic command as it is, you're already inside a transactional context
