### ISSUE TITLE
allow a migration name to be a sub-package rather than a single file

### ISSUE THREAD

**Issue by sqlalchemy-bot** [sqlalchemy/alembic#91]
**Migrated issue, originally created by Derek Harland ([@donkopotamus](https://github.com/donkopotamus))**

I wonder if it might be a nice enhancement to allow a revision to be a python package instead of being constrained to be a python module.

This may have a few advantages:

- if a revision consists of a lot of code, or support functions specific to that revision, it might be nicer to be able to split that amongst several files.

  - this is particularly the case for the base revision of a database, which could be large.

- it might allow for easier storage of symbolic names//tags for a revision. eg if we had a file structure something like:

    - `versions/<revision_number>/__init__.py`

        - upgrade/downgrade code goes here

    - `versions/<revision_number>/cfg.py`

        - the values of the up/down revisions could be stored in here

        - this means the revision tree could be analysed by only loading `cfg.py` for such revisions

        - a symbolic name for the revision could be in here etc.

**Comment by zzzeek** [comment]
note if this were to happen it would likely be very much mixed in with #648

**Comment by zzzeek** [comment]
it's been 9 years.  For many years we have supported explicit branching and merging so the very old "splice branches" use case is no longer an issue, and a lot of what was mentioned here seems to suggest that use case.     The overall versions folder can be a package now, you now can have an `__init__.py` file in your version locations if you want using ``--package`` as added in #463, but that doesn't directly imply each version being a sub-package which I think is what was suggested here.  However you can certainly have sub-packages in your versions folder, and migrations that make use of lots of other functions in other modules are commonplace now.

so while it still might be neat that the version file itself is actually `version_dir/__init__.py`, there hasn't been any other requests for this kind of thing and you can kind of approximate this setup on a per-version basis if you really wanted to (and people probably are doing so), but of course autogenerate doesn't build that up.    Generally though I don't have plans to work on this myself, so closing.
