### ISSUE TITLE
StringEncryptedType: VARCHAR requires a length on dialect mysql

### ISSUE THREAD

**Issue by POD666** [sqlalchemy/alembic#912]
**Describe the bug**
My tests when used against MySql DB leads to the following exception:
```python
from alembic.autogenerate import produce_migrations
...
diff = produce_migrations(mc, target_metadata)
...
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
self = <sqlalchemy.dialects.mysql.base.MySQLTypeCompiler object at 0x7f40af211080>
type_ = String(), kw = {}

def visit_VARCHAR(self, type_, **kw):
        if type_.length:
            return self._extend_string(type_, {}, "VARCHAR(%d)" % type_.length)
        else:
            raise exc.CompileError(
>               "VARCHAR requires a length on dialect %s" % self.dialect.name
            )
E           sqlalchemy.exc.CompileError: VARCHAR requires a length on dialect mysql
/usr/local/lib/python3.6/site-packages/sqlalchemy/dialects/mysql/base.py:2081: CompileError
```
This seems to be related to a usage of `StringEncryptedType` from `sqlalchemy_utils.types.encrypted.encrypted_type`.
My column definition looks like this:
```
credentials = Column(StringEncryptedType(String, get_fernet_key, FernetEngine), nullable=True, length=150)
```
And `_tokenize_column_type` function get `StringEncryptedType()` as a value for `column.type` but `column.type.underlying_type` is more desired in my case as it's equal to `varchar(150)`.

**Expected behavior**
* As an option, `column.type.underlying_type` might be used if available in `_tokenize_column_type`
* Alternatively need to fix a column that is passed to `_tokenize_column_type`

**To Reproduce**
might be hard to reproduce

**Error**

<details>
  <summary>Full traceback</summary>
  
  ```
/usr/local/lib/python3.6/site-packages/alembic/autogenerate/api.py:133: in produce_migrations
    compare._populate_migration_script(autogen_context, migration_script)
/usr/local/lib/python3.6/site-packages/alembic/autogenerate/compare.py:25: in _populate_migration_script
    _produce_net_changes(autogen_context, upgrade_ops)
/usr/local/lib/python3.6/site-packages/alembic/autogenerate/compare.py:55: in _produce_net_changes
    autogen_context, upgrade_ops, schemas
/usr/local/lib/python3.6/site-packages/alembic/util/langhelpers.py:307: in go
    fn(*arg, **kw)
/usr/local/lib/python3.6/site-packages/alembic/autogenerate/compare.py:94: in _autogen_for_tables
    autogen_context,
/usr/local/lib/python3.6/site-packages/alembic/autogenerate/compare.py:227: in _compare_tables
    inspector,
/usr/local/lib/python3.6/contextlib.py:81: in __enter__
    return next(self.gen)
/usr/local/lib/python3.6/site-packages/alembic/autogenerate/compare.py:340: in _compare_columns
    metadata_col,
/usr/local/lib/python3.6/site-packages/alembic/util/langhelpers.py:307: in go
    fn(*arg, **kw)
/usr/local/lib/python3.6/site-packages/alembic/autogenerate/compare.py:924: in _compare_type
    conn_col, metadata_col
/usr/local/lib/python3.6/site-packages/alembic/runtime/migration.py:651: in _compare_type
    return self.impl.compare_type(inspector_column, metadata_column)
/usr/local/lib/python3.6/site-packages/alembic/ddl/impl.py:439: in compare_type
    metadata_params = self._tokenize_column_type(metadata_column)
/usr/local/lib/python3.6/site-packages/alembic/ddl/impl.py:345: in _tokenize_column_type
    definition = self.dialect.type_compiler.process(column.type).lower()
/usr/local/lib/python3.6/site-packages/sqlalchemy/sql/compiler.py:400: in process
    return type_._compiler_dispatch(self, **kw)
/usr/local/lib/python3.6/site-packages/sqlalchemy/sql/visitors.py:95: in _compiler_dispatch
    return meth(self, **kw)
/usr/local/lib/python3.6/site-packages/sqlalchemy/sql/compiler.py:3443: in visit_type_decorator
    return self.process(type_.type_engine(self.dialect), **kw)
/usr/local/lib/python3.6/site-packages/sqlalchemy/sql/compiler.py:400: in process
    return type_._compiler_dispatch(self, **kw)
/usr/local/lib/python3.6/site-packages/sqlalchemy/sql/visitors.py:95: in _compiler_dispatch
    return meth(self, **kw)
/usr/local/lib/python3.6/site-packages/sqlalchemy/sql/compiler.py:3421: in visit_string
    return self.visit_VARCHAR(type_, **kw)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
self = <sqlalchemy.dialects.mysql.base.MySQLTypeCompiler object at 0x7f40af211080>
type_ = String(), kw = {}

def visit_VARCHAR(self, type_, **kw):
        if type_.length:
            return self._extend_string(type_, {}, "VARCHAR(%d)" % type_.length)
        else:
            raise exc.CompileError(
>               "VARCHAR requires a length on dialect %s" % self.dialect.name
            )
E           sqlalchemy.exc.CompileError: VARCHAR requires a length on dialect mysql
/usr/local/lib/python3.6/site-packages/sqlalchemy/dialects/mysql/base.py:2081: CompileError
```
</details>

**Versions.**
 - OS: docker image python:3.6
 - Python: 3.6.9
 - Alembic: latest master
 - SQLAlchemy: 1.3.18
 - Database: MySql
 - DBAPI:

**Have a nice day!**

**Comment by POD666** [comment]
I have prepared a draft PR: https://github.com/sqlalchemy/alembic/pull/913

Let me know if you know a better fix. And suggest a test to add, please.

**Comment by CaselIT** [comment]
Hi,

I'm leaning on treating this as a sqlalchemy utils bug. For sure it cannot be solved ad the proposed pr, since things would become a mess fast implementing the fix that way.

Using `StringEncryptedType(String(length=250), get_fernet_key, FernetEngine)` does not work?

**Comment by POD666** [comment]
@CaselIT, yeah, I tried with `String(length=250)` and it doesn't work too.

Should I reopen this issue in sqlalchemy utils instead?

**Comment by CaselIT** [comment]
Let's wait for mike opinion, maybe it's something that's missing on out part.

**Comment by POD666** [comment]
JFYI
With the fix from my PR, I get this message from running the test:
```
alembic.autogenerate.compare:compare.py:998 Detected type change from VARCHAR(length=8192) to StringEncryptedType() on 'mytable.credentials'
```
And `alembic revision --autogenerate` generates an empty migration.
So, overall looks like the column is only recognizable as VARCHAR from DB (NVM length here).

**Comment by zzzeek** [comment]
Not at my machine right now but the pr in question refers to a sqlalchemy-utils name, so this is certainly an issue for that tracker.

**Comment by CaselIT** [comment]
Do we illustrate how to create user types in a way that they are supported in alembic?

**Comment by zzzeek** [comment]
Im not following in this issue where something is going wrong.  if the issue is that autogenerate is not rendering the type correctly, the requirements for autogenerate of types is docuemnted at https://alembic.sqlalchemy.org/en/latest/autogenerate.html#affecting-the-rendering-of-types-themselves , basically, make sure `__repr__()` does the right thing.

if this type is not working in context of running a create_table operation then that's just a bug in the type itself, it should not be specific to alembic.

**Comment by CaselIT** [comment]
My question was regarding how user types should be treated. For this type it seems alembic renders it a varchar, and I wondered should it instead render it as `StringEncryptedType`. But looking at the documentation it seems the issue is of the type.

Alternatively a custom `render_item` could be used to support it as in the documentation example

@POD666 it's probably best to open an issue on their tracker. we can re-open this if there is something actionable on alembic part
