### ISSUE TITLE
Generate linter friendly output by default

### ISSUE THREAD

**Issue by abitrolly** [sqlalchemy/alembic#924]
**Describe the bug**

Generated migrations are not linter friendly. `black` fails, because migrations use single quotes. [`isort`](https://github.com/PyCQA/isort) because imports are not properly ordered.
```diff
-from alembic import op
-import sqlalchemy as sa
+import sqlalchemy as sa
+
+from alembic import op
```
 Perhaps there are more issues, but at least these two could already make it better.

**Expected behavior**

Generated migration to be `black` and `isort` compatible.

**Comment by CaselIT** [comment]
Hi,

you are free to modify the template file however you want.
Regarding the formatting, anyone has its own preference, so to address that alembic supports ["post_write_hooks"](https://alembic.sqlalchemy.org/en/latest/autogenerate.html#post-write-hooks) for exactly this use case.
