### ISSUE TITLE
create_check_constraint condition argument typing incorrect

### ISSUE THREAD

**Issue by liverpool1026** [sqlalchemy/alembic#928]
**Describe the bug**
The typing of condition argument is incorrect according to the documentation.
Definition:
create_check_constraint(constraint_name: Optional[str], table_name: str, condition: **BinaryExpression**, schema: Optional[str] = None, **kw) → Optional[Table]

The definition specifies the type for condition must be BinaryExpression, but in the documentation below.

condition¶ – SQL expression that’s the condition of the constraint. Can be a **string** or SQLAlchemy expression language structure.

https://alembic.sqlalchemy.org/en/latest/ops.html#alembic.operations.Operations.create_check_constraint

**Expected behaviour**
The typing for condition should be updated.

create_check_constraint(constraint_name: Optional[str], table_name: str, condition: **Union[str, BinaryExpression]**, schema: Optional[str] = None, **kw) → Optional[Table]

**To Reproduce**

```py
from alembic import op


def upgrade() -> None:

    op.create_check_constraint(
        "check_constraint",
        "table_name",
        "applies_from_time < applies_to_time"
    )

```

Then run mypy test.py

**Error**

```
test.py:9: error: Argument 3 to "create_check_constraint" has incompatible type "str"; expected "BinaryExpression[Any, Any, Any]"
```

**Versions.**
 - OS: Linux Ubuntu 18.04
 - Python: 3.6
 - Alembic:1.73
 - SQLAlchemy: 1.3.24
 - sqlalchemy-stubs: 0.4
 - mypy: 0.910
 - Database: Not need here
 - DBAPI: Not need here

**Additional context**
None
**Have a nice day!**

**Comment by CaselIT** [comment]
thanks for reporting
