### ISSUE TITLE
Generated version doesnt support PEP8's: E128

### ISSUE THREAD

**Issue by IlayG01** [sqlalchemy/alembic#954]
**problem**
Generated version script from `alembic revision <...>` doesn't support PEP8's E128.
For someone like me that uses pre-commit & linters trigger that causes some dirty work every revision I make.
I have to say this is not a **BUG** but something that would be nice to fix(if you can refer me to the relevant code id love to try and fix this myself).
Example:
```py
# does not support E128
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('full_name', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_user_full_name'), 'user', ['full_name'], unique=False)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    # ### end Alembic commands ###
```

**Expected behavior**
```py
#  supports E128
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'user',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('full_name', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_full_name'), 'user', ['full_name'], unique=False)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    # ### end Alembic commands ###
```

**Versions.**
Im using alembic 1.7.4

**Have a nice day!**

**Comment by zzzeek** [comment]
hi -

did you configure the [post write hooks](https://alembic.sqlalchemy.org/en/latest/autogenerate.html?highlight=black#applying-post-processing-and-python-code-formatters-to-generated-revisions) correctly ?
