### ISSUE TITLE
Command to create a raw alembic_version table

### ISSUE THREAD

**Issue by kasium** [sqlalchemy/alembic#964]
### Discussed in https://github.com/sqlalchemy/alembic/discussions/962

<div type='discussions-op-text'>

<sup>Originally posted by **kasium** November 10, 2021</sup>
Hey,
not sure if this use case is somehow common, but I would like to request it:

In my application, I use the alembic_version table as a synchronization point, meaning that multiple instances of the app are starting in parallel and will try to lock the alembic_version table in order to execute a migration. However, this approach only works if the alembic_version table already exists.

So, my question would be, if it would be possible to a command to generate a raw alembic_version table? It would help me a lot. Currently I use heads and stamp together, but the code doesn't make it obvious want I want to do</div>

**Comment by sqla-tester** [comment]
**Kai Mueller** has proposed a fix for this issue in the **main** branch:

**Add new ensure_version command** https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/3302
