### ISSUE TITLE
Identifying and dealing with potentially reserved names in databases (i.e. in MySQL)

### ISSUE THREAD

**Issue by andreit23** [sqlalchemy/alembic#967]
I ran into an issue using a reserved name for a table where the table name is not encased in " ` ".

**Expected behavior**
Reserved names must be enclosed in " ` ". 

In this case, trying to create a table with name `lead` will result in an SQL syntax error using MySQL

**To Reproduce**
 - Using Ubuntu 20
 - Install MySQL
 - Install pymysql
 - Create an alembic environment
 - Create database and add the proper `mysql+pymysql://database_location:3306/dbname` in the alembic.ini
 - Create an alembic migration, add the following code:

```py
def upgrade():
    op.create_table(
        'lead',
        sa.Column('id', sa.Integer, primary_key=True),
        sa.Column('name', sa.String(50), nullable=False),
    )
```

**Error**

```
sqlalchemy.exc.ProgrammingError: (pymysql.err.ProgrammingError) (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'lead (\n\tid INTEGER NOT NULL AUTO_INCREMENT, \n\tname VARCHAR(50) NOT NULL, \n\tPRIMA' at line 1")
[SQL:
CREATE TABLE lead (
        id INTEGER NOT NULL AUTO_INCREMENT,
        name VARCHAR(50) NOT NULL,
        PRIMARY KEY (id)
)
```

**Versions.**
 - OS: Ubuntu 20
 - Python: 3.8.10
 - Alembic: 1.7.4
 - SQLAlchemy: 1.4.26

**Additional context**
I noticed this issue does not happen on Windows, so I believe this might be something related to special characters on linux.
I also noticed that if using tables or columns with capitals in them, they are automatically surrounded by the " ` " character.
Extending this to **all** tables and columns would resolve the issue.

**Have a nice day!**

**Comment by zzzeek** [comment]
SQLAlchemy handles quoting of reserved words automatically so there is no need to worry about this.  In this specific case, "lead" is a recently added reserved word for MySQL which was fixed as part of https://github.com/sqlalchemy/sqlalchemy/issues/7167 , released half an hour ago in SQLAlchemy 1.4.27.
