### ISSUE TITLE
Add BatchOperations return type annotation to batch_alter_table

### ISSUE THREAD

**Issue by vinay1337** [sqlalchemy/alembic#975]
https://github.com/sqlalchemy/alembic/blob/5fce5dbd53cd23c972e82f8cba91a3b4624e523b/alembic/operations/base.py#L210-L222

**Comment by sqla-tester** [comment]
**CaselIT** has proposed a fix for this issue in the **main** branch:

**Annotate batch_alter_table** https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/3894
