### ISSUE TITLE
mypy error: Argument 1 to "fileConfig" has incompatible type "Optional[str]"

### ISSUE THREAD

**Issue by scratchmex** [sqlalchemy/alembic#986]
**Describe the bug**

start with `alembic init migrations` and you will get the error. Basically `fileConfig` expects an `str` not `None`. By default when alembic is called via the cli the parameter is filled with `alembic.ini` but in the class definition of `Config` by default is None

**Expected behavior**

**To Reproduce**
Please try to provide a [Minimal, Complete, and Verifiable](http://stackoverflow.com/help/mcve) example, with the migration script and/or the SQLAlchemy tables or models involved.
See also [Reporting Bugs](https://www.sqlalchemy.org/participate.html#bugs) on the website.

```py
# Insert code here
```

**Error**

```
# Copy error here. Please include the full stack trace.
```

**Versions.**
 - OS: 
 - Python:
 - Alembic: alembic 1.7.6
 - SQLAlchemy:
 - Database:
 - DBAPI:

**Additional context**

**Have a nice day!**

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**add conditional for fileConfig()** https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/3578

**Comment by zzzeek** [comment]
sure thing
