### ISSUE TITLE
remove "pylons" app template for 1.8

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/alembic#987]
this template is from decades ago from the old pre-pyramid form of pylons and is certainly not functional, for example it refers to "wsgi_app" that isn't even created in the default case.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**remove pylons template** https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/3886
